// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akeyless

import (
	"context"
	"reflect"

	"errors"
	"github.com/akeyless-community/pulumi-akeyless/sdk/go/akeyless/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AuthMethodGcp struct {
	pulumi.CustomResourceState

	// Access expiration date in Unix timestamp (select 0 for access without expiry date)
	AccessExpires pulumi.IntPtrOutput `pulumi:"accessExpires"`
	// Auth Method access ID
	AccessId pulumi.StringOutput `pulumi:"accessId"`
	// The audience to verify in the JWT received by the client
	Audience pulumi.StringPtrOutput `pulumi:"audience"`
	// Subclaims to include in audit logs
	AuditLogsClaims pulumi.StringArrayOutput `pulumi:"auditLogsClaims"`
	// A CIDR whitelist with the IPs that the access is restricted to
	BoundIps pulumi.StringArrayOutput `pulumi:"boundIps"`
	// GCE only. A list of GCP labels formatted as key:value pairs that must be set on instances in order to authenticate. For multiple values repeat this flag.
	BoundLabels pulumi.StringArrayOutput `pulumi:"boundLabels"`
	// A list of GCP project IDs. Clients must belong to any of the provided projects in order to authenticate. For multiple values repeat this flag.
	BoundProjects pulumi.StringArrayOutput `pulumi:"boundProjects"`
	// GCE only. A list of regions. GCE instances must belong to any of the provided regions in order to authenticate. For multiple values repeat this flag.
	BoundRegions pulumi.StringArrayOutput `pulumi:"boundRegions"`
	// A list of Service Accounts. Clients must belong to any of the provided service accounts in order to authenticate. For multiple values repeat this flag.
	BoundServiceAccounts pulumi.StringArrayOutput `pulumi:"boundServiceAccounts"`
	// GCE only. A list of zones. GCE instances must belong to any of the provided zones in order to authenticate. For multiple values repeat this flag.
	BoundZones pulumi.StringArrayOutput `pulumi:"boundZones"`
	// Protection from accidental deletion of this auth method, [true/false]
	DeleteProtection pulumi.StringPtrOutput `pulumi:"deleteProtection"`
	// enforce role-association must include sub claims
	ForceSubClaims pulumi.BoolPtrOutput `pulumi:"forceSubClaims"`
	// Creds expiration time in minutes
	JwtTtl pulumi.IntPtrOutput `pulumi:"jwtTtl"`
	// Auth Method name
	Name pulumi.StringOutput `pulumi:"name"`
	// Service Account creds data, base64 encoded
	ServiceAccountCredsData pulumi.StringPtrOutput `pulumi:"serviceAccountCredsData"`
	// The type of the GCP Auth Method (iam/gce)
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewAuthMethodGcp registers a new resource with the given unique name, arguments, and options.
func NewAuthMethodGcp(ctx *pulumi.Context,
	name string, args *AuthMethodGcpArgs, opts ...pulumi.ResourceOption) (*AuthMethodGcp, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AuthMethodGcp
	err := ctx.RegisterResource("akeyless:index/authMethodGcp:AuthMethodGcp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthMethodGcp gets an existing AuthMethodGcp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthMethodGcp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthMethodGcpState, opts ...pulumi.ResourceOption) (*AuthMethodGcp, error) {
	var resource AuthMethodGcp
	err := ctx.ReadResource("akeyless:index/authMethodGcp:AuthMethodGcp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuthMethodGcp resources.
type authMethodGcpState struct {
	// Access expiration date in Unix timestamp (select 0 for access without expiry date)
	AccessExpires *int `pulumi:"accessExpires"`
	// Auth Method access ID
	AccessId *string `pulumi:"accessId"`
	// The audience to verify in the JWT received by the client
	Audience *string `pulumi:"audience"`
	// Subclaims to include in audit logs
	AuditLogsClaims []string `pulumi:"auditLogsClaims"`
	// A CIDR whitelist with the IPs that the access is restricted to
	BoundIps []string `pulumi:"boundIps"`
	// GCE only. A list of GCP labels formatted as key:value pairs that must be set on instances in order to authenticate. For multiple values repeat this flag.
	BoundLabels []string `pulumi:"boundLabels"`
	// A list of GCP project IDs. Clients must belong to any of the provided projects in order to authenticate. For multiple values repeat this flag.
	BoundProjects []string `pulumi:"boundProjects"`
	// GCE only. A list of regions. GCE instances must belong to any of the provided regions in order to authenticate. For multiple values repeat this flag.
	BoundRegions []string `pulumi:"boundRegions"`
	// A list of Service Accounts. Clients must belong to any of the provided service accounts in order to authenticate. For multiple values repeat this flag.
	BoundServiceAccounts []string `pulumi:"boundServiceAccounts"`
	// GCE only. A list of zones. GCE instances must belong to any of the provided zones in order to authenticate. For multiple values repeat this flag.
	BoundZones []string `pulumi:"boundZones"`
	// Protection from accidental deletion of this auth method, [true/false]
	DeleteProtection *string `pulumi:"deleteProtection"`
	// enforce role-association must include sub claims
	ForceSubClaims *bool `pulumi:"forceSubClaims"`
	// Creds expiration time in minutes
	JwtTtl *int `pulumi:"jwtTtl"`
	// Auth Method name
	Name *string `pulumi:"name"`
	// Service Account creds data, base64 encoded
	ServiceAccountCredsData *string `pulumi:"serviceAccountCredsData"`
	// The type of the GCP Auth Method (iam/gce)
	Type *string `pulumi:"type"`
}

type AuthMethodGcpState struct {
	// Access expiration date in Unix timestamp (select 0 for access without expiry date)
	AccessExpires pulumi.IntPtrInput
	// Auth Method access ID
	AccessId pulumi.StringPtrInput
	// The audience to verify in the JWT received by the client
	Audience pulumi.StringPtrInput
	// Subclaims to include in audit logs
	AuditLogsClaims pulumi.StringArrayInput
	// A CIDR whitelist with the IPs that the access is restricted to
	BoundIps pulumi.StringArrayInput
	// GCE only. A list of GCP labels formatted as key:value pairs that must be set on instances in order to authenticate. For multiple values repeat this flag.
	BoundLabels pulumi.StringArrayInput
	// A list of GCP project IDs. Clients must belong to any of the provided projects in order to authenticate. For multiple values repeat this flag.
	BoundProjects pulumi.StringArrayInput
	// GCE only. A list of regions. GCE instances must belong to any of the provided regions in order to authenticate. For multiple values repeat this flag.
	BoundRegions pulumi.StringArrayInput
	// A list of Service Accounts. Clients must belong to any of the provided service accounts in order to authenticate. For multiple values repeat this flag.
	BoundServiceAccounts pulumi.StringArrayInput
	// GCE only. A list of zones. GCE instances must belong to any of the provided zones in order to authenticate. For multiple values repeat this flag.
	BoundZones pulumi.StringArrayInput
	// Protection from accidental deletion of this auth method, [true/false]
	DeleteProtection pulumi.StringPtrInput
	// enforce role-association must include sub claims
	ForceSubClaims pulumi.BoolPtrInput
	// Creds expiration time in minutes
	JwtTtl pulumi.IntPtrInput
	// Auth Method name
	Name pulumi.StringPtrInput
	// Service Account creds data, base64 encoded
	ServiceAccountCredsData pulumi.StringPtrInput
	// The type of the GCP Auth Method (iam/gce)
	Type pulumi.StringPtrInput
}

func (AuthMethodGcpState) ElementType() reflect.Type {
	return reflect.TypeOf((*authMethodGcpState)(nil)).Elem()
}

type authMethodGcpArgs struct {
	// Access expiration date in Unix timestamp (select 0 for access without expiry date)
	AccessExpires *int `pulumi:"accessExpires"`
	// The audience to verify in the JWT received by the client
	Audience *string `pulumi:"audience"`
	// Subclaims to include in audit logs
	AuditLogsClaims []string `pulumi:"auditLogsClaims"`
	// A CIDR whitelist with the IPs that the access is restricted to
	BoundIps []string `pulumi:"boundIps"`
	// GCE only. A list of GCP labels formatted as key:value pairs that must be set on instances in order to authenticate. For multiple values repeat this flag.
	BoundLabels []string `pulumi:"boundLabels"`
	// A list of GCP project IDs. Clients must belong to any of the provided projects in order to authenticate. For multiple values repeat this flag.
	BoundProjects []string `pulumi:"boundProjects"`
	// GCE only. A list of regions. GCE instances must belong to any of the provided regions in order to authenticate. For multiple values repeat this flag.
	BoundRegions []string `pulumi:"boundRegions"`
	// A list of Service Accounts. Clients must belong to any of the provided service accounts in order to authenticate. For multiple values repeat this flag.
	BoundServiceAccounts []string `pulumi:"boundServiceAccounts"`
	// GCE only. A list of zones. GCE instances must belong to any of the provided zones in order to authenticate. For multiple values repeat this flag.
	BoundZones []string `pulumi:"boundZones"`
	// Protection from accidental deletion of this auth method, [true/false]
	DeleteProtection *string `pulumi:"deleteProtection"`
	// enforce role-association must include sub claims
	ForceSubClaims *bool `pulumi:"forceSubClaims"`
	// Creds expiration time in minutes
	JwtTtl *int `pulumi:"jwtTtl"`
	// Auth Method name
	Name *string `pulumi:"name"`
	// Service Account creds data, base64 encoded
	ServiceAccountCredsData *string `pulumi:"serviceAccountCredsData"`
	// The type of the GCP Auth Method (iam/gce)
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a AuthMethodGcp resource.
type AuthMethodGcpArgs struct {
	// Access expiration date in Unix timestamp (select 0 for access without expiry date)
	AccessExpires pulumi.IntPtrInput
	// The audience to verify in the JWT received by the client
	Audience pulumi.StringPtrInput
	// Subclaims to include in audit logs
	AuditLogsClaims pulumi.StringArrayInput
	// A CIDR whitelist with the IPs that the access is restricted to
	BoundIps pulumi.StringArrayInput
	// GCE only. A list of GCP labels formatted as key:value pairs that must be set on instances in order to authenticate. For multiple values repeat this flag.
	BoundLabels pulumi.StringArrayInput
	// A list of GCP project IDs. Clients must belong to any of the provided projects in order to authenticate. For multiple values repeat this flag.
	BoundProjects pulumi.StringArrayInput
	// GCE only. A list of regions. GCE instances must belong to any of the provided regions in order to authenticate. For multiple values repeat this flag.
	BoundRegions pulumi.StringArrayInput
	// A list of Service Accounts. Clients must belong to any of the provided service accounts in order to authenticate. For multiple values repeat this flag.
	BoundServiceAccounts pulumi.StringArrayInput
	// GCE only. A list of zones. GCE instances must belong to any of the provided zones in order to authenticate. For multiple values repeat this flag.
	BoundZones pulumi.StringArrayInput
	// Protection from accidental deletion of this auth method, [true/false]
	DeleteProtection pulumi.StringPtrInput
	// enforce role-association must include sub claims
	ForceSubClaims pulumi.BoolPtrInput
	// Creds expiration time in minutes
	JwtTtl pulumi.IntPtrInput
	// Auth Method name
	Name pulumi.StringPtrInput
	// Service Account creds data, base64 encoded
	ServiceAccountCredsData pulumi.StringPtrInput
	// The type of the GCP Auth Method (iam/gce)
	Type pulumi.StringInput
}

func (AuthMethodGcpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authMethodGcpArgs)(nil)).Elem()
}

type AuthMethodGcpInput interface {
	pulumi.Input

	ToAuthMethodGcpOutput() AuthMethodGcpOutput
	ToAuthMethodGcpOutputWithContext(ctx context.Context) AuthMethodGcpOutput
}

func (*AuthMethodGcp) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthMethodGcp)(nil)).Elem()
}

func (i *AuthMethodGcp) ToAuthMethodGcpOutput() AuthMethodGcpOutput {
	return i.ToAuthMethodGcpOutputWithContext(context.Background())
}

func (i *AuthMethodGcp) ToAuthMethodGcpOutputWithContext(ctx context.Context) AuthMethodGcpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthMethodGcpOutput)
}

// AuthMethodGcpArrayInput is an input type that accepts AuthMethodGcpArray and AuthMethodGcpArrayOutput values.
// You can construct a concrete instance of `AuthMethodGcpArrayInput` via:
//
//	AuthMethodGcpArray{ AuthMethodGcpArgs{...} }
type AuthMethodGcpArrayInput interface {
	pulumi.Input

	ToAuthMethodGcpArrayOutput() AuthMethodGcpArrayOutput
	ToAuthMethodGcpArrayOutputWithContext(context.Context) AuthMethodGcpArrayOutput
}

type AuthMethodGcpArray []AuthMethodGcpInput

func (AuthMethodGcpArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AuthMethodGcp)(nil)).Elem()
}

func (i AuthMethodGcpArray) ToAuthMethodGcpArrayOutput() AuthMethodGcpArrayOutput {
	return i.ToAuthMethodGcpArrayOutputWithContext(context.Background())
}

func (i AuthMethodGcpArray) ToAuthMethodGcpArrayOutputWithContext(ctx context.Context) AuthMethodGcpArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthMethodGcpArrayOutput)
}

// AuthMethodGcpMapInput is an input type that accepts AuthMethodGcpMap and AuthMethodGcpMapOutput values.
// You can construct a concrete instance of `AuthMethodGcpMapInput` via:
//
//	AuthMethodGcpMap{ "key": AuthMethodGcpArgs{...} }
type AuthMethodGcpMapInput interface {
	pulumi.Input

	ToAuthMethodGcpMapOutput() AuthMethodGcpMapOutput
	ToAuthMethodGcpMapOutputWithContext(context.Context) AuthMethodGcpMapOutput
}

type AuthMethodGcpMap map[string]AuthMethodGcpInput

func (AuthMethodGcpMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AuthMethodGcp)(nil)).Elem()
}

func (i AuthMethodGcpMap) ToAuthMethodGcpMapOutput() AuthMethodGcpMapOutput {
	return i.ToAuthMethodGcpMapOutputWithContext(context.Background())
}

func (i AuthMethodGcpMap) ToAuthMethodGcpMapOutputWithContext(ctx context.Context) AuthMethodGcpMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthMethodGcpMapOutput)
}

type AuthMethodGcpOutput struct{ *pulumi.OutputState }

func (AuthMethodGcpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthMethodGcp)(nil)).Elem()
}

func (o AuthMethodGcpOutput) ToAuthMethodGcpOutput() AuthMethodGcpOutput {
	return o
}

func (o AuthMethodGcpOutput) ToAuthMethodGcpOutputWithContext(ctx context.Context) AuthMethodGcpOutput {
	return o
}

// Access expiration date in Unix timestamp (select 0 for access without expiry date)
func (o AuthMethodGcpOutput) AccessExpires() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.IntPtrOutput { return v.AccessExpires }).(pulumi.IntPtrOutput)
}

// Auth Method access ID
func (o AuthMethodGcpOutput) AccessId() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringOutput { return v.AccessId }).(pulumi.StringOutput)
}

// The audience to verify in the JWT received by the client
func (o AuthMethodGcpOutput) Audience() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringPtrOutput { return v.Audience }).(pulumi.StringPtrOutput)
}

// Subclaims to include in audit logs
func (o AuthMethodGcpOutput) AuditLogsClaims() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.AuditLogsClaims }).(pulumi.StringArrayOutput)
}

// A CIDR whitelist with the IPs that the access is restricted to
func (o AuthMethodGcpOutput) BoundIps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.BoundIps }).(pulumi.StringArrayOutput)
}

// GCE only. A list of GCP labels formatted as key:value pairs that must be set on instances in order to authenticate. For multiple values repeat this flag.
func (o AuthMethodGcpOutput) BoundLabels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.BoundLabels }).(pulumi.StringArrayOutput)
}

// A list of GCP project IDs. Clients must belong to any of the provided projects in order to authenticate. For multiple values repeat this flag.
func (o AuthMethodGcpOutput) BoundProjects() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.BoundProjects }).(pulumi.StringArrayOutput)
}

// GCE only. A list of regions. GCE instances must belong to any of the provided regions in order to authenticate. For multiple values repeat this flag.
func (o AuthMethodGcpOutput) BoundRegions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.BoundRegions }).(pulumi.StringArrayOutput)
}

// A list of Service Accounts. Clients must belong to any of the provided service accounts in order to authenticate. For multiple values repeat this flag.
func (o AuthMethodGcpOutput) BoundServiceAccounts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.BoundServiceAccounts }).(pulumi.StringArrayOutput)
}

// GCE only. A list of zones. GCE instances must belong to any of the provided zones in order to authenticate. For multiple values repeat this flag.
func (o AuthMethodGcpOutput) BoundZones() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringArrayOutput { return v.BoundZones }).(pulumi.StringArrayOutput)
}

// Protection from accidental deletion of this auth method, [true/false]
func (o AuthMethodGcpOutput) DeleteProtection() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringPtrOutput { return v.DeleteProtection }).(pulumi.StringPtrOutput)
}

// enforce role-association must include sub claims
func (o AuthMethodGcpOutput) ForceSubClaims() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.BoolPtrOutput { return v.ForceSubClaims }).(pulumi.BoolPtrOutput)
}

// Creds expiration time in minutes
func (o AuthMethodGcpOutput) JwtTtl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.IntPtrOutput { return v.JwtTtl }).(pulumi.IntPtrOutput)
}

// Auth Method name
func (o AuthMethodGcpOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Service Account creds data, base64 encoded
func (o AuthMethodGcpOutput) ServiceAccountCredsData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringPtrOutput { return v.ServiceAccountCredsData }).(pulumi.StringPtrOutput)
}

// The type of the GCP Auth Method (iam/gce)
func (o AuthMethodGcpOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthMethodGcp) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type AuthMethodGcpArrayOutput struct{ *pulumi.OutputState }

func (AuthMethodGcpArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AuthMethodGcp)(nil)).Elem()
}

func (o AuthMethodGcpArrayOutput) ToAuthMethodGcpArrayOutput() AuthMethodGcpArrayOutput {
	return o
}

func (o AuthMethodGcpArrayOutput) ToAuthMethodGcpArrayOutputWithContext(ctx context.Context) AuthMethodGcpArrayOutput {
	return o
}

func (o AuthMethodGcpArrayOutput) Index(i pulumi.IntInput) AuthMethodGcpOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AuthMethodGcp {
		return vs[0].([]*AuthMethodGcp)[vs[1].(int)]
	}).(AuthMethodGcpOutput)
}

type AuthMethodGcpMapOutput struct{ *pulumi.OutputState }

func (AuthMethodGcpMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AuthMethodGcp)(nil)).Elem()
}

func (o AuthMethodGcpMapOutput) ToAuthMethodGcpMapOutput() AuthMethodGcpMapOutput {
	return o
}

func (o AuthMethodGcpMapOutput) ToAuthMethodGcpMapOutputWithContext(ctx context.Context) AuthMethodGcpMapOutput {
	return o
}

func (o AuthMethodGcpMapOutput) MapIndex(k pulumi.StringInput) AuthMethodGcpOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AuthMethodGcp {
		return vs[0].(map[string]*AuthMethodGcp)[vs[1].(string)]
	}).(AuthMethodGcpOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuthMethodGcpInput)(nil)).Elem(), &AuthMethodGcp{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthMethodGcpArrayInput)(nil)).Elem(), AuthMethodGcpArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthMethodGcpMapInput)(nil)).Elem(), AuthMethodGcpMap{})
	pulumi.RegisterOutputType(AuthMethodGcpOutput{})
	pulumi.RegisterOutputType(AuthMethodGcpArrayOutput{})
	pulumi.RegisterOutputType(AuthMethodGcpMapOutput{})
}
