// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akeyless

import (
	"context"
	"reflect"

	"github.com/akeyless-community/pulumi-akeyless/sdk/go/akeyless/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type GatewayLogForwardingGoogleChronicle struct {
	pulumi.CustomResourceState

	// Google chronicle customer id
	CustomerId pulumi.StringPtrOutput `pulumi:"customerId"`
	// Enable Log Forwarding [true/false]
	Enable pulumi.StringPtrOutput `pulumi:"enable"`
	// Base64-encoded service account private key text
	GcpKey pulumi.StringPtrOutput `pulumi:"gcpKey"`
	// Google chronicle log type
	LogType pulumi.StringPtrOutput `pulumi:"logType"`
	// Logs format [text/json]
	OutputFormat pulumi.StringPtrOutput `pulumi:"outputFormat"`
	// Pull interval in seconds
	PullInterval pulumi.StringPtrOutput `pulumi:"pullInterval"`
	// Google chronicle region [eu_multi_region/london/us_multi_region/singapore/tel_aviv]
	Region pulumi.StringPtrOutput `pulumi:"region"`
}

// NewGatewayLogForwardingGoogleChronicle registers a new resource with the given unique name, arguments, and options.
func NewGatewayLogForwardingGoogleChronicle(ctx *pulumi.Context,
	name string, args *GatewayLogForwardingGoogleChronicleArgs, opts ...pulumi.ResourceOption) (*GatewayLogForwardingGoogleChronicle, error) {
	if args == nil {
		args = &GatewayLogForwardingGoogleChronicleArgs{}
	}

	if args.GcpKey != nil {
		args.GcpKey = pulumi.ToSecret(args.GcpKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"gcpKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GatewayLogForwardingGoogleChronicle
	err := ctx.RegisterResource("akeyless:index/gatewayLogForwardingGoogleChronicle:GatewayLogForwardingGoogleChronicle", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGatewayLogForwardingGoogleChronicle gets an existing GatewayLogForwardingGoogleChronicle resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGatewayLogForwardingGoogleChronicle(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GatewayLogForwardingGoogleChronicleState, opts ...pulumi.ResourceOption) (*GatewayLogForwardingGoogleChronicle, error) {
	var resource GatewayLogForwardingGoogleChronicle
	err := ctx.ReadResource("akeyless:index/gatewayLogForwardingGoogleChronicle:GatewayLogForwardingGoogleChronicle", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GatewayLogForwardingGoogleChronicle resources.
type gatewayLogForwardingGoogleChronicleState struct {
	// Google chronicle customer id
	CustomerId *string `pulumi:"customerId"`
	// Enable Log Forwarding [true/false]
	Enable *string `pulumi:"enable"`
	// Base64-encoded service account private key text
	GcpKey *string `pulumi:"gcpKey"`
	// Google chronicle log type
	LogType *string `pulumi:"logType"`
	// Logs format [text/json]
	OutputFormat *string `pulumi:"outputFormat"`
	// Pull interval in seconds
	PullInterval *string `pulumi:"pullInterval"`
	// Google chronicle region [eu_multi_region/london/us_multi_region/singapore/tel_aviv]
	Region *string `pulumi:"region"`
}

type GatewayLogForwardingGoogleChronicleState struct {
	// Google chronicle customer id
	CustomerId pulumi.StringPtrInput
	// Enable Log Forwarding [true/false]
	Enable pulumi.StringPtrInput
	// Base64-encoded service account private key text
	GcpKey pulumi.StringPtrInput
	// Google chronicle log type
	LogType pulumi.StringPtrInput
	// Logs format [text/json]
	OutputFormat pulumi.StringPtrInput
	// Pull interval in seconds
	PullInterval pulumi.StringPtrInput
	// Google chronicle region [eu_multi_region/london/us_multi_region/singapore/tel_aviv]
	Region pulumi.StringPtrInput
}

func (GatewayLogForwardingGoogleChronicleState) ElementType() reflect.Type {
	return reflect.TypeOf((*gatewayLogForwardingGoogleChronicleState)(nil)).Elem()
}

type gatewayLogForwardingGoogleChronicleArgs struct {
	// Google chronicle customer id
	CustomerId *string `pulumi:"customerId"`
	// Enable Log Forwarding [true/false]
	Enable *string `pulumi:"enable"`
	// Base64-encoded service account private key text
	GcpKey *string `pulumi:"gcpKey"`
	// Google chronicle log type
	LogType *string `pulumi:"logType"`
	// Logs format [text/json]
	OutputFormat *string `pulumi:"outputFormat"`
	// Pull interval in seconds
	PullInterval *string `pulumi:"pullInterval"`
	// Google chronicle region [eu_multi_region/london/us_multi_region/singapore/tel_aviv]
	Region *string `pulumi:"region"`
}

// The set of arguments for constructing a GatewayLogForwardingGoogleChronicle resource.
type GatewayLogForwardingGoogleChronicleArgs struct {
	// Google chronicle customer id
	CustomerId pulumi.StringPtrInput
	// Enable Log Forwarding [true/false]
	Enable pulumi.StringPtrInput
	// Base64-encoded service account private key text
	GcpKey pulumi.StringPtrInput
	// Google chronicle log type
	LogType pulumi.StringPtrInput
	// Logs format [text/json]
	OutputFormat pulumi.StringPtrInput
	// Pull interval in seconds
	PullInterval pulumi.StringPtrInput
	// Google chronicle region [eu_multi_region/london/us_multi_region/singapore/tel_aviv]
	Region pulumi.StringPtrInput
}

func (GatewayLogForwardingGoogleChronicleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gatewayLogForwardingGoogleChronicleArgs)(nil)).Elem()
}

type GatewayLogForwardingGoogleChronicleInput interface {
	pulumi.Input

	ToGatewayLogForwardingGoogleChronicleOutput() GatewayLogForwardingGoogleChronicleOutput
	ToGatewayLogForwardingGoogleChronicleOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleOutput
}

func (*GatewayLogForwardingGoogleChronicle) ElementType() reflect.Type {
	return reflect.TypeOf((**GatewayLogForwardingGoogleChronicle)(nil)).Elem()
}

func (i *GatewayLogForwardingGoogleChronicle) ToGatewayLogForwardingGoogleChronicleOutput() GatewayLogForwardingGoogleChronicleOutput {
	return i.ToGatewayLogForwardingGoogleChronicleOutputWithContext(context.Background())
}

func (i *GatewayLogForwardingGoogleChronicle) ToGatewayLogForwardingGoogleChronicleOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GatewayLogForwardingGoogleChronicleOutput)
}

// GatewayLogForwardingGoogleChronicleArrayInput is an input type that accepts GatewayLogForwardingGoogleChronicleArray and GatewayLogForwardingGoogleChronicleArrayOutput values.
// You can construct a concrete instance of `GatewayLogForwardingGoogleChronicleArrayInput` via:
//
//	GatewayLogForwardingGoogleChronicleArray{ GatewayLogForwardingGoogleChronicleArgs{...} }
type GatewayLogForwardingGoogleChronicleArrayInput interface {
	pulumi.Input

	ToGatewayLogForwardingGoogleChronicleArrayOutput() GatewayLogForwardingGoogleChronicleArrayOutput
	ToGatewayLogForwardingGoogleChronicleArrayOutputWithContext(context.Context) GatewayLogForwardingGoogleChronicleArrayOutput
}

type GatewayLogForwardingGoogleChronicleArray []GatewayLogForwardingGoogleChronicleInput

func (GatewayLogForwardingGoogleChronicleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GatewayLogForwardingGoogleChronicle)(nil)).Elem()
}

func (i GatewayLogForwardingGoogleChronicleArray) ToGatewayLogForwardingGoogleChronicleArrayOutput() GatewayLogForwardingGoogleChronicleArrayOutput {
	return i.ToGatewayLogForwardingGoogleChronicleArrayOutputWithContext(context.Background())
}

func (i GatewayLogForwardingGoogleChronicleArray) ToGatewayLogForwardingGoogleChronicleArrayOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GatewayLogForwardingGoogleChronicleArrayOutput)
}

// GatewayLogForwardingGoogleChronicleMapInput is an input type that accepts GatewayLogForwardingGoogleChronicleMap and GatewayLogForwardingGoogleChronicleMapOutput values.
// You can construct a concrete instance of `GatewayLogForwardingGoogleChronicleMapInput` via:
//
//	GatewayLogForwardingGoogleChronicleMap{ "key": GatewayLogForwardingGoogleChronicleArgs{...} }
type GatewayLogForwardingGoogleChronicleMapInput interface {
	pulumi.Input

	ToGatewayLogForwardingGoogleChronicleMapOutput() GatewayLogForwardingGoogleChronicleMapOutput
	ToGatewayLogForwardingGoogleChronicleMapOutputWithContext(context.Context) GatewayLogForwardingGoogleChronicleMapOutput
}

type GatewayLogForwardingGoogleChronicleMap map[string]GatewayLogForwardingGoogleChronicleInput

func (GatewayLogForwardingGoogleChronicleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GatewayLogForwardingGoogleChronicle)(nil)).Elem()
}

func (i GatewayLogForwardingGoogleChronicleMap) ToGatewayLogForwardingGoogleChronicleMapOutput() GatewayLogForwardingGoogleChronicleMapOutput {
	return i.ToGatewayLogForwardingGoogleChronicleMapOutputWithContext(context.Background())
}

func (i GatewayLogForwardingGoogleChronicleMap) ToGatewayLogForwardingGoogleChronicleMapOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GatewayLogForwardingGoogleChronicleMapOutput)
}

type GatewayLogForwardingGoogleChronicleOutput struct{ *pulumi.OutputState }

func (GatewayLogForwardingGoogleChronicleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GatewayLogForwardingGoogleChronicle)(nil)).Elem()
}

func (o GatewayLogForwardingGoogleChronicleOutput) ToGatewayLogForwardingGoogleChronicleOutput() GatewayLogForwardingGoogleChronicleOutput {
	return o
}

func (o GatewayLogForwardingGoogleChronicleOutput) ToGatewayLogForwardingGoogleChronicleOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleOutput {
	return o
}

// Google chronicle customer id
func (o GatewayLogForwardingGoogleChronicleOutput) CustomerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.CustomerId }).(pulumi.StringPtrOutput)
}

// Enable Log Forwarding [true/false]
func (o GatewayLogForwardingGoogleChronicleOutput) Enable() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.Enable }).(pulumi.StringPtrOutput)
}

// Base64-encoded service account private key text
func (o GatewayLogForwardingGoogleChronicleOutput) GcpKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.GcpKey }).(pulumi.StringPtrOutput)
}

// Google chronicle log type
func (o GatewayLogForwardingGoogleChronicleOutput) LogType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.LogType }).(pulumi.StringPtrOutput)
}

// Logs format [text/json]
func (o GatewayLogForwardingGoogleChronicleOutput) OutputFormat() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.OutputFormat }).(pulumi.StringPtrOutput)
}

// Pull interval in seconds
func (o GatewayLogForwardingGoogleChronicleOutput) PullInterval() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.PullInterval }).(pulumi.StringPtrOutput)
}

// Google chronicle region [eu_multi_region/london/us_multi_region/singapore/tel_aviv]
func (o GatewayLogForwardingGoogleChronicleOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayLogForwardingGoogleChronicle) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

type GatewayLogForwardingGoogleChronicleArrayOutput struct{ *pulumi.OutputState }

func (GatewayLogForwardingGoogleChronicleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GatewayLogForwardingGoogleChronicle)(nil)).Elem()
}

func (o GatewayLogForwardingGoogleChronicleArrayOutput) ToGatewayLogForwardingGoogleChronicleArrayOutput() GatewayLogForwardingGoogleChronicleArrayOutput {
	return o
}

func (o GatewayLogForwardingGoogleChronicleArrayOutput) ToGatewayLogForwardingGoogleChronicleArrayOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleArrayOutput {
	return o
}

func (o GatewayLogForwardingGoogleChronicleArrayOutput) Index(i pulumi.IntInput) GatewayLogForwardingGoogleChronicleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GatewayLogForwardingGoogleChronicle {
		return vs[0].([]*GatewayLogForwardingGoogleChronicle)[vs[1].(int)]
	}).(GatewayLogForwardingGoogleChronicleOutput)
}

type GatewayLogForwardingGoogleChronicleMapOutput struct{ *pulumi.OutputState }

func (GatewayLogForwardingGoogleChronicleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GatewayLogForwardingGoogleChronicle)(nil)).Elem()
}

func (o GatewayLogForwardingGoogleChronicleMapOutput) ToGatewayLogForwardingGoogleChronicleMapOutput() GatewayLogForwardingGoogleChronicleMapOutput {
	return o
}

func (o GatewayLogForwardingGoogleChronicleMapOutput) ToGatewayLogForwardingGoogleChronicleMapOutputWithContext(ctx context.Context) GatewayLogForwardingGoogleChronicleMapOutput {
	return o
}

func (o GatewayLogForwardingGoogleChronicleMapOutput) MapIndex(k pulumi.StringInput) GatewayLogForwardingGoogleChronicleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GatewayLogForwardingGoogleChronicle {
		return vs[0].(map[string]*GatewayLogForwardingGoogleChronicle)[vs[1].(string)]
	}).(GatewayLogForwardingGoogleChronicleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GatewayLogForwardingGoogleChronicleInput)(nil)).Elem(), &GatewayLogForwardingGoogleChronicle{})
	pulumi.RegisterInputType(reflect.TypeOf((*GatewayLogForwardingGoogleChronicleArrayInput)(nil)).Elem(), GatewayLogForwardingGoogleChronicleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GatewayLogForwardingGoogleChronicleMapInput)(nil)).Elem(), GatewayLogForwardingGoogleChronicleMap{})
	pulumi.RegisterOutputType(GatewayLogForwardingGoogleChronicleOutput{})
	pulumi.RegisterOutputType(GatewayLogForwardingGoogleChronicleArrayOutput{})
	pulumi.RegisterOutputType(GatewayLogForwardingGoogleChronicleMapOutput{})
}
