// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akeyless

import (
	"context"
	"reflect"

	"errors"
	"github.com/akeyless-community/pulumi-akeyless/sdk/go/akeyless/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type K8sAuthConfig struct {
	pulumi.CustomResourceState

	// The access ID of the Kubernetes auth method
	AccessId pulumi.StringOutput `pulumi:"accessId"`
	// Cluster access type. options: [native_k8s, rancher]
	ClusterApiType pulumi.StringPtrOutput `pulumi:"clusterApiType"`
	// Disable issuer validation [true/false]
	DisableIssuerValidation pulumi.StringPtrOutput `pulumi:"disableIssuerValidation"`
	// Native K8S auth type, [token/certificate]. (relevant for nativeK8s only)
	K8sAuthType pulumi.StringPtrOutput `pulumi:"k8sAuthType"`
	// The CA Certificate (base64 encoded) to use to call into the kubernetes API server
	K8sCaCert pulumi.StringPtrOutput `pulumi:"k8sCaCert"`
	// Content of the k8 client certificate (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientCertificate pulumi.StringPtrOutput `pulumi:"k8sClientCertificate"`
	// Content of the k8 client private key (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientKey pulumi.StringPtrOutput `pulumi:"k8sClientKey"`
	// The URL of the kubernetes API server
	K8sHost pulumi.StringPtrOutput `pulumi:"k8sHost"`
	// The Kubernetes JWT issuer name. If not set, this <kubernetes/serviceaccount> will be used by default.
	K8sIssuer pulumi.StringPtrOutput `pulumi:"k8sIssuer"`
	// K8S Auth config name
	Name pulumi.StringOutput `pulumi:"name"`
	// The api key used to access the TokenReview API to validate other JWTs (relevant for rancher only)
	RancherApiKey pulumi.StringPtrOutput `pulumi:"rancherApiKey"`
	// The cluster id as define in rancher (relevant for rancher only)
	RancherClusterId pulumi.StringPtrOutput `pulumi:"rancherClusterId"`
	// The private key (in base64 encoded of the PEM format) associated with the public key defined in the Kubernetes auth
	SigningKey pulumi.StringPtrOutput `pulumi:"signingKey"`
	// Time in seconds of expiration of the Akeyless Kube Auth Method token
	TokenExp pulumi.IntPtrOutput `pulumi:"tokenExp"`
	// A Kubernetes service account JWT used to access the TokenReview API to validate other JWTs. If not set, the JWT submitted in the authentication process will be used to access the Kubernetes TokenReview API.
	TokenReviewerJwt pulumi.StringPtrOutput `pulumi:"tokenReviewerJwt"`
	// Use the GW's service account
	UseLocalCaJwt pulumi.BoolPtrOutput `pulumi:"useLocalCaJwt"`
}

// NewK8sAuthConfig registers a new resource with the given unique name, arguments, and options.
func NewK8sAuthConfig(ctx *pulumi.Context,
	name string, args *K8sAuthConfigArgs, opts ...pulumi.ResourceOption) (*K8sAuthConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccessId == nil {
		return nil, errors.New("invalid value for required argument 'AccessId'")
	}
	if args.K8sClientKey != nil {
		args.K8sClientKey = pulumi.ToSecret(args.K8sClientKey).(pulumi.StringPtrInput)
	}
	if args.SigningKey != nil {
		args.SigningKey = pulumi.ToSecret(args.SigningKey).(pulumi.StringPtrInput)
	}
	if args.TokenReviewerJwt != nil {
		args.TokenReviewerJwt = pulumi.ToSecret(args.TokenReviewerJwt).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"k8sClientKey",
		"signingKey",
		"tokenReviewerJwt",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource K8sAuthConfig
	err := ctx.RegisterResource("akeyless:index/k8sAuthConfig:K8sAuthConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetK8sAuthConfig gets an existing K8sAuthConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetK8sAuthConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *K8sAuthConfigState, opts ...pulumi.ResourceOption) (*K8sAuthConfig, error) {
	var resource K8sAuthConfig
	err := ctx.ReadResource("akeyless:index/k8sAuthConfig:K8sAuthConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering K8sAuthConfig resources.
type k8sAuthConfigState struct {
	// The access ID of the Kubernetes auth method
	AccessId *string `pulumi:"accessId"`
	// Cluster access type. options: [native_k8s, rancher]
	ClusterApiType *string `pulumi:"clusterApiType"`
	// Disable issuer validation [true/false]
	DisableIssuerValidation *string `pulumi:"disableIssuerValidation"`
	// Native K8S auth type, [token/certificate]. (relevant for nativeK8s only)
	K8sAuthType *string `pulumi:"k8sAuthType"`
	// The CA Certificate (base64 encoded) to use to call into the kubernetes API server
	K8sCaCert *string `pulumi:"k8sCaCert"`
	// Content of the k8 client certificate (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientCertificate *string `pulumi:"k8sClientCertificate"`
	// Content of the k8 client private key (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientKey *string `pulumi:"k8sClientKey"`
	// The URL of the kubernetes API server
	K8sHost *string `pulumi:"k8sHost"`
	// The Kubernetes JWT issuer name. If not set, this <kubernetes/serviceaccount> will be used by default.
	K8sIssuer *string `pulumi:"k8sIssuer"`
	// K8S Auth config name
	Name *string `pulumi:"name"`
	// The api key used to access the TokenReview API to validate other JWTs (relevant for rancher only)
	RancherApiKey *string `pulumi:"rancherApiKey"`
	// The cluster id as define in rancher (relevant for rancher only)
	RancherClusterId *string `pulumi:"rancherClusterId"`
	// The private key (in base64 encoded of the PEM format) associated with the public key defined in the Kubernetes auth
	SigningKey *string `pulumi:"signingKey"`
	// Time in seconds of expiration of the Akeyless Kube Auth Method token
	TokenExp *int `pulumi:"tokenExp"`
	// A Kubernetes service account JWT used to access the TokenReview API to validate other JWTs. If not set, the JWT submitted in the authentication process will be used to access the Kubernetes TokenReview API.
	TokenReviewerJwt *string `pulumi:"tokenReviewerJwt"`
	// Use the GW's service account
	UseLocalCaJwt *bool `pulumi:"useLocalCaJwt"`
}

type K8sAuthConfigState struct {
	// The access ID of the Kubernetes auth method
	AccessId pulumi.StringPtrInput
	// Cluster access type. options: [native_k8s, rancher]
	ClusterApiType pulumi.StringPtrInput
	// Disable issuer validation [true/false]
	DisableIssuerValidation pulumi.StringPtrInput
	// Native K8S auth type, [token/certificate]. (relevant for nativeK8s only)
	K8sAuthType pulumi.StringPtrInput
	// The CA Certificate (base64 encoded) to use to call into the kubernetes API server
	K8sCaCert pulumi.StringPtrInput
	// Content of the k8 client certificate (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientCertificate pulumi.StringPtrInput
	// Content of the k8 client private key (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientKey pulumi.StringPtrInput
	// The URL of the kubernetes API server
	K8sHost pulumi.StringPtrInput
	// The Kubernetes JWT issuer name. If not set, this <kubernetes/serviceaccount> will be used by default.
	K8sIssuer pulumi.StringPtrInput
	// K8S Auth config name
	Name pulumi.StringPtrInput
	// The api key used to access the TokenReview API to validate other JWTs (relevant for rancher only)
	RancherApiKey pulumi.StringPtrInput
	// The cluster id as define in rancher (relevant for rancher only)
	RancherClusterId pulumi.StringPtrInput
	// The private key (in base64 encoded of the PEM format) associated with the public key defined in the Kubernetes auth
	SigningKey pulumi.StringPtrInput
	// Time in seconds of expiration of the Akeyless Kube Auth Method token
	TokenExp pulumi.IntPtrInput
	// A Kubernetes service account JWT used to access the TokenReview API to validate other JWTs. If not set, the JWT submitted in the authentication process will be used to access the Kubernetes TokenReview API.
	TokenReviewerJwt pulumi.StringPtrInput
	// Use the GW's service account
	UseLocalCaJwt pulumi.BoolPtrInput
}

func (K8sAuthConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*k8sAuthConfigState)(nil)).Elem()
}

type k8sAuthConfigArgs struct {
	// The access ID of the Kubernetes auth method
	AccessId string `pulumi:"accessId"`
	// Cluster access type. options: [native_k8s, rancher]
	ClusterApiType *string `pulumi:"clusterApiType"`
	// Disable issuer validation [true/false]
	DisableIssuerValidation *string `pulumi:"disableIssuerValidation"`
	// Native K8S auth type, [token/certificate]. (relevant for nativeK8s only)
	K8sAuthType *string `pulumi:"k8sAuthType"`
	// The CA Certificate (base64 encoded) to use to call into the kubernetes API server
	K8sCaCert *string `pulumi:"k8sCaCert"`
	// Content of the k8 client certificate (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientCertificate *string `pulumi:"k8sClientCertificate"`
	// Content of the k8 client private key (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientKey *string `pulumi:"k8sClientKey"`
	// The URL of the kubernetes API server
	K8sHost *string `pulumi:"k8sHost"`
	// The Kubernetes JWT issuer name. If not set, this <kubernetes/serviceaccount> will be used by default.
	K8sIssuer *string `pulumi:"k8sIssuer"`
	// K8S Auth config name
	Name *string `pulumi:"name"`
	// The api key used to access the TokenReview API to validate other JWTs (relevant for rancher only)
	RancherApiKey *string `pulumi:"rancherApiKey"`
	// The cluster id as define in rancher (relevant for rancher only)
	RancherClusterId *string `pulumi:"rancherClusterId"`
	// The private key (in base64 encoded of the PEM format) associated with the public key defined in the Kubernetes auth
	SigningKey *string `pulumi:"signingKey"`
	// Time in seconds of expiration of the Akeyless Kube Auth Method token
	TokenExp *int `pulumi:"tokenExp"`
	// A Kubernetes service account JWT used to access the TokenReview API to validate other JWTs. If not set, the JWT submitted in the authentication process will be used to access the Kubernetes TokenReview API.
	TokenReviewerJwt *string `pulumi:"tokenReviewerJwt"`
	// Use the GW's service account
	UseLocalCaJwt *bool `pulumi:"useLocalCaJwt"`
}

// The set of arguments for constructing a K8sAuthConfig resource.
type K8sAuthConfigArgs struct {
	// The access ID of the Kubernetes auth method
	AccessId pulumi.StringInput
	// Cluster access type. options: [native_k8s, rancher]
	ClusterApiType pulumi.StringPtrInput
	// Disable issuer validation [true/false]
	DisableIssuerValidation pulumi.StringPtrInput
	// Native K8S auth type, [token/certificate]. (relevant for nativeK8s only)
	K8sAuthType pulumi.StringPtrInput
	// The CA Certificate (base64 encoded) to use to call into the kubernetes API server
	K8sCaCert pulumi.StringPtrInput
	// Content of the k8 client certificate (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientCertificate pulumi.StringPtrInput
	// Content of the k8 client private key (PEM format) in a Base64 format (relevant for nativeK8s only)
	K8sClientKey pulumi.StringPtrInput
	// The URL of the kubernetes API server
	K8sHost pulumi.StringPtrInput
	// The Kubernetes JWT issuer name. If not set, this <kubernetes/serviceaccount> will be used by default.
	K8sIssuer pulumi.StringPtrInput
	// K8S Auth config name
	Name pulumi.StringPtrInput
	// The api key used to access the TokenReview API to validate other JWTs (relevant for rancher only)
	RancherApiKey pulumi.StringPtrInput
	// The cluster id as define in rancher (relevant for rancher only)
	RancherClusterId pulumi.StringPtrInput
	// The private key (in base64 encoded of the PEM format) associated with the public key defined in the Kubernetes auth
	SigningKey pulumi.StringPtrInput
	// Time in seconds of expiration of the Akeyless Kube Auth Method token
	TokenExp pulumi.IntPtrInput
	// A Kubernetes service account JWT used to access the TokenReview API to validate other JWTs. If not set, the JWT submitted in the authentication process will be used to access the Kubernetes TokenReview API.
	TokenReviewerJwt pulumi.StringPtrInput
	// Use the GW's service account
	UseLocalCaJwt pulumi.BoolPtrInput
}

func (K8sAuthConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*k8sAuthConfigArgs)(nil)).Elem()
}

type K8sAuthConfigInput interface {
	pulumi.Input

	ToK8sAuthConfigOutput() K8sAuthConfigOutput
	ToK8sAuthConfigOutputWithContext(ctx context.Context) K8sAuthConfigOutput
}

func (*K8sAuthConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**K8sAuthConfig)(nil)).Elem()
}

func (i *K8sAuthConfig) ToK8sAuthConfigOutput() K8sAuthConfigOutput {
	return i.ToK8sAuthConfigOutputWithContext(context.Background())
}

func (i *K8sAuthConfig) ToK8sAuthConfigOutputWithContext(ctx context.Context) K8sAuthConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(K8sAuthConfigOutput)
}

// K8sAuthConfigArrayInput is an input type that accepts K8sAuthConfigArray and K8sAuthConfigArrayOutput values.
// You can construct a concrete instance of `K8sAuthConfigArrayInput` via:
//
//	K8sAuthConfigArray{ K8sAuthConfigArgs{...} }
type K8sAuthConfigArrayInput interface {
	pulumi.Input

	ToK8sAuthConfigArrayOutput() K8sAuthConfigArrayOutput
	ToK8sAuthConfigArrayOutputWithContext(context.Context) K8sAuthConfigArrayOutput
}

type K8sAuthConfigArray []K8sAuthConfigInput

func (K8sAuthConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*K8sAuthConfig)(nil)).Elem()
}

func (i K8sAuthConfigArray) ToK8sAuthConfigArrayOutput() K8sAuthConfigArrayOutput {
	return i.ToK8sAuthConfigArrayOutputWithContext(context.Background())
}

func (i K8sAuthConfigArray) ToK8sAuthConfigArrayOutputWithContext(ctx context.Context) K8sAuthConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(K8sAuthConfigArrayOutput)
}

// K8sAuthConfigMapInput is an input type that accepts K8sAuthConfigMap and K8sAuthConfigMapOutput values.
// You can construct a concrete instance of `K8sAuthConfigMapInput` via:
//
//	K8sAuthConfigMap{ "key": K8sAuthConfigArgs{...} }
type K8sAuthConfigMapInput interface {
	pulumi.Input

	ToK8sAuthConfigMapOutput() K8sAuthConfigMapOutput
	ToK8sAuthConfigMapOutputWithContext(context.Context) K8sAuthConfigMapOutput
}

type K8sAuthConfigMap map[string]K8sAuthConfigInput

func (K8sAuthConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*K8sAuthConfig)(nil)).Elem()
}

func (i K8sAuthConfigMap) ToK8sAuthConfigMapOutput() K8sAuthConfigMapOutput {
	return i.ToK8sAuthConfigMapOutputWithContext(context.Background())
}

func (i K8sAuthConfigMap) ToK8sAuthConfigMapOutputWithContext(ctx context.Context) K8sAuthConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(K8sAuthConfigMapOutput)
}

type K8sAuthConfigOutput struct{ *pulumi.OutputState }

func (K8sAuthConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**K8sAuthConfig)(nil)).Elem()
}

func (o K8sAuthConfigOutput) ToK8sAuthConfigOutput() K8sAuthConfigOutput {
	return o
}

func (o K8sAuthConfigOutput) ToK8sAuthConfigOutputWithContext(ctx context.Context) K8sAuthConfigOutput {
	return o
}

// The access ID of the Kubernetes auth method
func (o K8sAuthConfigOutput) AccessId() pulumi.StringOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringOutput { return v.AccessId }).(pulumi.StringOutput)
}

// Cluster access type. options: [native_k8s, rancher]
func (o K8sAuthConfigOutput) ClusterApiType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.ClusterApiType }).(pulumi.StringPtrOutput)
}

// Disable issuer validation [true/false]
func (o K8sAuthConfigOutput) DisableIssuerValidation() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.DisableIssuerValidation }).(pulumi.StringPtrOutput)
}

// Native K8S auth type, [token/certificate]. (relevant for nativeK8s only)
func (o K8sAuthConfigOutput) K8sAuthType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.K8sAuthType }).(pulumi.StringPtrOutput)
}

// The CA Certificate (base64 encoded) to use to call into the kubernetes API server
func (o K8sAuthConfigOutput) K8sCaCert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.K8sCaCert }).(pulumi.StringPtrOutput)
}

// Content of the k8 client certificate (PEM format) in a Base64 format (relevant for nativeK8s only)
func (o K8sAuthConfigOutput) K8sClientCertificate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.K8sClientCertificate }).(pulumi.StringPtrOutput)
}

// Content of the k8 client private key (PEM format) in a Base64 format (relevant for nativeK8s only)
func (o K8sAuthConfigOutput) K8sClientKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.K8sClientKey }).(pulumi.StringPtrOutput)
}

// The URL of the kubernetes API server
func (o K8sAuthConfigOutput) K8sHost() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.K8sHost }).(pulumi.StringPtrOutput)
}

// The Kubernetes JWT issuer name. If not set, this <kubernetes/serviceaccount> will be used by default.
func (o K8sAuthConfigOutput) K8sIssuer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.K8sIssuer }).(pulumi.StringPtrOutput)
}

// K8S Auth config name
func (o K8sAuthConfigOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The api key used to access the TokenReview API to validate other JWTs (relevant for rancher only)
func (o K8sAuthConfigOutput) RancherApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.RancherApiKey }).(pulumi.StringPtrOutput)
}

// The cluster id as define in rancher (relevant for rancher only)
func (o K8sAuthConfigOutput) RancherClusterId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.RancherClusterId }).(pulumi.StringPtrOutput)
}

// The private key (in base64 encoded of the PEM format) associated with the public key defined in the Kubernetes auth
func (o K8sAuthConfigOutput) SigningKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.SigningKey }).(pulumi.StringPtrOutput)
}

// Time in seconds of expiration of the Akeyless Kube Auth Method token
func (o K8sAuthConfigOutput) TokenExp() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.IntPtrOutput { return v.TokenExp }).(pulumi.IntPtrOutput)
}

// A Kubernetes service account JWT used to access the TokenReview API to validate other JWTs. If not set, the JWT submitted in the authentication process will be used to access the Kubernetes TokenReview API.
func (o K8sAuthConfigOutput) TokenReviewerJwt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.StringPtrOutput { return v.TokenReviewerJwt }).(pulumi.StringPtrOutput)
}

// Use the GW's service account
func (o K8sAuthConfigOutput) UseLocalCaJwt() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *K8sAuthConfig) pulumi.BoolPtrOutput { return v.UseLocalCaJwt }).(pulumi.BoolPtrOutput)
}

type K8sAuthConfigArrayOutput struct{ *pulumi.OutputState }

func (K8sAuthConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*K8sAuthConfig)(nil)).Elem()
}

func (o K8sAuthConfigArrayOutput) ToK8sAuthConfigArrayOutput() K8sAuthConfigArrayOutput {
	return o
}

func (o K8sAuthConfigArrayOutput) ToK8sAuthConfigArrayOutputWithContext(ctx context.Context) K8sAuthConfigArrayOutput {
	return o
}

func (o K8sAuthConfigArrayOutput) Index(i pulumi.IntInput) K8sAuthConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *K8sAuthConfig {
		return vs[0].([]*K8sAuthConfig)[vs[1].(int)]
	}).(K8sAuthConfigOutput)
}

type K8sAuthConfigMapOutput struct{ *pulumi.OutputState }

func (K8sAuthConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*K8sAuthConfig)(nil)).Elem()
}

func (o K8sAuthConfigMapOutput) ToK8sAuthConfigMapOutput() K8sAuthConfigMapOutput {
	return o
}

func (o K8sAuthConfigMapOutput) ToK8sAuthConfigMapOutputWithContext(ctx context.Context) K8sAuthConfigMapOutput {
	return o
}

func (o K8sAuthConfigMapOutput) MapIndex(k pulumi.StringInput) K8sAuthConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *K8sAuthConfig {
		return vs[0].(map[string]*K8sAuthConfig)[vs[1].(string)]
	}).(K8sAuthConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*K8sAuthConfigInput)(nil)).Elem(), &K8sAuthConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*K8sAuthConfigArrayInput)(nil)).Elem(), K8sAuthConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*K8sAuthConfigMapInput)(nil)).Elem(), K8sAuthConfigMap{})
	pulumi.RegisterOutputType(K8sAuthConfigOutput{})
	pulumi.RegisterOutputType(K8sAuthConfigArrayOutput{})
	pulumi.RegisterOutputType(K8sAuthConfigMapOutput{})
}
