// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akeyless

import (
	"context"
	"reflect"

	"errors"
	"github.com/akeyless-community/pulumi-akeyless/sdk/go/akeyless/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type RotatedSecretCassandra struct {
	pulumi.CustomResourceState

	// The credentials to connect with [use-self-creds/use-target-creds]
	AuthenticationCredentials pulumi.StringPtrOutput `pulumi:"authenticationCredentials"`
	// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
	AutoRotate pulumi.StringPtrOutput `pulumi:"autoRotate"`
	// Description of the object
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
	Key pulumi.StringOutput `pulumi:"key"`
	// Secret name
	Name pulumi.StringOutput `pulumi:"name"`
	// The length of the password to be generated
	PasswordLength pulumi.StringPtrOutput `pulumi:"passwordLength"`
	// rotated-username password (relevant only for rotator-type=password)
	RotatedPassword pulumi.StringOutput `pulumi:"rotatedPassword"`
	// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
	RotatedUsername pulumi.StringOutput `pulumi:"rotatedUsername"`
	// The Hour of the rotation in UTC
	RotationHour pulumi.IntPtrOutput `pulumi:"rotationHour"`
	// The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
	RotationInterval pulumi.StringPtrOutput `pulumi:"rotationInterval"`
	// The rotator type [target/password]
	RotatorType pulumi.StringOutput `pulumi:"rotatorType"`
	// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// The target name to associate
	TargetName pulumi.StringOutput `pulumi:"targetName"`
}

// NewRotatedSecretCassandra registers a new resource with the given unique name, arguments, and options.
func NewRotatedSecretCassandra(ctx *pulumi.Context,
	name string, args *RotatedSecretCassandraArgs, opts ...pulumi.ResourceOption) (*RotatedSecretCassandra, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.RotatorType == nil {
		return nil, errors.New("invalid value for required argument 'RotatorType'")
	}
	if args.TargetName == nil {
		return nil, errors.New("invalid value for required argument 'TargetName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RotatedSecretCassandra
	err := ctx.RegisterResource("akeyless:index/rotatedSecretCassandra:RotatedSecretCassandra", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRotatedSecretCassandra gets an existing RotatedSecretCassandra resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRotatedSecretCassandra(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RotatedSecretCassandraState, opts ...pulumi.ResourceOption) (*RotatedSecretCassandra, error) {
	var resource RotatedSecretCassandra
	err := ctx.ReadResource("akeyless:index/rotatedSecretCassandra:RotatedSecretCassandra", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RotatedSecretCassandra resources.
type rotatedSecretCassandraState struct {
	// The credentials to connect with [use-self-creds/use-target-creds]
	AuthenticationCredentials *string `pulumi:"authenticationCredentials"`
	// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
	AutoRotate *string `pulumi:"autoRotate"`
	// Description of the object
	Description *string `pulumi:"description"`
	// The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
	Key *string `pulumi:"key"`
	// Secret name
	Name *string `pulumi:"name"`
	// The length of the password to be generated
	PasswordLength *string `pulumi:"passwordLength"`
	// rotated-username password (relevant only for rotator-type=password)
	RotatedPassword *string `pulumi:"rotatedPassword"`
	// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
	RotatedUsername *string `pulumi:"rotatedUsername"`
	// The Hour of the rotation in UTC
	RotationHour *int `pulumi:"rotationHour"`
	// The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
	RotationInterval *string `pulumi:"rotationInterval"`
	// The rotator type [target/password]
	RotatorType *string `pulumi:"rotatorType"`
	// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
	Tags []string `pulumi:"tags"`
	// The target name to associate
	TargetName *string `pulumi:"targetName"`
}

type RotatedSecretCassandraState struct {
	// The credentials to connect with [use-self-creds/use-target-creds]
	AuthenticationCredentials pulumi.StringPtrInput
	// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
	AutoRotate pulumi.StringPtrInput
	// Description of the object
	Description pulumi.StringPtrInput
	// The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
	Key pulumi.StringPtrInput
	// Secret name
	Name pulumi.StringPtrInput
	// The length of the password to be generated
	PasswordLength pulumi.StringPtrInput
	// rotated-username password (relevant only for rotator-type=password)
	RotatedPassword pulumi.StringPtrInput
	// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
	RotatedUsername pulumi.StringPtrInput
	// The Hour of the rotation in UTC
	RotationHour pulumi.IntPtrInput
	// The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
	RotationInterval pulumi.StringPtrInput
	// The rotator type [target/password]
	RotatorType pulumi.StringPtrInput
	// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
	Tags pulumi.StringArrayInput
	// The target name to associate
	TargetName pulumi.StringPtrInput
}

func (RotatedSecretCassandraState) ElementType() reflect.Type {
	return reflect.TypeOf((*rotatedSecretCassandraState)(nil)).Elem()
}

type rotatedSecretCassandraArgs struct {
	// The credentials to connect with [use-self-creds/use-target-creds]
	AuthenticationCredentials *string `pulumi:"authenticationCredentials"`
	// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
	AutoRotate *string `pulumi:"autoRotate"`
	// Description of the object
	Description *string `pulumi:"description"`
	// The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
	Key *string `pulumi:"key"`
	// Secret name
	Name *string `pulumi:"name"`
	// The length of the password to be generated
	PasswordLength *string `pulumi:"passwordLength"`
	// rotated-username password (relevant only for rotator-type=password)
	RotatedPassword *string `pulumi:"rotatedPassword"`
	// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
	RotatedUsername *string `pulumi:"rotatedUsername"`
	// The Hour of the rotation in UTC
	RotationHour *int `pulumi:"rotationHour"`
	// The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
	RotationInterval *string `pulumi:"rotationInterval"`
	// The rotator type [target/password]
	RotatorType string `pulumi:"rotatorType"`
	// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
	Tags []string `pulumi:"tags"`
	// The target name to associate
	TargetName string `pulumi:"targetName"`
}

// The set of arguments for constructing a RotatedSecretCassandra resource.
type RotatedSecretCassandraArgs struct {
	// The credentials to connect with [use-self-creds/use-target-creds]
	AuthenticationCredentials pulumi.StringPtrInput
	// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
	AutoRotate pulumi.StringPtrInput
	// Description of the object
	Description pulumi.StringPtrInput
	// The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
	Key pulumi.StringPtrInput
	// Secret name
	Name pulumi.StringPtrInput
	// The length of the password to be generated
	PasswordLength pulumi.StringPtrInput
	// rotated-username password (relevant only for rotator-type=password)
	RotatedPassword pulumi.StringPtrInput
	// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
	RotatedUsername pulumi.StringPtrInput
	// The Hour of the rotation in UTC
	RotationHour pulumi.IntPtrInput
	// The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
	RotationInterval pulumi.StringPtrInput
	// The rotator type [target/password]
	RotatorType pulumi.StringInput
	// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
	Tags pulumi.StringArrayInput
	// The target name to associate
	TargetName pulumi.StringInput
}

func (RotatedSecretCassandraArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*rotatedSecretCassandraArgs)(nil)).Elem()
}

type RotatedSecretCassandraInput interface {
	pulumi.Input

	ToRotatedSecretCassandraOutput() RotatedSecretCassandraOutput
	ToRotatedSecretCassandraOutputWithContext(ctx context.Context) RotatedSecretCassandraOutput
}

func (*RotatedSecretCassandra) ElementType() reflect.Type {
	return reflect.TypeOf((**RotatedSecretCassandra)(nil)).Elem()
}

func (i *RotatedSecretCassandra) ToRotatedSecretCassandraOutput() RotatedSecretCassandraOutput {
	return i.ToRotatedSecretCassandraOutputWithContext(context.Background())
}

func (i *RotatedSecretCassandra) ToRotatedSecretCassandraOutputWithContext(ctx context.Context) RotatedSecretCassandraOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RotatedSecretCassandraOutput)
}

// RotatedSecretCassandraArrayInput is an input type that accepts RotatedSecretCassandraArray and RotatedSecretCassandraArrayOutput values.
// You can construct a concrete instance of `RotatedSecretCassandraArrayInput` via:
//
//	RotatedSecretCassandraArray{ RotatedSecretCassandraArgs{...} }
type RotatedSecretCassandraArrayInput interface {
	pulumi.Input

	ToRotatedSecretCassandraArrayOutput() RotatedSecretCassandraArrayOutput
	ToRotatedSecretCassandraArrayOutputWithContext(context.Context) RotatedSecretCassandraArrayOutput
}

type RotatedSecretCassandraArray []RotatedSecretCassandraInput

func (RotatedSecretCassandraArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RotatedSecretCassandra)(nil)).Elem()
}

func (i RotatedSecretCassandraArray) ToRotatedSecretCassandraArrayOutput() RotatedSecretCassandraArrayOutput {
	return i.ToRotatedSecretCassandraArrayOutputWithContext(context.Background())
}

func (i RotatedSecretCassandraArray) ToRotatedSecretCassandraArrayOutputWithContext(ctx context.Context) RotatedSecretCassandraArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RotatedSecretCassandraArrayOutput)
}

// RotatedSecretCassandraMapInput is an input type that accepts RotatedSecretCassandraMap and RotatedSecretCassandraMapOutput values.
// You can construct a concrete instance of `RotatedSecretCassandraMapInput` via:
//
//	RotatedSecretCassandraMap{ "key": RotatedSecretCassandraArgs{...} }
type RotatedSecretCassandraMapInput interface {
	pulumi.Input

	ToRotatedSecretCassandraMapOutput() RotatedSecretCassandraMapOutput
	ToRotatedSecretCassandraMapOutputWithContext(context.Context) RotatedSecretCassandraMapOutput
}

type RotatedSecretCassandraMap map[string]RotatedSecretCassandraInput

func (RotatedSecretCassandraMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RotatedSecretCassandra)(nil)).Elem()
}

func (i RotatedSecretCassandraMap) ToRotatedSecretCassandraMapOutput() RotatedSecretCassandraMapOutput {
	return i.ToRotatedSecretCassandraMapOutputWithContext(context.Background())
}

func (i RotatedSecretCassandraMap) ToRotatedSecretCassandraMapOutputWithContext(ctx context.Context) RotatedSecretCassandraMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RotatedSecretCassandraMapOutput)
}

type RotatedSecretCassandraOutput struct{ *pulumi.OutputState }

func (RotatedSecretCassandraOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RotatedSecretCassandra)(nil)).Elem()
}

func (o RotatedSecretCassandraOutput) ToRotatedSecretCassandraOutput() RotatedSecretCassandraOutput {
	return o
}

func (o RotatedSecretCassandraOutput) ToRotatedSecretCassandraOutputWithContext(ctx context.Context) RotatedSecretCassandraOutput {
	return o
}

// The credentials to connect with [use-self-creds/use-target-creds]
func (o RotatedSecretCassandraOutput) AuthenticationCredentials() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringPtrOutput { return v.AuthenticationCredentials }).(pulumi.StringPtrOutput)
}

// Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
func (o RotatedSecretCassandraOutput) AutoRotate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringPtrOutput { return v.AutoRotate }).(pulumi.StringPtrOutput)
}

// Description of the object
func (o RotatedSecretCassandraOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
func (o RotatedSecretCassandraOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

// Secret name
func (o RotatedSecretCassandraOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The length of the password to be generated
func (o RotatedSecretCassandraOutput) PasswordLength() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringPtrOutput { return v.PasswordLength }).(pulumi.StringPtrOutput)
}

// rotated-username password (relevant only for rotator-type=password)
func (o RotatedSecretCassandraOutput) RotatedPassword() pulumi.StringOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringOutput { return v.RotatedPassword }).(pulumi.StringOutput)
}

// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
func (o RotatedSecretCassandraOutput) RotatedUsername() pulumi.StringOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringOutput { return v.RotatedUsername }).(pulumi.StringOutput)
}

// The Hour of the rotation in UTC
func (o RotatedSecretCassandraOutput) RotationHour() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.IntPtrOutput { return v.RotationHour }).(pulumi.IntPtrOutput)
}

// The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
func (o RotatedSecretCassandraOutput) RotationInterval() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringPtrOutput { return v.RotationInterval }).(pulumi.StringPtrOutput)
}

// The rotator type [target/password]
func (o RotatedSecretCassandraOutput) RotatorType() pulumi.StringOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringOutput { return v.RotatorType }).(pulumi.StringOutput)
}

// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
func (o RotatedSecretCassandraOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// The target name to associate
func (o RotatedSecretCassandraOutput) TargetName() pulumi.StringOutput {
	return o.ApplyT(func(v *RotatedSecretCassandra) pulumi.StringOutput { return v.TargetName }).(pulumi.StringOutput)
}

type RotatedSecretCassandraArrayOutput struct{ *pulumi.OutputState }

func (RotatedSecretCassandraArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RotatedSecretCassandra)(nil)).Elem()
}

func (o RotatedSecretCassandraArrayOutput) ToRotatedSecretCassandraArrayOutput() RotatedSecretCassandraArrayOutput {
	return o
}

func (o RotatedSecretCassandraArrayOutput) ToRotatedSecretCassandraArrayOutputWithContext(ctx context.Context) RotatedSecretCassandraArrayOutput {
	return o
}

func (o RotatedSecretCassandraArrayOutput) Index(i pulumi.IntInput) RotatedSecretCassandraOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RotatedSecretCassandra {
		return vs[0].([]*RotatedSecretCassandra)[vs[1].(int)]
	}).(RotatedSecretCassandraOutput)
}

type RotatedSecretCassandraMapOutput struct{ *pulumi.OutputState }

func (RotatedSecretCassandraMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RotatedSecretCassandra)(nil)).Elem()
}

func (o RotatedSecretCassandraMapOutput) ToRotatedSecretCassandraMapOutput() RotatedSecretCassandraMapOutput {
	return o
}

func (o RotatedSecretCassandraMapOutput) ToRotatedSecretCassandraMapOutputWithContext(ctx context.Context) RotatedSecretCassandraMapOutput {
	return o
}

func (o RotatedSecretCassandraMapOutput) MapIndex(k pulumi.StringInput) RotatedSecretCassandraOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RotatedSecretCassandra {
		return vs[0].(map[string]*RotatedSecretCassandra)[vs[1].(string)]
	}).(RotatedSecretCassandraOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RotatedSecretCassandraInput)(nil)).Elem(), &RotatedSecretCassandra{})
	pulumi.RegisterInputType(reflect.TypeOf((*RotatedSecretCassandraArrayInput)(nil)).Elem(), RotatedSecretCassandraArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RotatedSecretCassandraMapInput)(nil)).Elem(), RotatedSecretCassandraMap{})
	pulumi.RegisterOutputType(RotatedSecretCassandraOutput{})
	pulumi.RegisterOutputType(RotatedSecretCassandraArrayOutput{})
	pulumi.RegisterOutputType(RotatedSecretCassandraMapOutput{})
}
