// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akeyless

import (
	"context"
	"reflect"

	"github.com/akeyless-community/pulumi-akeyless/sdk/go/akeyless/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TargetGithub struct {
	pulumi.CustomResourceState

	// Description of the object
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Github application id
	GithubAppId pulumi.IntPtrOutput `pulumi:"githubAppId"`
	// Github application private key (base64 encoded key)
	GithubAppPrivateKey pulumi.StringPtrOutput `pulumi:"githubAppPrivateKey"`
	// Github base url
	GithubBaseUrl pulumi.StringPtrOutput `pulumi:"githubBaseUrl"`
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
	Key pulumi.StringPtrOutput `pulumi:"key"`
	// Target name
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewTargetGithub registers a new resource with the given unique name, arguments, and options.
func NewTargetGithub(ctx *pulumi.Context,
	name string, args *TargetGithubArgs, opts ...pulumi.ResourceOption) (*TargetGithub, error) {
	if args == nil {
		args = &TargetGithubArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TargetGithub
	err := ctx.RegisterResource("akeyless:index/targetGithub:TargetGithub", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTargetGithub gets an existing TargetGithub resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTargetGithub(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TargetGithubState, opts ...pulumi.ResourceOption) (*TargetGithub, error) {
	var resource TargetGithub
	err := ctx.ReadResource("akeyless:index/targetGithub:TargetGithub", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TargetGithub resources.
type targetGithubState struct {
	// Description of the object
	Description *string `pulumi:"description"`
	// Github application id
	GithubAppId *int `pulumi:"githubAppId"`
	// Github application private key (base64 encoded key)
	GithubAppPrivateKey *string `pulumi:"githubAppPrivateKey"`
	// Github base url
	GithubBaseUrl *string `pulumi:"githubBaseUrl"`
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
	Key *string `pulumi:"key"`
	// Target name
	Name *string `pulumi:"name"`
}

type TargetGithubState struct {
	// Description of the object
	Description pulumi.StringPtrInput
	// Github application id
	GithubAppId pulumi.IntPtrInput
	// Github application private key (base64 encoded key)
	GithubAppPrivateKey pulumi.StringPtrInput
	// Github base url
	GithubBaseUrl pulumi.StringPtrInput
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
	Key pulumi.StringPtrInput
	// Target name
	Name pulumi.StringPtrInput
}

func (TargetGithubState) ElementType() reflect.Type {
	return reflect.TypeOf((*targetGithubState)(nil)).Elem()
}

type targetGithubArgs struct {
	// Description of the object
	Description *string `pulumi:"description"`
	// Github application id
	GithubAppId *int `pulumi:"githubAppId"`
	// Github application private key (base64 encoded key)
	GithubAppPrivateKey *string `pulumi:"githubAppPrivateKey"`
	// Github base url
	GithubBaseUrl *string `pulumi:"githubBaseUrl"`
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
	Key *string `pulumi:"key"`
	// Target name
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a TargetGithub resource.
type TargetGithubArgs struct {
	// Description of the object
	Description pulumi.StringPtrInput
	// Github application id
	GithubAppId pulumi.IntPtrInput
	// Github application private key (base64 encoded key)
	GithubAppPrivateKey pulumi.StringPtrInput
	// Github base url
	GithubBaseUrl pulumi.StringPtrInput
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
	Key pulumi.StringPtrInput
	// Target name
	Name pulumi.StringPtrInput
}

func (TargetGithubArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*targetGithubArgs)(nil)).Elem()
}

type TargetGithubInput interface {
	pulumi.Input

	ToTargetGithubOutput() TargetGithubOutput
	ToTargetGithubOutputWithContext(ctx context.Context) TargetGithubOutput
}

func (*TargetGithub) ElementType() reflect.Type {
	return reflect.TypeOf((**TargetGithub)(nil)).Elem()
}

func (i *TargetGithub) ToTargetGithubOutput() TargetGithubOutput {
	return i.ToTargetGithubOutputWithContext(context.Background())
}

func (i *TargetGithub) ToTargetGithubOutputWithContext(ctx context.Context) TargetGithubOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetGithubOutput)
}

// TargetGithubArrayInput is an input type that accepts TargetGithubArray and TargetGithubArrayOutput values.
// You can construct a concrete instance of `TargetGithubArrayInput` via:
//
//	TargetGithubArray{ TargetGithubArgs{...} }
type TargetGithubArrayInput interface {
	pulumi.Input

	ToTargetGithubArrayOutput() TargetGithubArrayOutput
	ToTargetGithubArrayOutputWithContext(context.Context) TargetGithubArrayOutput
}

type TargetGithubArray []TargetGithubInput

func (TargetGithubArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TargetGithub)(nil)).Elem()
}

func (i TargetGithubArray) ToTargetGithubArrayOutput() TargetGithubArrayOutput {
	return i.ToTargetGithubArrayOutputWithContext(context.Background())
}

func (i TargetGithubArray) ToTargetGithubArrayOutputWithContext(ctx context.Context) TargetGithubArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetGithubArrayOutput)
}

// TargetGithubMapInput is an input type that accepts TargetGithubMap and TargetGithubMapOutput values.
// You can construct a concrete instance of `TargetGithubMapInput` via:
//
//	TargetGithubMap{ "key": TargetGithubArgs{...} }
type TargetGithubMapInput interface {
	pulumi.Input

	ToTargetGithubMapOutput() TargetGithubMapOutput
	ToTargetGithubMapOutputWithContext(context.Context) TargetGithubMapOutput
}

type TargetGithubMap map[string]TargetGithubInput

func (TargetGithubMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TargetGithub)(nil)).Elem()
}

func (i TargetGithubMap) ToTargetGithubMapOutput() TargetGithubMapOutput {
	return i.ToTargetGithubMapOutputWithContext(context.Background())
}

func (i TargetGithubMap) ToTargetGithubMapOutputWithContext(ctx context.Context) TargetGithubMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetGithubMapOutput)
}

type TargetGithubOutput struct{ *pulumi.OutputState }

func (TargetGithubOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TargetGithub)(nil)).Elem()
}

func (o TargetGithubOutput) ToTargetGithubOutput() TargetGithubOutput {
	return o
}

func (o TargetGithubOutput) ToTargetGithubOutputWithContext(ctx context.Context) TargetGithubOutput {
	return o
}

// Description of the object
func (o TargetGithubOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TargetGithub) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Github application id
func (o TargetGithubOutput) GithubAppId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TargetGithub) pulumi.IntPtrOutput { return v.GithubAppId }).(pulumi.IntPtrOutput)
}

// Github application private key (base64 encoded key)
func (o TargetGithubOutput) GithubAppPrivateKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TargetGithub) pulumi.StringPtrOutput { return v.GithubAppPrivateKey }).(pulumi.StringPtrOutput)
}

// Github base url
func (o TargetGithubOutput) GithubBaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TargetGithub) pulumi.StringPtrOutput { return v.GithubBaseUrl }).(pulumi.StringPtrOutput)
}

// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
func (o TargetGithubOutput) Key() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TargetGithub) pulumi.StringPtrOutput { return v.Key }).(pulumi.StringPtrOutput)
}

// Target name
func (o TargetGithubOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TargetGithub) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type TargetGithubArrayOutput struct{ *pulumi.OutputState }

func (TargetGithubArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TargetGithub)(nil)).Elem()
}

func (o TargetGithubArrayOutput) ToTargetGithubArrayOutput() TargetGithubArrayOutput {
	return o
}

func (o TargetGithubArrayOutput) ToTargetGithubArrayOutputWithContext(ctx context.Context) TargetGithubArrayOutput {
	return o
}

func (o TargetGithubArrayOutput) Index(i pulumi.IntInput) TargetGithubOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TargetGithub {
		return vs[0].([]*TargetGithub)[vs[1].(int)]
	}).(TargetGithubOutput)
}

type TargetGithubMapOutput struct{ *pulumi.OutputState }

func (TargetGithubMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TargetGithub)(nil)).Elem()
}

func (o TargetGithubMapOutput) ToTargetGithubMapOutput() TargetGithubMapOutput {
	return o
}

func (o TargetGithubMapOutput) ToTargetGithubMapOutputWithContext(ctx context.Context) TargetGithubMapOutput {
	return o
}

func (o TargetGithubMapOutput) MapIndex(k pulumi.StringInput) TargetGithubOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TargetGithub {
		return vs[0].(map[string]*TargetGithub)[vs[1].(string)]
	}).(TargetGithubOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TargetGithubInput)(nil)).Elem(), &TargetGithub{})
	pulumi.RegisterInputType(reflect.TypeOf((*TargetGithubArrayInput)(nil)).Elem(), TargetGithubArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TargetGithubMapInput)(nil)).Elem(), TargetGithubMap{})
	pulumi.RegisterOutputType(TargetGithubOutput{})
	pulumi.RegisterOutputType(TargetGithubArrayOutput{})
	pulumi.RegisterOutputType(TargetGithubMapOutput{})
}
