// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package akeyless

import (
	"context"
	"reflect"

	"errors"
	"github.com/akeyless-community/pulumi-akeyless/sdk/go/akeyless/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TargetWeb struct {
	pulumi.CustomResourceState

	// Description of the object
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
	Key pulumi.StringPtrOutput `pulumi:"key"`
	// Target name
	Name pulumi.StringOutput `pulumi:"name"`
	// Web target URL
	Url pulumi.StringOutput `pulumi:"url"`
}

// NewTargetWeb registers a new resource with the given unique name, arguments, and options.
func NewTargetWeb(ctx *pulumi.Context,
	name string, args *TargetWebArgs, opts ...pulumi.ResourceOption) (*TargetWeb, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TargetWeb
	err := ctx.RegisterResource("akeyless:index/targetWeb:TargetWeb", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTargetWeb gets an existing TargetWeb resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTargetWeb(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TargetWebState, opts ...pulumi.ResourceOption) (*TargetWeb, error) {
	var resource TargetWeb
	err := ctx.ReadResource("akeyless:index/targetWeb:TargetWeb", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TargetWeb resources.
type targetWebState struct {
	// Description of the object
	Description *string `pulumi:"description"`
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
	Key *string `pulumi:"key"`
	// Target name
	Name *string `pulumi:"name"`
	// Web target URL
	Url *string `pulumi:"url"`
}

type TargetWebState struct {
	// Description of the object
	Description pulumi.StringPtrInput
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
	Key pulumi.StringPtrInput
	// Target name
	Name pulumi.StringPtrInput
	// Web target URL
	Url pulumi.StringPtrInput
}

func (TargetWebState) ElementType() reflect.Type {
	return reflect.TypeOf((*targetWebState)(nil)).Elem()
}

type targetWebArgs struct {
	// Description of the object
	Description *string `pulumi:"description"`
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
	Key *string `pulumi:"key"`
	// Target name
	Name *string `pulumi:"name"`
	// Web target URL
	Url string `pulumi:"url"`
}

// The set of arguments for constructing a TargetWeb resource.
type TargetWebArgs struct {
	// Description of the object
	Description pulumi.StringPtrInput
	// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
	Key pulumi.StringPtrInput
	// Target name
	Name pulumi.StringPtrInput
	// Web target URL
	Url pulumi.StringInput
}

func (TargetWebArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*targetWebArgs)(nil)).Elem()
}

type TargetWebInput interface {
	pulumi.Input

	ToTargetWebOutput() TargetWebOutput
	ToTargetWebOutputWithContext(ctx context.Context) TargetWebOutput
}

func (*TargetWeb) ElementType() reflect.Type {
	return reflect.TypeOf((**TargetWeb)(nil)).Elem()
}

func (i *TargetWeb) ToTargetWebOutput() TargetWebOutput {
	return i.ToTargetWebOutputWithContext(context.Background())
}

func (i *TargetWeb) ToTargetWebOutputWithContext(ctx context.Context) TargetWebOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetWebOutput)
}

// TargetWebArrayInput is an input type that accepts TargetWebArray and TargetWebArrayOutput values.
// You can construct a concrete instance of `TargetWebArrayInput` via:
//
//	TargetWebArray{ TargetWebArgs{...} }
type TargetWebArrayInput interface {
	pulumi.Input

	ToTargetWebArrayOutput() TargetWebArrayOutput
	ToTargetWebArrayOutputWithContext(context.Context) TargetWebArrayOutput
}

type TargetWebArray []TargetWebInput

func (TargetWebArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TargetWeb)(nil)).Elem()
}

func (i TargetWebArray) ToTargetWebArrayOutput() TargetWebArrayOutput {
	return i.ToTargetWebArrayOutputWithContext(context.Background())
}

func (i TargetWebArray) ToTargetWebArrayOutputWithContext(ctx context.Context) TargetWebArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetWebArrayOutput)
}

// TargetWebMapInput is an input type that accepts TargetWebMap and TargetWebMapOutput values.
// You can construct a concrete instance of `TargetWebMapInput` via:
//
//	TargetWebMap{ "key": TargetWebArgs{...} }
type TargetWebMapInput interface {
	pulumi.Input

	ToTargetWebMapOutput() TargetWebMapOutput
	ToTargetWebMapOutputWithContext(context.Context) TargetWebMapOutput
}

type TargetWebMap map[string]TargetWebInput

func (TargetWebMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TargetWeb)(nil)).Elem()
}

func (i TargetWebMap) ToTargetWebMapOutput() TargetWebMapOutput {
	return i.ToTargetWebMapOutputWithContext(context.Background())
}

func (i TargetWebMap) ToTargetWebMapOutputWithContext(ctx context.Context) TargetWebMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetWebMapOutput)
}

type TargetWebOutput struct{ *pulumi.OutputState }

func (TargetWebOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TargetWeb)(nil)).Elem()
}

func (o TargetWebOutput) ToTargetWebOutput() TargetWebOutput {
	return o
}

func (o TargetWebOutput) ToTargetWebOutputWithContext(ctx context.Context) TargetWebOutput {
	return o
}

// Description of the object
func (o TargetWebOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TargetWeb) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
func (o TargetWebOutput) Key() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TargetWeb) pulumi.StringPtrOutput { return v.Key }).(pulumi.StringPtrOutput)
}

// Target name
func (o TargetWebOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TargetWeb) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Web target URL
func (o TargetWebOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *TargetWeb) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

type TargetWebArrayOutput struct{ *pulumi.OutputState }

func (TargetWebArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TargetWeb)(nil)).Elem()
}

func (o TargetWebArrayOutput) ToTargetWebArrayOutput() TargetWebArrayOutput {
	return o
}

func (o TargetWebArrayOutput) ToTargetWebArrayOutputWithContext(ctx context.Context) TargetWebArrayOutput {
	return o
}

func (o TargetWebArrayOutput) Index(i pulumi.IntInput) TargetWebOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TargetWeb {
		return vs[0].([]*TargetWeb)[vs[1].(int)]
	}).(TargetWebOutput)
}

type TargetWebMapOutput struct{ *pulumi.OutputState }

func (TargetWebMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TargetWeb)(nil)).Elem()
}

func (o TargetWebMapOutput) ToTargetWebMapOutput() TargetWebMapOutput {
	return o
}

func (o TargetWebMapOutput) ToTargetWebMapOutputWithContext(ctx context.Context) TargetWebMapOutput {
	return o
}

func (o TargetWebMapOutput) MapIndex(k pulumi.StringInput) TargetWebOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TargetWeb {
		return vs[0].(map[string]*TargetWeb)[vs[1].(string)]
	}).(TargetWebOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TargetWebInput)(nil)).Elem(), &TargetWeb{})
	pulumi.RegisterInputType(reflect.TypeOf((*TargetWebArrayInput)(nil)).Elem(), TargetWebArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TargetWebMapInput)(nil)).Elem(), TargetWebMap{})
	pulumi.RegisterOutputType(TargetWebOutput{})
	pulumi.RegisterOutputType(TargetWebArrayOutput{})
	pulumi.RegisterOutputType(TargetWebMapOutput{})
}
