// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless
{
    [AkeylessResourceType("akeyless:index/dynamicSecretRdp:DynamicSecretRdp")]
    public partial class DynamicSecretRdp : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Customize how temporary usernames are generated using go template
        /// </summary>
        [Output("customUsernameTemplate")]
        public Output<string?> CustomUsernameTemplate { get; private set; } = null!;

        /// <summary>
        /// Encrypt dynamic secret details with following key
        /// </summary>
        [Output("encryptionKeyName")]
        public Output<string?> EncryptionKeyName { get; private set; } = null!;

        /// <summary>
        /// Enable fixed user only
        /// </summary>
        [Output("fixedUserOnly")]
        public Output<string?> FixedUserOnly { get; private set; } = null!;

        /// <summary>
        /// Dynamic secret name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The length of the password to be generated
        /// </summary>
        [Output("passwordLength")]
        public Output<string?> PasswordLength { get; private set; } = null!;

        /// <summary>
        /// RDP Admin name
        /// </summary>
        [Output("rdpAdminName")]
        public Output<string?> RdpAdminName { get; private set; } = null!;

        /// <summary>
        /// RDP Admin Password
        /// </summary>
        [Output("rdpAdminPwd")]
        public Output<string?> RdpAdminPwd { get; private set; } = null!;

        /// <summary>
        /// RDP Host name
        /// </summary>
        [Output("rdpHostName")]
        public Output<string?> RdpHostName { get; private set; } = null!;

        /// <summary>
        /// RDP Host port
        /// </summary>
        [Output("rdpHostPort")]
        public Output<string?> RdpHostPort { get; private set; } = null!;

        /// <summary>
        /// RDP UserGroup name(s). Multiple values should be separated by comma
        /// </summary>
        [Output("rdpUserGroups")]
        public Output<string?> RdpUserGroups { get; private set; } = null!;

        /// <summary>
        /// Allow providing external user for a domain users
        /// </summary>
        [Output("secureAccessAllowExternalUser")]
        public Output<bool?> SecureAccessAllowExternalUser { get; private set; } = null!;

        /// <summary>
        /// Enable/Disable secure remote access, [true/false]
        /// </summary>
        [Output("secureAccessEnable")]
        public Output<string?> SecureAccessEnable { get; private set; } = null!;

        /// <summary>
        /// Target servers for connections., For multiple values repeat this flag.
        /// </summary>
        [Output("secureAccessHosts")]
        public Output<ImmutableArray<string>> SecureAccessHosts { get; private set; } = null!;

        /// <summary>
        /// Required when the Dynamic Secret is used for a domain user
        /// </summary>
        [Output("secureAccessRdpDomain")]
        public Output<string?> SecureAccessRdpDomain { get; private set; } = null!;

        /// <summary>
        /// Override the RDP Domain username
        /// </summary>
        [Output("secureAccessRdpUser")]
        public Output<string?> SecureAccessRdpUser { get; private set; } = null!;

        /// <summary>
        /// Enable Web Secure Remote Access
        /// </summary>
        [Output("secureAccessWeb")]
        public Output<bool> SecureAccessWeb { get; private set; } = null!;

        /// <summary>
        /// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Name of existing target to use in dynamic secret creation
        /// </summary>
        [Output("targetName")]
        public Output<string?> TargetName { get; private set; } = null!;

        /// <summary>
        /// User TTL
        /// </summary>
        [Output("userTtl")]
        public Output<string?> UserTtl { get; private set; } = null!;


        /// <summary>
        /// Create a DynamicSecretRdp resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DynamicSecretRdp(string name, DynamicSecretRdpArgs? args = null, CustomResourceOptions? options = null)
            : base("akeyless:index/dynamicSecretRdp:DynamicSecretRdp", name, args ?? new DynamicSecretRdpArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DynamicSecretRdp(string name, Input<string> id, DynamicSecretRdpState? state = null, CustomResourceOptions? options = null)
            : base("akeyless:index/dynamicSecretRdp:DynamicSecretRdp", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DynamicSecretRdp resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DynamicSecretRdp Get(string name, Input<string> id, DynamicSecretRdpState? state = null, CustomResourceOptions? options = null)
        {
            return new DynamicSecretRdp(name, id, state, options);
        }
    }

    public sealed class DynamicSecretRdpArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Customize how temporary usernames are generated using go template
        /// </summary>
        [Input("customUsernameTemplate")]
        public Input<string>? CustomUsernameTemplate { get; set; }

        /// <summary>
        /// Encrypt dynamic secret details with following key
        /// </summary>
        [Input("encryptionKeyName")]
        public Input<string>? EncryptionKeyName { get; set; }

        /// <summary>
        /// Enable fixed user only
        /// </summary>
        [Input("fixedUserOnly")]
        public Input<string>? FixedUserOnly { get; set; }

        /// <summary>
        /// Dynamic secret name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The length of the password to be generated
        /// </summary>
        [Input("passwordLength")]
        public Input<string>? PasswordLength { get; set; }

        /// <summary>
        /// RDP Admin name
        /// </summary>
        [Input("rdpAdminName")]
        public Input<string>? RdpAdminName { get; set; }

        /// <summary>
        /// RDP Admin Password
        /// </summary>
        [Input("rdpAdminPwd")]
        public Input<string>? RdpAdminPwd { get; set; }

        /// <summary>
        /// RDP Host name
        /// </summary>
        [Input("rdpHostName")]
        public Input<string>? RdpHostName { get; set; }

        /// <summary>
        /// RDP Host port
        /// </summary>
        [Input("rdpHostPort")]
        public Input<string>? RdpHostPort { get; set; }

        /// <summary>
        /// RDP UserGroup name(s). Multiple values should be separated by comma
        /// </summary>
        [Input("rdpUserGroups")]
        public Input<string>? RdpUserGroups { get; set; }

        /// <summary>
        /// Allow providing external user for a domain users
        /// </summary>
        [Input("secureAccessAllowExternalUser")]
        public Input<bool>? SecureAccessAllowExternalUser { get; set; }

        /// <summary>
        /// Enable/Disable secure remote access, [true/false]
        /// </summary>
        [Input("secureAccessEnable")]
        public Input<string>? SecureAccessEnable { get; set; }

        [Input("secureAccessHosts")]
        private InputList<string>? _secureAccessHosts;

        /// <summary>
        /// Target servers for connections., For multiple values repeat this flag.
        /// </summary>
        public InputList<string> SecureAccessHosts
        {
            get => _secureAccessHosts ?? (_secureAccessHosts = new InputList<string>());
            set => _secureAccessHosts = value;
        }

        /// <summary>
        /// Required when the Dynamic Secret is used for a domain user
        /// </summary>
        [Input("secureAccessRdpDomain")]
        public Input<string>? SecureAccessRdpDomain { get; set; }

        /// <summary>
        /// Override the RDP Domain username
        /// </summary>
        [Input("secureAccessRdpUser")]
        public Input<string>? SecureAccessRdpUser { get; set; }

        /// <summary>
        /// Enable Web Secure Remote Access
        /// </summary>
        [Input("secureAccessWeb")]
        public Input<bool>? SecureAccessWeb { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Name of existing target to use in dynamic secret creation
        /// </summary>
        [Input("targetName")]
        public Input<string>? TargetName { get; set; }

        /// <summary>
        /// User TTL
        /// </summary>
        [Input("userTtl")]
        public Input<string>? UserTtl { get; set; }

        public DynamicSecretRdpArgs()
        {
        }
        public static new DynamicSecretRdpArgs Empty => new DynamicSecretRdpArgs();
    }

    public sealed class DynamicSecretRdpState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Customize how temporary usernames are generated using go template
        /// </summary>
        [Input("customUsernameTemplate")]
        public Input<string>? CustomUsernameTemplate { get; set; }

        /// <summary>
        /// Encrypt dynamic secret details with following key
        /// </summary>
        [Input("encryptionKeyName")]
        public Input<string>? EncryptionKeyName { get; set; }

        /// <summary>
        /// Enable fixed user only
        /// </summary>
        [Input("fixedUserOnly")]
        public Input<string>? FixedUserOnly { get; set; }

        /// <summary>
        /// Dynamic secret name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The length of the password to be generated
        /// </summary>
        [Input("passwordLength")]
        public Input<string>? PasswordLength { get; set; }

        /// <summary>
        /// RDP Admin name
        /// </summary>
        [Input("rdpAdminName")]
        public Input<string>? RdpAdminName { get; set; }

        /// <summary>
        /// RDP Admin Password
        /// </summary>
        [Input("rdpAdminPwd")]
        public Input<string>? RdpAdminPwd { get; set; }

        /// <summary>
        /// RDP Host name
        /// </summary>
        [Input("rdpHostName")]
        public Input<string>? RdpHostName { get; set; }

        /// <summary>
        /// RDP Host port
        /// </summary>
        [Input("rdpHostPort")]
        public Input<string>? RdpHostPort { get; set; }

        /// <summary>
        /// RDP UserGroup name(s). Multiple values should be separated by comma
        /// </summary>
        [Input("rdpUserGroups")]
        public Input<string>? RdpUserGroups { get; set; }

        /// <summary>
        /// Allow providing external user for a domain users
        /// </summary>
        [Input("secureAccessAllowExternalUser")]
        public Input<bool>? SecureAccessAllowExternalUser { get; set; }

        /// <summary>
        /// Enable/Disable secure remote access, [true/false]
        /// </summary>
        [Input("secureAccessEnable")]
        public Input<string>? SecureAccessEnable { get; set; }

        [Input("secureAccessHosts")]
        private InputList<string>? _secureAccessHosts;

        /// <summary>
        /// Target servers for connections., For multiple values repeat this flag.
        /// </summary>
        public InputList<string> SecureAccessHosts
        {
            get => _secureAccessHosts ?? (_secureAccessHosts = new InputList<string>());
            set => _secureAccessHosts = value;
        }

        /// <summary>
        /// Required when the Dynamic Secret is used for a domain user
        /// </summary>
        [Input("secureAccessRdpDomain")]
        public Input<string>? SecureAccessRdpDomain { get; set; }

        /// <summary>
        /// Override the RDP Domain username
        /// </summary>
        [Input("secureAccessRdpUser")]
        public Input<string>? SecureAccessRdpUser { get; set; }

        /// <summary>
        /// Enable Web Secure Remote Access
        /// </summary>
        [Input("secureAccessWeb")]
        public Input<bool>? SecureAccessWeb { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Name of existing target to use in dynamic secret creation
        /// </summary>
        [Input("targetName")]
        public Input<string>? TargetName { get; set; }

        /// <summary>
        /// User TTL
        /// </summary>
        [Input("userTtl")]
        public Input<string>? UserTtl { get; set; }

        public DynamicSecretRdpState()
        {
        }
        public static new DynamicSecretRdpState Empty => new DynamicSecretRdpState();
    }
}
