// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless
{
    public static class GetDetokenize
    {
        public static Task<GetDetokenizeResult> InvokeAsync(GetDetokenizeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDetokenizeResult>("akeyless:index/getDetokenize:getDetokenize", args ?? new GetDetokenizeArgs(), options.WithDefaults());

        public static Output<GetDetokenizeResult> Invoke(GetDetokenizeInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDetokenizeResult>("akeyless:index/getDetokenize:getDetokenize", args ?? new GetDetokenizeInvokeArgs(), options.WithDefaults());

        public static Output<GetDetokenizeResult> Invoke(GetDetokenizeInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDetokenizeResult>("akeyless:index/getDetokenize:getDetokenize", args ?? new GetDetokenizeInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDetokenizeArgs : global::Pulumi.InvokeArgs
    {
        [Input("ciphertext", required: true)]
        public string Ciphertext { get; set; } = null!;

        [Input("tokenizerName", required: true)]
        public string TokenizerName { get; set; } = null!;

        [Input("tweak")]
        public string? Tweak { get; set; }

        public GetDetokenizeArgs()
        {
        }
        public static new GetDetokenizeArgs Empty => new GetDetokenizeArgs();
    }

    public sealed class GetDetokenizeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("ciphertext", required: true)]
        public Input<string> Ciphertext { get; set; } = null!;

        [Input("tokenizerName", required: true)]
        public Input<string> TokenizerName { get; set; } = null!;

        [Input("tweak")]
        public Input<string>? Tweak { get; set; }

        public GetDetokenizeInvokeArgs()
        {
        }
        public static new GetDetokenizeInvokeArgs Empty => new GetDetokenizeInvokeArgs();
    }


    [OutputType]
    public sealed class GetDetokenizeResult
    {
        public readonly string Ciphertext;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Result;
        public readonly string TokenizerName;
        public readonly string Tweak;

        [OutputConstructor]
        private GetDetokenizeResult(
            string ciphertext,

            string id,

            string result,

            string tokenizerName,

            string tweak)
        {
            Ciphertext = ciphertext;
            Id = id;
            Result = result;
            TokenizerName = tokenizerName;
            Tweak = tweak;
        }
    }
}
