// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless
{
    public static class GetTarget
    {
        public static Task<GetTargetResult> InvokeAsync(GetTargetArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTargetResult>("akeyless:index/getTarget:getTarget", args ?? new GetTargetArgs(), options.WithDefaults());

        public static Output<GetTargetResult> Invoke(GetTargetInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTargetResult>("akeyless:index/getTarget:getTarget", args ?? new GetTargetInvokeArgs(), options.WithDefaults());

        public static Output<GetTargetResult> Invoke(GetTargetInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTargetResult>("akeyless:index/getTarget:getTarget", args ?? new GetTargetInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTargetArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("showVersions")]
        public bool? ShowVersions { get; set; }

        public GetTargetArgs()
        {
        }
        public static new GetTargetArgs Empty => new GetTargetArgs();
    }

    public sealed class GetTargetInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("showVersions")]
        public Input<bool>? ShowVersions { get; set; }

        public GetTargetInvokeArgs()
        {
        }
        public static new GetTargetInvokeArgs Empty => new GetTargetInvokeArgs();
    }


    [OutputType]
    public sealed class GetTargetResult
    {
        public readonly ImmutableArray<string> ClientPermissions;
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int LastVersion;
        public readonly string Name;
        public readonly string ProtectionKeyName;
        public readonly bool? ShowVersions;
        public readonly int TargetId;
        public readonly string TargetItemsAssoc;
        public readonly string TargetName;
        public readonly string TargetType;
        public readonly string TargetVersions;
        public readonly bool WithCustomerFragment;

        [OutputConstructor]
        private GetTargetResult(
            ImmutableArray<string> clientPermissions,

            string description,

            string id,

            int lastVersion,

            string name,

            string protectionKeyName,

            bool? showVersions,

            int targetId,

            string targetItemsAssoc,

            string targetName,

            string targetType,

            string targetVersions,

            bool withCustomerFragment)
        {
            ClientPermissions = clientPermissions;
            Description = description;
            Id = id;
            LastVersion = lastVersion;
            Name = name;
            ProtectionKeyName = protectionKeyName;
            ShowVersions = showVersions;
            TargetId = targetId;
            TargetItemsAssoc = targetItemsAssoc;
            TargetName = targetName;
            TargetType = targetType;
            TargetVersions = targetVersions;
            WithCustomerFragment = withCustomerFragment;
        }
    }
}
