// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless
{
    [AkeylessResourceType("akeyless:index/targetK8s:TargetK8s")]
    public partial class TargetK8s : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Description of the object
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// K8S Cluster certificate. Base 64 encoded certificate.
        /// </summary>
        [Output("k8sClusterCaCert")]
        public Output<string> K8sClusterCaCert { get; private set; } = null!;

        /// <summary>
        /// K8S Cluster endpoint. https:// , &lt;DNS / IP&gt; of the cluster.
        /// </summary>
        [Output("k8sClusterEndpoint")]
        public Output<string> K8sClusterEndpoint { get; private set; } = null!;

        /// <summary>
        /// K8S Cluster authentication token.
        /// </summary>
        [Output("k8sClusterToken")]
        public Output<string> K8sClusterToken { get; private set; } = null!;

        /// <summary>
        /// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
        /// </summary>
        [Output("key")]
        public Output<string?> Key { get; private set; } = null!;

        /// <summary>
        /// Target name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a TargetK8s resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TargetK8s(string name, TargetK8sArgs args, CustomResourceOptions? options = null)
            : base("akeyless:index/targetK8s:TargetK8s", name, args ?? new TargetK8sArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TargetK8s(string name, Input<string> id, TargetK8sState? state = null, CustomResourceOptions? options = null)
            : base("akeyless:index/targetK8s:TargetK8s", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/akeyless-community/pulumi-akeyless",
                AdditionalSecretOutputs =
                {
                    "k8sClusterCaCert",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TargetK8s resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TargetK8s Get(string name, Input<string> id, TargetK8sState? state = null, CustomResourceOptions? options = null)
        {
            return new TargetK8s(name, id, state, options);
        }
    }

    public sealed class TargetK8sArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the object
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("k8sClusterCaCert", required: true)]
        private Input<string>? _k8sClusterCaCert;

        /// <summary>
        /// K8S Cluster certificate. Base 64 encoded certificate.
        /// </summary>
        public Input<string>? K8sClusterCaCert
        {
            get => _k8sClusterCaCert;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _k8sClusterCaCert = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// K8S Cluster endpoint. https:// , &lt;DNS / IP&gt; of the cluster.
        /// </summary>
        [Input("k8sClusterEndpoint", required: true)]
        public Input<string> K8sClusterEndpoint { get; set; } = null!;

        /// <summary>
        /// K8S Cluster authentication token.
        /// </summary>
        [Input("k8sClusterToken", required: true)]
        public Input<string> K8sClusterToken { get; set; } = null!;

        /// <summary>
        /// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public TargetK8sArgs()
        {
        }
        public static new TargetK8sArgs Empty => new TargetK8sArgs();
    }

    public sealed class TargetK8sState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the object
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("k8sClusterCaCert")]
        private Input<string>? _k8sClusterCaCert;

        /// <summary>
        /// K8S Cluster certificate. Base 64 encoded certificate.
        /// </summary>
        public Input<string>? K8sClusterCaCert
        {
            get => _k8sClusterCaCert;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _k8sClusterCaCert = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// K8S Cluster endpoint. https:// , &lt;DNS / IP&gt; of the cluster.
        /// </summary>
        [Input("k8sClusterEndpoint")]
        public Input<string>? K8sClusterEndpoint { get; set; }

        /// <summary>
        /// K8S Cluster authentication token.
        /// </summary>
        [Input("k8sClusterToken")]
        public Input<string>? K8sClusterToken { get; set; }

        /// <summary>
        /// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public TargetK8sState()
        {
        }
        public static new TargetK8sState Empty => new TargetK8sState();
    }
}
