// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless
{
    [AkeylessResourceType("akeyless:index/targetZerossl:TargetZerossl")]
    public partial class TargetZerossl : global::Pulumi.CustomResource
    {
        /// <summary>
        /// API Key of the ZeroSSLTarget account
        /// </summary>
        [Output("apiKey")]
        public Output<string> ApiKey { get; private set; } = null!;

        /// <summary>
        /// Description of the object
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// FQDN of the IMAP service
        /// </summary>
        [Output("imapFqdn")]
        public Output<string> ImapFqdn { get; private set; } = null!;

        /// <summary>
        /// Password to access the IMAP service
        /// </summary>
        [Output("imapPassword")]
        public Output<string> ImapPassword { get; private set; } = null!;

        /// <summary>
        /// Port of the IMAP service
        /// </summary>
        [Output("imapPort")]
        public Output<string?> ImapPort { get; private set; } = null!;

        /// <summary>
        /// Email to use when asking ZeroSSL to send a validation email, if empty will use username
        /// </summary>
        [Output("imapTargetEmail")]
        public Output<string?> ImapTargetEmail { get; private set; } = null!;

        /// <summary>
        /// Username to access the IMAP service
        /// </summary>
        [Output("imapUsername")]
        public Output<string> ImapUsername { get; private set; } = null!;

        /// <summary>
        /// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
        /// </summary>
        [Output("key")]
        public Output<string?> Key { get; private set; } = null!;

        /// <summary>
        /// Target name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Timeout waiting for certificate validation
        /// </summary>
        [Output("timeout")]
        public Output<string?> Timeout { get; private set; } = null!;


        /// <summary>
        /// Create a TargetZerossl resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TargetZerossl(string name, TargetZerosslArgs args, CustomResourceOptions? options = null)
            : base("akeyless:index/targetZerossl:TargetZerossl", name, args ?? new TargetZerosslArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TargetZerossl(string name, Input<string> id, TargetZerosslState? state = null, CustomResourceOptions? options = null)
            : base("akeyless:index/targetZerossl:TargetZerossl", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/akeyless-community/pulumi-akeyless",
                AdditionalSecretOutputs =
                {
                    "apiKey",
                    "imapPassword",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TargetZerossl resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TargetZerossl Get(string name, Input<string> id, TargetZerosslState? state = null, CustomResourceOptions? options = null)
        {
            return new TargetZerossl(name, id, state, options);
        }
    }

    public sealed class TargetZerosslArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey", required: true)]
        private Input<string>? _apiKey;

        /// <summary>
        /// API Key of the ZeroSSLTarget account
        /// </summary>
        public Input<string>? ApiKey
        {
            get => _apiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Description of the object
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// FQDN of the IMAP service
        /// </summary>
        [Input("imapFqdn", required: true)]
        public Input<string> ImapFqdn { get; set; } = null!;

        [Input("imapPassword", required: true)]
        private Input<string>? _imapPassword;

        /// <summary>
        /// Password to access the IMAP service
        /// </summary>
        public Input<string>? ImapPassword
        {
            get => _imapPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _imapPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Port of the IMAP service
        /// </summary>
        [Input("imapPort")]
        public Input<string>? ImapPort { get; set; }

        /// <summary>
        /// Email to use when asking ZeroSSL to send a validation email, if empty will use username
        /// </summary>
        [Input("imapTargetEmail")]
        public Input<string>? ImapTargetEmail { get; set; }

        /// <summary>
        /// Username to access the IMAP service
        /// </summary>
        [Input("imapUsername", required: true)]
        public Input<string> ImapUsername { get; set; } = null!;

        /// <summary>
        /// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Timeout waiting for certificate validation
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        public TargetZerosslArgs()
        {
        }
        public static new TargetZerosslArgs Empty => new TargetZerosslArgs();
    }

    public sealed class TargetZerosslState : global::Pulumi.ResourceArgs
    {
        [Input("apiKey")]
        private Input<string>? _apiKey;

        /// <summary>
        /// API Key of the ZeroSSLTarget account
        /// </summary>
        public Input<string>? ApiKey
        {
            get => _apiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Description of the object
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// FQDN of the IMAP service
        /// </summary>
        [Input("imapFqdn")]
        public Input<string>? ImapFqdn { get; set; }

        [Input("imapPassword")]
        private Input<string>? _imapPassword;

        /// <summary>
        /// Password to access the IMAP service
        /// </summary>
        public Input<string>? ImapPassword
        {
            get => _imapPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _imapPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Port of the IMAP service
        /// </summary>
        [Input("imapPort")]
        public Input<string>? ImapPort { get; set; }

        /// <summary>
        /// Email to use when asking ZeroSSL to send a validation email, if empty will use username
        /// </summary>
        [Input("imapTargetEmail")]
        public Input<string>? ImapTargetEmail { get; set; }

        /// <summary>
        /// Username to access the IMAP service
        /// </summary>
        [Input("imapUsername")]
        public Input<string>? ImapUsername { get; set; }

        /// <summary>
        /// Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Timeout waiting for certificate validation
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        public TargetZerosslState()
        {
        }
        public static new TargetZerosslState Empty => new TargetZerosslState();
    }
}
