# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AssociateRoleAuthMethodArgs', 'AssociateRoleAuthMethod']

@pulumi.input_type
class AssociateRoleAuthMethodArgs:
    def __init__(__self__, *,
                 am_name: pulumi.Input[_builtins.str],
                 role_name: pulumi.Input[_builtins.str],
                 case_sensitive: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_claims: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a AssociateRoleAuthMethod resource.

        :param pulumi.Input[_builtins.str] am_name: The auth method to associate
        :param pulumi.Input[_builtins.str] role_name: The role to associate
        :param pulumi.Input[_builtins.str] case_sensitive: Treat sub claims as case-sensitive
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] sub_claims: key/val of sub claims, e.g group=admins,developers
        """
        pulumi.set(__self__, "am_name", am_name)
        pulumi.set(__self__, "role_name", role_name)
        if case_sensitive is not None:
            pulumi.set(__self__, "case_sensitive", case_sensitive)
        if sub_claims is not None:
            pulumi.set(__self__, "sub_claims", sub_claims)

    @_builtins.property
    @pulumi.getter(name="amName")
    def am_name(self) -> pulumi.Input[_builtins.str]:
        """
        The auth method to associate
        """
        return pulumi.get(self, "am_name")

    @am_name.setter
    def am_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "am_name", value)

    @_builtins.property
    @pulumi.getter(name="roleName")
    def role_name(self) -> pulumi.Input[_builtins.str]:
        """
        The role to associate
        """
        return pulumi.get(self, "role_name")

    @role_name.setter
    def role_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role_name", value)

    @_builtins.property
    @pulumi.getter(name="caseSensitive")
    def case_sensitive(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Treat sub claims as case-sensitive
        """
        return pulumi.get(self, "case_sensitive")

    @case_sensitive.setter
    def case_sensitive(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "case_sensitive", value)

    @_builtins.property
    @pulumi.getter(name="subClaims")
    def sub_claims(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        key/val of sub claims, e.g group=admins,developers
        """
        return pulumi.get(self, "sub_claims")

    @sub_claims.setter
    def sub_claims(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "sub_claims", value)


@pulumi.input_type
class _AssociateRoleAuthMethodState:
    def __init__(__self__, *,
                 am_name: Optional[pulumi.Input[_builtins.str]] = None,
                 case_sensitive: Optional[pulumi.Input[_builtins.str]] = None,
                 role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_claims: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering AssociateRoleAuthMethod resources.

        :param pulumi.Input[_builtins.str] am_name: The auth method to associate
        :param pulumi.Input[_builtins.str] case_sensitive: Treat sub claims as case-sensitive
        :param pulumi.Input[_builtins.str] role_name: The role to associate
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] sub_claims: key/val of sub claims, e.g group=admins,developers
        """
        if am_name is not None:
            pulumi.set(__self__, "am_name", am_name)
        if case_sensitive is not None:
            pulumi.set(__self__, "case_sensitive", case_sensitive)
        if role_name is not None:
            pulumi.set(__self__, "role_name", role_name)
        if sub_claims is not None:
            pulumi.set(__self__, "sub_claims", sub_claims)

    @_builtins.property
    @pulumi.getter(name="amName")
    def am_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The auth method to associate
        """
        return pulumi.get(self, "am_name")

    @am_name.setter
    def am_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "am_name", value)

    @_builtins.property
    @pulumi.getter(name="caseSensitive")
    def case_sensitive(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Treat sub claims as case-sensitive
        """
        return pulumi.get(self, "case_sensitive")

    @case_sensitive.setter
    def case_sensitive(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "case_sensitive", value)

    @_builtins.property
    @pulumi.getter(name="roleName")
    def role_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The role to associate
        """
        return pulumi.get(self, "role_name")

    @role_name.setter
    def role_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "role_name", value)

    @_builtins.property
    @pulumi.getter(name="subClaims")
    def sub_claims(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        key/val of sub claims, e.g group=admins,developers
        """
        return pulumi.get(self, "sub_claims")

    @sub_claims.setter
    def sub_claims(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "sub_claims", value)


@pulumi.type_token("akeyless:index/associateRoleAuthMethod:AssociateRoleAuthMethod")
class AssociateRoleAuthMethod(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 am_name: Optional[pulumi.Input[_builtins.str]] = None,
                 case_sensitive: Optional[pulumi.Input[_builtins.str]] = None,
                 role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_claims: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a AssociateRoleAuthMethod resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] am_name: The auth method to associate
        :param pulumi.Input[_builtins.str] case_sensitive: Treat sub claims as case-sensitive
        :param pulumi.Input[_builtins.str] role_name: The role to associate
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] sub_claims: key/val of sub claims, e.g group=admins,developers
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AssociateRoleAuthMethodArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AssociateRoleAuthMethod resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AssociateRoleAuthMethodArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AssociateRoleAuthMethodArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 am_name: Optional[pulumi.Input[_builtins.str]] = None,
                 case_sensitive: Optional[pulumi.Input[_builtins.str]] = None,
                 role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_claims: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AssociateRoleAuthMethodArgs.__new__(AssociateRoleAuthMethodArgs)

            if am_name is None and not opts.urn:
                raise TypeError("Missing required property 'am_name'")
            __props__.__dict__["am_name"] = am_name
            __props__.__dict__["case_sensitive"] = case_sensitive
            if role_name is None and not opts.urn:
                raise TypeError("Missing required property 'role_name'")
            __props__.__dict__["role_name"] = role_name
            __props__.__dict__["sub_claims"] = sub_claims
        super(AssociateRoleAuthMethod, __self__).__init__(
            'akeyless:index/associateRoleAuthMethod:AssociateRoleAuthMethod',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            am_name: Optional[pulumi.Input[_builtins.str]] = None,
            case_sensitive: Optional[pulumi.Input[_builtins.str]] = None,
            role_name: Optional[pulumi.Input[_builtins.str]] = None,
            sub_claims: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None) -> 'AssociateRoleAuthMethod':
        """
        Get an existing AssociateRoleAuthMethod resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] am_name: The auth method to associate
        :param pulumi.Input[_builtins.str] case_sensitive: Treat sub claims as case-sensitive
        :param pulumi.Input[_builtins.str] role_name: The role to associate
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] sub_claims: key/val of sub claims, e.g group=admins,developers
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AssociateRoleAuthMethodState.__new__(_AssociateRoleAuthMethodState)

        __props__.__dict__["am_name"] = am_name
        __props__.__dict__["case_sensitive"] = case_sensitive
        __props__.__dict__["role_name"] = role_name
        __props__.__dict__["sub_claims"] = sub_claims
        return AssociateRoleAuthMethod(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="amName")
    def am_name(self) -> pulumi.Output[_builtins.str]:
        """
        The auth method to associate
        """
        return pulumi.get(self, "am_name")

    @_builtins.property
    @pulumi.getter(name="caseSensitive")
    def case_sensitive(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Treat sub claims as case-sensitive
        """
        return pulumi.get(self, "case_sensitive")

    @_builtins.property
    @pulumi.getter(name="roleName")
    def role_name(self) -> pulumi.Output[_builtins.str]:
        """
        The role to associate
        """
        return pulumi.get(self, "role_name")

    @_builtins.property
    @pulumi.getter(name="subClaims")
    def sub_claims(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        key/val of sub claims, e.g group=admins,developers
        """
        return pulumi.get(self, "sub_claims")

