# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AuthMethodOauth2Args', 'AuthMethodOauth2']

@pulumi.input_type
class AuthMethodOauth2Args:
    def __init__(__self__, *,
                 unique_identifier: pulumi.Input[_builtins.str],
                 access_expires: Optional[pulumi.Input[_builtins.int]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 audit_logs_claims: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: Optional[pulumi.Input[_builtins.str]] = None,
                 force_sub_claims: Optional[pulumi.Input[_builtins.bool]] = None,
                 gateway_url: Optional[pulumi.Input[_builtins.str]] = None,
                 issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_json_data: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a AuthMethodOauth2 resource.

        :param pulumi.Input[_builtins.str] unique_identifier: A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        :param pulumi.Input[_builtins.int] access_expires: Access expiration date in Unix timestamp (select 0 for access without expiry date)
        :param pulumi.Input[_builtins.str] audience: The audience in the JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] audit_logs_claims: Subclaims to include in audit logs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_client_ids: The clients ids that the access is restricted to
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_ips: A CIDR whitelist with the IPs that the access is restricted to
        :param pulumi.Input[_builtins.str] delete_protection: Protection from accidental deletion of this auth method, [true/false]
        :param pulumi.Input[_builtins.bool] force_sub_claims: enforce role-association must include sub claims
        :param pulumi.Input[_builtins.str] gateway_url: Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        :param pulumi.Input[_builtins.str] issuer: Issuer URL
        :param pulumi.Input[_builtins.str] jwks_json_data: The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        :param pulumi.Input[_builtins.str] jwks_uri: The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        :param pulumi.Input[_builtins.int] jwt_ttl: Creds expiration time in minutes
        :param pulumi.Input[_builtins.str] name: Auth Method name
        """
        pulumi.set(__self__, "unique_identifier", unique_identifier)
        if access_expires is not None:
            pulumi.set(__self__, "access_expires", access_expires)
        if audience is not None:
            pulumi.set(__self__, "audience", audience)
        if audit_logs_claims is not None:
            pulumi.set(__self__, "audit_logs_claims", audit_logs_claims)
        if bound_client_ids is not None:
            pulumi.set(__self__, "bound_client_ids", bound_client_ids)
        if bound_ips is not None:
            pulumi.set(__self__, "bound_ips", bound_ips)
        if delete_protection is not None:
            pulumi.set(__self__, "delete_protection", delete_protection)
        if force_sub_claims is not None:
            pulumi.set(__self__, "force_sub_claims", force_sub_claims)
        if gateway_url is not None:
            pulumi.set(__self__, "gateway_url", gateway_url)
        if issuer is not None:
            pulumi.set(__self__, "issuer", issuer)
        if jwks_json_data is not None:
            pulumi.set(__self__, "jwks_json_data", jwks_json_data)
        if jwks_uri is not None:
            pulumi.set(__self__, "jwks_uri", jwks_uri)
        if jwt_ttl is not None:
            pulumi.set(__self__, "jwt_ttl", jwt_ttl)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="uniqueIdentifier")
    def unique_identifier(self) -> pulumi.Input[_builtins.str]:
        """
        A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        """
        return pulumi.get(self, "unique_identifier")

    @unique_identifier.setter
    def unique_identifier(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "unique_identifier", value)

    @_builtins.property
    @pulumi.getter(name="accessExpires")
    def access_expires(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Access expiration date in Unix timestamp (select 0 for access without expiry date)
        """
        return pulumi.get(self, "access_expires")

    @access_expires.setter
    def access_expires(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "access_expires", value)

    @_builtins.property
    @pulumi.getter
    def audience(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The audience in the JWT
        """
        return pulumi.get(self, "audience")

    @audience.setter
    def audience(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "audience", value)

    @_builtins.property
    @pulumi.getter(name="auditLogsClaims")
    def audit_logs_claims(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Subclaims to include in audit logs
        """
        return pulumi.get(self, "audit_logs_claims")

    @audit_logs_claims.setter
    def audit_logs_claims(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "audit_logs_claims", value)

    @_builtins.property
    @pulumi.getter(name="boundClientIds")
    def bound_client_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The clients ids that the access is restricted to
        """
        return pulumi.get(self, "bound_client_ids")

    @bound_client_ids.setter
    def bound_client_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bound_client_ids", value)

    @_builtins.property
    @pulumi.getter(name="boundIps")
    def bound_ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A CIDR whitelist with the IPs that the access is restricted to
        """
        return pulumi.get(self, "bound_ips")

    @bound_ips.setter
    def bound_ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bound_ips", value)

    @_builtins.property
    @pulumi.getter(name="deleteProtection")
    def delete_protection(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Protection from accidental deletion of this auth method, [true/false]
        """
        return pulumi.get(self, "delete_protection")

    @delete_protection.setter
    def delete_protection(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "delete_protection", value)

    @_builtins.property
    @pulumi.getter(name="forceSubClaims")
    def force_sub_claims(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        enforce role-association must include sub claims
        """
        return pulumi.get(self, "force_sub_claims")

    @force_sub_claims.setter
    def force_sub_claims(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "force_sub_claims", value)

    @_builtins.property
    @pulumi.getter(name="gatewayUrl")
    def gateway_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        """
        return pulumi.get(self, "gateway_url")

    @gateway_url.setter
    def gateway_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "gateway_url", value)

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Issuer URL
        """
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "issuer", value)

    @_builtins.property
    @pulumi.getter(name="jwksJsonData")
    def jwks_json_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        """
        return pulumi.get(self, "jwks_json_data")

    @jwks_json_data.setter
    def jwks_json_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jwks_json_data", value)

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        """
        return pulumi.get(self, "jwks_uri")

    @jwks_uri.setter
    def jwks_uri(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jwks_uri", value)

    @_builtins.property
    @pulumi.getter(name="jwtTtl")
    def jwt_ttl(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Creds expiration time in minutes
        """
        return pulumi.get(self, "jwt_ttl")

    @jwt_ttl.setter
    def jwt_ttl(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "jwt_ttl", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auth Method name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _AuthMethodOauth2State:
    def __init__(__self__, *,
                 access_expires: Optional[pulumi.Input[_builtins.int]] = None,
                 access_id: Optional[pulumi.Input[_builtins.str]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 audit_logs_claims: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: Optional[pulumi.Input[_builtins.str]] = None,
                 force_sub_claims: Optional[pulumi.Input[_builtins.bool]] = None,
                 gateway_url: Optional[pulumi.Input[_builtins.str]] = None,
                 issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_json_data: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 unique_identifier: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering AuthMethodOauth2 resources.

        :param pulumi.Input[_builtins.int] access_expires: Access expiration date in Unix timestamp (select 0 for access without expiry date)
        :param pulumi.Input[_builtins.str] access_id: Auth Method access ID
        :param pulumi.Input[_builtins.str] audience: The audience in the JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] audit_logs_claims: Subclaims to include in audit logs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_client_ids: The clients ids that the access is restricted to
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_ips: A CIDR whitelist with the IPs that the access is restricted to
        :param pulumi.Input[_builtins.str] delete_protection: Protection from accidental deletion of this auth method, [true/false]
        :param pulumi.Input[_builtins.bool] force_sub_claims: enforce role-association must include sub claims
        :param pulumi.Input[_builtins.str] gateway_url: Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        :param pulumi.Input[_builtins.str] issuer: Issuer URL
        :param pulumi.Input[_builtins.str] jwks_json_data: The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        :param pulumi.Input[_builtins.str] jwks_uri: The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        :param pulumi.Input[_builtins.int] jwt_ttl: Creds expiration time in minutes
        :param pulumi.Input[_builtins.str] name: Auth Method name
        :param pulumi.Input[_builtins.str] unique_identifier: A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        """
        if access_expires is not None:
            pulumi.set(__self__, "access_expires", access_expires)
        if access_id is not None:
            pulumi.set(__self__, "access_id", access_id)
        if audience is not None:
            pulumi.set(__self__, "audience", audience)
        if audit_logs_claims is not None:
            pulumi.set(__self__, "audit_logs_claims", audit_logs_claims)
        if bound_client_ids is not None:
            pulumi.set(__self__, "bound_client_ids", bound_client_ids)
        if bound_ips is not None:
            pulumi.set(__self__, "bound_ips", bound_ips)
        if delete_protection is not None:
            pulumi.set(__self__, "delete_protection", delete_protection)
        if force_sub_claims is not None:
            pulumi.set(__self__, "force_sub_claims", force_sub_claims)
        if gateway_url is not None:
            pulumi.set(__self__, "gateway_url", gateway_url)
        if issuer is not None:
            pulumi.set(__self__, "issuer", issuer)
        if jwks_json_data is not None:
            pulumi.set(__self__, "jwks_json_data", jwks_json_data)
        if jwks_uri is not None:
            pulumi.set(__self__, "jwks_uri", jwks_uri)
        if jwt_ttl is not None:
            pulumi.set(__self__, "jwt_ttl", jwt_ttl)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if unique_identifier is not None:
            pulumi.set(__self__, "unique_identifier", unique_identifier)

    @_builtins.property
    @pulumi.getter(name="accessExpires")
    def access_expires(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Access expiration date in Unix timestamp (select 0 for access without expiry date)
        """
        return pulumi.get(self, "access_expires")

    @access_expires.setter
    def access_expires(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "access_expires", value)

    @_builtins.property
    @pulumi.getter(name="accessId")
    def access_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auth Method access ID
        """
        return pulumi.get(self, "access_id")

    @access_id.setter
    def access_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "access_id", value)

    @_builtins.property
    @pulumi.getter
    def audience(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The audience in the JWT
        """
        return pulumi.get(self, "audience")

    @audience.setter
    def audience(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "audience", value)

    @_builtins.property
    @pulumi.getter(name="auditLogsClaims")
    def audit_logs_claims(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Subclaims to include in audit logs
        """
        return pulumi.get(self, "audit_logs_claims")

    @audit_logs_claims.setter
    def audit_logs_claims(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "audit_logs_claims", value)

    @_builtins.property
    @pulumi.getter(name="boundClientIds")
    def bound_client_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The clients ids that the access is restricted to
        """
        return pulumi.get(self, "bound_client_ids")

    @bound_client_ids.setter
    def bound_client_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bound_client_ids", value)

    @_builtins.property
    @pulumi.getter(name="boundIps")
    def bound_ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A CIDR whitelist with the IPs that the access is restricted to
        """
        return pulumi.get(self, "bound_ips")

    @bound_ips.setter
    def bound_ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bound_ips", value)

    @_builtins.property
    @pulumi.getter(name="deleteProtection")
    def delete_protection(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Protection from accidental deletion of this auth method, [true/false]
        """
        return pulumi.get(self, "delete_protection")

    @delete_protection.setter
    def delete_protection(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "delete_protection", value)

    @_builtins.property
    @pulumi.getter(name="forceSubClaims")
    def force_sub_claims(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        enforce role-association must include sub claims
        """
        return pulumi.get(self, "force_sub_claims")

    @force_sub_claims.setter
    def force_sub_claims(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "force_sub_claims", value)

    @_builtins.property
    @pulumi.getter(name="gatewayUrl")
    def gateway_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        """
        return pulumi.get(self, "gateway_url")

    @gateway_url.setter
    def gateway_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "gateway_url", value)

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Issuer URL
        """
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "issuer", value)

    @_builtins.property
    @pulumi.getter(name="jwksJsonData")
    def jwks_json_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        """
        return pulumi.get(self, "jwks_json_data")

    @jwks_json_data.setter
    def jwks_json_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jwks_json_data", value)

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        """
        return pulumi.get(self, "jwks_uri")

    @jwks_uri.setter
    def jwks_uri(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jwks_uri", value)

    @_builtins.property
    @pulumi.getter(name="jwtTtl")
    def jwt_ttl(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Creds expiration time in minutes
        """
        return pulumi.get(self, "jwt_ttl")

    @jwt_ttl.setter
    def jwt_ttl(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "jwt_ttl", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auth Method name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="uniqueIdentifier")
    def unique_identifier(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        """
        return pulumi.get(self, "unique_identifier")

    @unique_identifier.setter
    def unique_identifier(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "unique_identifier", value)


@pulumi.type_token("akeyless:index/authMethodOauth2:AuthMethodOauth2")
class AuthMethodOauth2(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_expires: Optional[pulumi.Input[_builtins.int]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 audit_logs_claims: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: Optional[pulumi.Input[_builtins.str]] = None,
                 force_sub_claims: Optional[pulumi.Input[_builtins.bool]] = None,
                 gateway_url: Optional[pulumi.Input[_builtins.str]] = None,
                 issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_json_data: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 unique_identifier: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a AuthMethodOauth2 resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] access_expires: Access expiration date in Unix timestamp (select 0 for access without expiry date)
        :param pulumi.Input[_builtins.str] audience: The audience in the JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] audit_logs_claims: Subclaims to include in audit logs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_client_ids: The clients ids that the access is restricted to
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_ips: A CIDR whitelist with the IPs that the access is restricted to
        :param pulumi.Input[_builtins.str] delete_protection: Protection from accidental deletion of this auth method, [true/false]
        :param pulumi.Input[_builtins.bool] force_sub_claims: enforce role-association must include sub claims
        :param pulumi.Input[_builtins.str] gateway_url: Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        :param pulumi.Input[_builtins.str] issuer: Issuer URL
        :param pulumi.Input[_builtins.str] jwks_json_data: The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        :param pulumi.Input[_builtins.str] jwks_uri: The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        :param pulumi.Input[_builtins.int] jwt_ttl: Creds expiration time in minutes
        :param pulumi.Input[_builtins.str] name: Auth Method name
        :param pulumi.Input[_builtins.str] unique_identifier: A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AuthMethodOauth2Args,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AuthMethodOauth2 resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AuthMethodOauth2Args args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AuthMethodOauth2Args, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_expires: Optional[pulumi.Input[_builtins.int]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 audit_logs_claims: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bound_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: Optional[pulumi.Input[_builtins.str]] = None,
                 force_sub_claims: Optional[pulumi.Input[_builtins.bool]] = None,
                 gateway_url: Optional[pulumi.Input[_builtins.str]] = None,
                 issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_json_data: Optional[pulumi.Input[_builtins.str]] = None,
                 jwks_uri: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 unique_identifier: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AuthMethodOauth2Args.__new__(AuthMethodOauth2Args)

            __props__.__dict__["access_expires"] = access_expires
            __props__.__dict__["audience"] = audience
            __props__.__dict__["audit_logs_claims"] = audit_logs_claims
            __props__.__dict__["bound_client_ids"] = bound_client_ids
            __props__.__dict__["bound_ips"] = bound_ips
            __props__.__dict__["delete_protection"] = delete_protection
            __props__.__dict__["force_sub_claims"] = force_sub_claims
            __props__.__dict__["gateway_url"] = gateway_url
            __props__.__dict__["issuer"] = issuer
            __props__.__dict__["jwks_json_data"] = jwks_json_data
            __props__.__dict__["jwks_uri"] = jwks_uri
            __props__.__dict__["jwt_ttl"] = jwt_ttl
            __props__.__dict__["name"] = name
            if unique_identifier is None and not opts.urn:
                raise TypeError("Missing required property 'unique_identifier'")
            __props__.__dict__["unique_identifier"] = unique_identifier
            __props__.__dict__["access_id"] = None
        super(AuthMethodOauth2, __self__).__init__(
            'akeyless:index/authMethodOauth2:AuthMethodOauth2',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            access_expires: Optional[pulumi.Input[_builtins.int]] = None,
            access_id: Optional[pulumi.Input[_builtins.str]] = None,
            audience: Optional[pulumi.Input[_builtins.str]] = None,
            audit_logs_claims: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            bound_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            bound_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            delete_protection: Optional[pulumi.Input[_builtins.str]] = None,
            force_sub_claims: Optional[pulumi.Input[_builtins.bool]] = None,
            gateway_url: Optional[pulumi.Input[_builtins.str]] = None,
            issuer: Optional[pulumi.Input[_builtins.str]] = None,
            jwks_json_data: Optional[pulumi.Input[_builtins.str]] = None,
            jwks_uri: Optional[pulumi.Input[_builtins.str]] = None,
            jwt_ttl: Optional[pulumi.Input[_builtins.int]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            unique_identifier: Optional[pulumi.Input[_builtins.str]] = None) -> 'AuthMethodOauth2':
        """
        Get an existing AuthMethodOauth2 resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] access_expires: Access expiration date in Unix timestamp (select 0 for access without expiry date)
        :param pulumi.Input[_builtins.str] access_id: Auth Method access ID
        :param pulumi.Input[_builtins.str] audience: The audience in the JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] audit_logs_claims: Subclaims to include in audit logs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_client_ids: The clients ids that the access is restricted to
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bound_ips: A CIDR whitelist with the IPs that the access is restricted to
        :param pulumi.Input[_builtins.str] delete_protection: Protection from accidental deletion of this auth method, [true/false]
        :param pulumi.Input[_builtins.bool] force_sub_claims: enforce role-association must include sub claims
        :param pulumi.Input[_builtins.str] gateway_url: Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        :param pulumi.Input[_builtins.str] issuer: Issuer URL
        :param pulumi.Input[_builtins.str] jwks_json_data: The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        :param pulumi.Input[_builtins.str] jwks_uri: The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        :param pulumi.Input[_builtins.int] jwt_ttl: Creds expiration time in minutes
        :param pulumi.Input[_builtins.str] name: Auth Method name
        :param pulumi.Input[_builtins.str] unique_identifier: A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AuthMethodOauth2State.__new__(_AuthMethodOauth2State)

        __props__.__dict__["access_expires"] = access_expires
        __props__.__dict__["access_id"] = access_id
        __props__.__dict__["audience"] = audience
        __props__.__dict__["audit_logs_claims"] = audit_logs_claims
        __props__.__dict__["bound_client_ids"] = bound_client_ids
        __props__.__dict__["bound_ips"] = bound_ips
        __props__.__dict__["delete_protection"] = delete_protection
        __props__.__dict__["force_sub_claims"] = force_sub_claims
        __props__.__dict__["gateway_url"] = gateway_url
        __props__.__dict__["issuer"] = issuer
        __props__.__dict__["jwks_json_data"] = jwks_json_data
        __props__.__dict__["jwks_uri"] = jwks_uri
        __props__.__dict__["jwt_ttl"] = jwt_ttl
        __props__.__dict__["name"] = name
        __props__.__dict__["unique_identifier"] = unique_identifier
        return AuthMethodOauth2(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessExpires")
    def access_expires(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Access expiration date in Unix timestamp (select 0 for access without expiry date)
        """
        return pulumi.get(self, "access_expires")

    @_builtins.property
    @pulumi.getter(name="accessId")
    def access_id(self) -> pulumi.Output[_builtins.str]:
        """
        Auth Method access ID
        """
        return pulumi.get(self, "access_id")

    @_builtins.property
    @pulumi.getter
    def audience(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The audience in the JWT
        """
        return pulumi.get(self, "audience")

    @_builtins.property
    @pulumi.getter(name="auditLogsClaims")
    def audit_logs_claims(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Subclaims to include in audit logs
        """
        return pulumi.get(self, "audit_logs_claims")

    @_builtins.property
    @pulumi.getter(name="boundClientIds")
    def bound_client_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The clients ids that the access is restricted to
        """
        return pulumi.get(self, "bound_client_ids")

    @_builtins.property
    @pulumi.getter(name="boundIps")
    def bound_ips(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A CIDR whitelist with the IPs that the access is restricted to
        """
        return pulumi.get(self, "bound_ips")

    @_builtins.property
    @pulumi.getter(name="deleteProtection")
    def delete_protection(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Protection from accidental deletion of this auth method, [true/false]
        """
        return pulumi.get(self, "delete_protection")

    @_builtins.property
    @pulumi.getter(name="forceSubClaims")
    def force_sub_claims(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        enforce role-association must include sub claims
        """
        return pulumi.get(self, "force_sub_claims")

    @_builtins.property
    @pulumi.getter(name="gatewayUrl")
    def gateway_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
        """
        return pulumi.get(self, "gateway_url")

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Issuer URL
        """
        return pulumi.get(self, "issuer")

    @_builtins.property
    @pulumi.getter(name="jwksJsonData")
    def jwks_json_data(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The JSON Web Key Set (JWKS) containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization serve, in base64 format.
        """
        return pulumi.get(self, "jwks_json_data")

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The URL to the JSON Web Key Set (JWKS) that containing the public keys that should be used to verify any JSON Web Token (JWT) issued by the authorization server.
        """
        return pulumi.get(self, "jwks_uri")

    @_builtins.property
    @pulumi.getter(name="jwtTtl")
    def jwt_ttl(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Creds expiration time in minutes
        """
        return pulumi.get(self, "jwt_ttl")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Auth Method name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="uniqueIdentifier")
    def unique_identifier(self) -> pulumi.Output[_builtins.str]:
        """
        A unique identifier (ID) value should be configured for OAuth2, LDAP and SAML authentication method types and is usually a value such as the email, username, or upn for example. Whenever a user logs in with a token, these authentication types issue a sub claim that contains details uniquely identifying that user. This sub claim includes a key containing the ID value that you configured, and is used to distinguish between different users from within the same organization.
        """
        return pulumi.get(self, "unique_identifier")

