# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['EventForwarderWebhookArgs', 'EventForwarderWebhook']

@pulumi.input_type
class EventForwarderWebhookArgs:
    def __init__(__self__, *,
                 auth_methods_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 auth_token: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 client_cert_data: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 event_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 every: Optional[pulumi.Input[_builtins.str]] = None,
                 gateways_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 items_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key_data: Optional[pulumi.Input[_builtins.str]] = None,
                 runner_type: Optional[pulumi.Input[_builtins.str]] = None,
                 server_certificates: Optional[pulumi.Input[_builtins.str]] = None,
                 targets_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a EventForwarderWebhook resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auth_methods_event_source_locations: Auth Methods event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] auth_token: Base64 encoded Token string relevant for token auth-type
        :param pulumi.Input[_builtins.str] auth_type: The Webhook authentication type [user-pass, bearer-token, certificate]
        :param pulumi.Input[_builtins.str] client_cert_data: Base64 encoded PEM certificate, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] event_types: A comma-separated list of types of events to notify about
        :param pulumi.Input[_builtins.str] every: Rate of periodic runner repetition in hours
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] gateways_event_source_locations: Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] items_event_source_locations: Items event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] key: Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        :param pulumi.Input[_builtins.str] name: Event Forwarder name
        :param pulumi.Input[_builtins.str] password: Password for authentication relevant for user-pass auth-type
        :param pulumi.Input[_builtins.str] private_key_data: Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] runner_type: Event Forwarder runner type [immediate/periodic]
        :param pulumi.Input[_builtins.str] server_certificates: Base64 encoded PEM certificate of the Webhook
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] targets_event_source_locations: Targets event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] url: Webhook URL
        :param pulumi.Input[_builtins.str] username: Username for authentication relevant for user-pass auth-type
        """
        if auth_methods_event_source_locations is not None:
            pulumi.set(__self__, "auth_methods_event_source_locations", auth_methods_event_source_locations)
        if auth_token is not None:
            pulumi.set(__self__, "auth_token", auth_token)
        if auth_type is not None:
            pulumi.set(__self__, "auth_type", auth_type)
        if client_cert_data is not None:
            pulumi.set(__self__, "client_cert_data", client_cert_data)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if event_types is not None:
            pulumi.set(__self__, "event_types", event_types)
        if every is not None:
            pulumi.set(__self__, "every", every)
        if gateways_event_source_locations is not None:
            pulumi.set(__self__, "gateways_event_source_locations", gateways_event_source_locations)
        if items_event_source_locations is not None:
            pulumi.set(__self__, "items_event_source_locations", items_event_source_locations)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if private_key_data is not None:
            pulumi.set(__self__, "private_key_data", private_key_data)
        if runner_type is not None:
            pulumi.set(__self__, "runner_type", runner_type)
        if server_certificates is not None:
            pulumi.set(__self__, "server_certificates", server_certificates)
        if targets_event_source_locations is not None:
            pulumi.set(__self__, "targets_event_source_locations", targets_event_source_locations)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter(name="authMethodsEventSourceLocations")
    def auth_methods_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Auth Methods event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "auth_methods_event_source_locations")

    @auth_methods_event_source_locations.setter
    def auth_methods_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "auth_methods_event_source_locations", value)

    @_builtins.property
    @pulumi.getter(name="authToken")
    def auth_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded Token string relevant for token auth-type
        """
        return pulumi.get(self, "auth_token")

    @auth_token.setter
    def auth_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_token", value)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Webhook authentication type [user-pass, bearer-token, certificate]
        """
        return pulumi.get(self, "auth_type")

    @auth_type.setter
    def auth_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_type", value)

    @_builtins.property
    @pulumi.getter(name="clientCertData")
    def client_cert_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded PEM certificate, relevant for certificate auth-type
        """
        return pulumi.get(self, "client_cert_data")

    @client_cert_data.setter
    def client_cert_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_cert_data", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="eventTypes")
    def event_types(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A comma-separated list of types of events to notify about
        """
        return pulumi.get(self, "event_types")

    @event_types.setter
    def event_types(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "event_types", value)

    @_builtins.property
    @pulumi.getter
    def every(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rate of periodic runner repetition in hours
        """
        return pulumi.get(self, "every")

    @every.setter
    def every(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "every", value)

    @_builtins.property
    @pulumi.getter(name="gatewaysEventSourceLocations")
    def gateways_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        """
        return pulumi.get(self, "gateways_event_source_locations")

    @gateways_event_source_locations.setter
    def gateways_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "gateways_event_source_locations", value)

    @_builtins.property
    @pulumi.getter(name="itemsEventSourceLocations")
    def items_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Items event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "items_event_source_locations")

    @items_event_source_locations.setter
    def items_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "items_event_source_locations", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Event Forwarder name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password for authentication relevant for user-pass auth-type
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="privateKeyData")
    def private_key_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        """
        return pulumi.get(self, "private_key_data")

    @private_key_data.setter
    def private_key_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "private_key_data", value)

    @_builtins.property
    @pulumi.getter(name="runnerType")
    def runner_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Event Forwarder runner type [immediate/periodic]
        """
        return pulumi.get(self, "runner_type")

    @runner_type.setter
    def runner_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "runner_type", value)

    @_builtins.property
    @pulumi.getter(name="serverCertificates")
    def server_certificates(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded PEM certificate of the Webhook
        """
        return pulumi.get(self, "server_certificates")

    @server_certificates.setter
    def server_certificates(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "server_certificates", value)

    @_builtins.property
    @pulumi.getter(name="targetsEventSourceLocations")
    def targets_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Targets event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "targets_event_source_locations")

    @targets_event_source_locations.setter
    def targets_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "targets_event_source_locations", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Webhook URL
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Username for authentication relevant for user-pass auth-type
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.input_type
class _EventForwarderWebhookState:
    def __init__(__self__, *,
                 auth_methods_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 auth_token: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 client_cert_data: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 event_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 every: Optional[pulumi.Input[_builtins.str]] = None,
                 gateways_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 items_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key_data: Optional[pulumi.Input[_builtins.str]] = None,
                 runner_type: Optional[pulumi.Input[_builtins.str]] = None,
                 server_certificates: Optional[pulumi.Input[_builtins.str]] = None,
                 targets_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering EventForwarderWebhook resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auth_methods_event_source_locations: Auth Methods event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] auth_token: Base64 encoded Token string relevant for token auth-type
        :param pulumi.Input[_builtins.str] auth_type: The Webhook authentication type [user-pass, bearer-token, certificate]
        :param pulumi.Input[_builtins.str] client_cert_data: Base64 encoded PEM certificate, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] event_types: A comma-separated list of types of events to notify about
        :param pulumi.Input[_builtins.str] every: Rate of periodic runner repetition in hours
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] gateways_event_source_locations: Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] items_event_source_locations: Items event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] key: Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        :param pulumi.Input[_builtins.str] name: Event Forwarder name
        :param pulumi.Input[_builtins.str] password: Password for authentication relevant for user-pass auth-type
        :param pulumi.Input[_builtins.str] private_key_data: Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] runner_type: Event Forwarder runner type [immediate/periodic]
        :param pulumi.Input[_builtins.str] server_certificates: Base64 encoded PEM certificate of the Webhook
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] targets_event_source_locations: Targets event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] url: Webhook URL
        :param pulumi.Input[_builtins.str] username: Username for authentication relevant for user-pass auth-type
        """
        if auth_methods_event_source_locations is not None:
            pulumi.set(__self__, "auth_methods_event_source_locations", auth_methods_event_source_locations)
        if auth_token is not None:
            pulumi.set(__self__, "auth_token", auth_token)
        if auth_type is not None:
            pulumi.set(__self__, "auth_type", auth_type)
        if client_cert_data is not None:
            pulumi.set(__self__, "client_cert_data", client_cert_data)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if event_types is not None:
            pulumi.set(__self__, "event_types", event_types)
        if every is not None:
            pulumi.set(__self__, "every", every)
        if gateways_event_source_locations is not None:
            pulumi.set(__self__, "gateways_event_source_locations", gateways_event_source_locations)
        if items_event_source_locations is not None:
            pulumi.set(__self__, "items_event_source_locations", items_event_source_locations)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if private_key_data is not None:
            pulumi.set(__self__, "private_key_data", private_key_data)
        if runner_type is not None:
            pulumi.set(__self__, "runner_type", runner_type)
        if server_certificates is not None:
            pulumi.set(__self__, "server_certificates", server_certificates)
        if targets_event_source_locations is not None:
            pulumi.set(__self__, "targets_event_source_locations", targets_event_source_locations)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter(name="authMethodsEventSourceLocations")
    def auth_methods_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Auth Methods event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "auth_methods_event_source_locations")

    @auth_methods_event_source_locations.setter
    def auth_methods_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "auth_methods_event_source_locations", value)

    @_builtins.property
    @pulumi.getter(name="authToken")
    def auth_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded Token string relevant for token auth-type
        """
        return pulumi.get(self, "auth_token")

    @auth_token.setter
    def auth_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_token", value)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Webhook authentication type [user-pass, bearer-token, certificate]
        """
        return pulumi.get(self, "auth_type")

    @auth_type.setter
    def auth_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_type", value)

    @_builtins.property
    @pulumi.getter(name="clientCertData")
    def client_cert_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded PEM certificate, relevant for certificate auth-type
        """
        return pulumi.get(self, "client_cert_data")

    @client_cert_data.setter
    def client_cert_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_cert_data", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="eventTypes")
    def event_types(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A comma-separated list of types of events to notify about
        """
        return pulumi.get(self, "event_types")

    @event_types.setter
    def event_types(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "event_types", value)

    @_builtins.property
    @pulumi.getter
    def every(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rate of periodic runner repetition in hours
        """
        return pulumi.get(self, "every")

    @every.setter
    def every(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "every", value)

    @_builtins.property
    @pulumi.getter(name="gatewaysEventSourceLocations")
    def gateways_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        """
        return pulumi.get(self, "gateways_event_source_locations")

    @gateways_event_source_locations.setter
    def gateways_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "gateways_event_source_locations", value)

    @_builtins.property
    @pulumi.getter(name="itemsEventSourceLocations")
    def items_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Items event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "items_event_source_locations")

    @items_event_source_locations.setter
    def items_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "items_event_source_locations", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Event Forwarder name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password for authentication relevant for user-pass auth-type
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="privateKeyData")
    def private_key_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        """
        return pulumi.get(self, "private_key_data")

    @private_key_data.setter
    def private_key_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "private_key_data", value)

    @_builtins.property
    @pulumi.getter(name="runnerType")
    def runner_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Event Forwarder runner type [immediate/periodic]
        """
        return pulumi.get(self, "runner_type")

    @runner_type.setter
    def runner_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "runner_type", value)

    @_builtins.property
    @pulumi.getter(name="serverCertificates")
    def server_certificates(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base64 encoded PEM certificate of the Webhook
        """
        return pulumi.get(self, "server_certificates")

    @server_certificates.setter
    def server_certificates(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "server_certificates", value)

    @_builtins.property
    @pulumi.getter(name="targetsEventSourceLocations")
    def targets_event_source_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Targets event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "targets_event_source_locations")

    @targets_event_source_locations.setter
    def targets_event_source_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "targets_event_source_locations", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Webhook URL
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Username for authentication relevant for user-pass auth-type
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.type_token("akeyless:index/eventForwarderWebhook:EventForwarderWebhook")
class EventForwarderWebhook(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_methods_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 auth_token: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 client_cert_data: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 event_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 every: Optional[pulumi.Input[_builtins.str]] = None,
                 gateways_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 items_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key_data: Optional[pulumi.Input[_builtins.str]] = None,
                 runner_type: Optional[pulumi.Input[_builtins.str]] = None,
                 server_certificates: Optional[pulumi.Input[_builtins.str]] = None,
                 targets_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a EventForwarderWebhook resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auth_methods_event_source_locations: Auth Methods event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] auth_token: Base64 encoded Token string relevant for token auth-type
        :param pulumi.Input[_builtins.str] auth_type: The Webhook authentication type [user-pass, bearer-token, certificate]
        :param pulumi.Input[_builtins.str] client_cert_data: Base64 encoded PEM certificate, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] event_types: A comma-separated list of types of events to notify about
        :param pulumi.Input[_builtins.str] every: Rate of periodic runner repetition in hours
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] gateways_event_source_locations: Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] items_event_source_locations: Items event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] key: Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        :param pulumi.Input[_builtins.str] name: Event Forwarder name
        :param pulumi.Input[_builtins.str] password: Password for authentication relevant for user-pass auth-type
        :param pulumi.Input[_builtins.str] private_key_data: Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] runner_type: Event Forwarder runner type [immediate/periodic]
        :param pulumi.Input[_builtins.str] server_certificates: Base64 encoded PEM certificate of the Webhook
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] targets_event_source_locations: Targets event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] url: Webhook URL
        :param pulumi.Input[_builtins.str] username: Username for authentication relevant for user-pass auth-type
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[EventForwarderWebhookArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a EventForwarderWebhook resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param EventForwarderWebhookArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EventForwarderWebhookArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_methods_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 auth_token: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_type: Optional[pulumi.Input[_builtins.str]] = None,
                 client_cert_data: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 event_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 every: Optional[pulumi.Input[_builtins.str]] = None,
                 gateways_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 items_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key_data: Optional[pulumi.Input[_builtins.str]] = None,
                 runner_type: Optional[pulumi.Input[_builtins.str]] = None,
                 server_certificates: Optional[pulumi.Input[_builtins.str]] = None,
                 targets_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EventForwarderWebhookArgs.__new__(EventForwarderWebhookArgs)

            __props__.__dict__["auth_methods_event_source_locations"] = auth_methods_event_source_locations
            __props__.__dict__["auth_token"] = None if auth_token is None else pulumi.Output.secret(auth_token)
            __props__.__dict__["auth_type"] = auth_type
            __props__.__dict__["client_cert_data"] = None if client_cert_data is None else pulumi.Output.secret(client_cert_data)
            __props__.__dict__["description"] = description
            __props__.__dict__["event_types"] = event_types
            __props__.__dict__["every"] = every
            __props__.__dict__["gateways_event_source_locations"] = gateways_event_source_locations
            __props__.__dict__["items_event_source_locations"] = items_event_source_locations
            __props__.__dict__["key"] = key
            __props__.__dict__["name"] = name
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["private_key_data"] = None if private_key_data is None else pulumi.Output.secret(private_key_data)
            __props__.__dict__["runner_type"] = runner_type
            __props__.__dict__["server_certificates"] = None if server_certificates is None else pulumi.Output.secret(server_certificates)
            __props__.__dict__["targets_event_source_locations"] = targets_event_source_locations
            __props__.__dict__["url"] = url
            __props__.__dict__["username"] = username
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["authToken", "clientCertData", "password", "privateKeyData", "serverCertificates"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(EventForwarderWebhook, __self__).__init__(
            'akeyless:index/eventForwarderWebhook:EventForwarderWebhook',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth_methods_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            auth_token: Optional[pulumi.Input[_builtins.str]] = None,
            auth_type: Optional[pulumi.Input[_builtins.str]] = None,
            client_cert_data: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            event_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            every: Optional[pulumi.Input[_builtins.str]] = None,
            gateways_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            items_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            password: Optional[pulumi.Input[_builtins.str]] = None,
            private_key_data: Optional[pulumi.Input[_builtins.str]] = None,
            runner_type: Optional[pulumi.Input[_builtins.str]] = None,
            server_certificates: Optional[pulumi.Input[_builtins.str]] = None,
            targets_event_source_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            url: Optional[pulumi.Input[_builtins.str]] = None,
            username: Optional[pulumi.Input[_builtins.str]] = None) -> 'EventForwarderWebhook':
        """
        Get an existing EventForwarderWebhook resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] auth_methods_event_source_locations: Auth Methods event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] auth_token: Base64 encoded Token string relevant for token auth-type
        :param pulumi.Input[_builtins.str] auth_type: The Webhook authentication type [user-pass, bearer-token, certificate]
        :param pulumi.Input[_builtins.str] client_cert_data: Base64 encoded PEM certificate, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] event_types: A comma-separated list of types of events to notify about
        :param pulumi.Input[_builtins.str] every: Rate of periodic runner repetition in hours
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] gateways_event_source_locations: Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] items_event_source_locations: Items event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] key: Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        :param pulumi.Input[_builtins.str] name: Event Forwarder name
        :param pulumi.Input[_builtins.str] password: Password for authentication relevant for user-pass auth-type
        :param pulumi.Input[_builtins.str] private_key_data: Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        :param pulumi.Input[_builtins.str] runner_type: Event Forwarder runner type [immediate/periodic]
        :param pulumi.Input[_builtins.str] server_certificates: Base64 encoded PEM certificate of the Webhook
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] targets_event_source_locations: Targets event sources to forward events about, for example: /abc/*
        :param pulumi.Input[_builtins.str] url: Webhook URL
        :param pulumi.Input[_builtins.str] username: Username for authentication relevant for user-pass auth-type
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _EventForwarderWebhookState.__new__(_EventForwarderWebhookState)

        __props__.__dict__["auth_methods_event_source_locations"] = auth_methods_event_source_locations
        __props__.__dict__["auth_token"] = auth_token
        __props__.__dict__["auth_type"] = auth_type
        __props__.__dict__["client_cert_data"] = client_cert_data
        __props__.__dict__["description"] = description
        __props__.__dict__["event_types"] = event_types
        __props__.__dict__["every"] = every
        __props__.__dict__["gateways_event_source_locations"] = gateways_event_source_locations
        __props__.__dict__["items_event_source_locations"] = items_event_source_locations
        __props__.__dict__["key"] = key
        __props__.__dict__["name"] = name
        __props__.__dict__["password"] = password
        __props__.__dict__["private_key_data"] = private_key_data
        __props__.__dict__["runner_type"] = runner_type
        __props__.__dict__["server_certificates"] = server_certificates
        __props__.__dict__["targets_event_source_locations"] = targets_event_source_locations
        __props__.__dict__["url"] = url
        __props__.__dict__["username"] = username
        return EventForwarderWebhook(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="authMethodsEventSourceLocations")
    def auth_methods_event_source_locations(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Auth Methods event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "auth_methods_event_source_locations")

    @_builtins.property
    @pulumi.getter(name="authToken")
    def auth_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Base64 encoded Token string relevant for token auth-type
        """
        return pulumi.get(self, "auth_token")

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The Webhook authentication type [user-pass, bearer-token, certificate]
        """
        return pulumi.get(self, "auth_type")

    @_builtins.property
    @pulumi.getter(name="clientCertData")
    def client_cert_data(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Base64 encoded PEM certificate, relevant for certificate auth-type
        """
        return pulumi.get(self, "client_cert_data")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="eventTypes")
    def event_types(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A comma-separated list of types of events to notify about
        """
        return pulumi.get(self, "event_types")

    @_builtins.property
    @pulumi.getter
    def every(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Rate of periodic runner repetition in hours
        """
        return pulumi.get(self, "every")

    @_builtins.property
    @pulumi.getter(name="gatewaysEventSourceLocations")
    def gateways_event_source_locations(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Gateways event sources to forward events about,for example the relevant Gateways cluster urls,: http://localhost:8000.
        """
        return pulumi.get(self, "gateways_event_source_locations")

    @_builtins.property
    @pulumi.getter(name="itemsEventSourceLocations")
    def items_event_source_locations(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Items event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "items_event_source_locations")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        Key name. The key will be used to encrypt the Event Forwarder secret value. If key name is not specified, the account default protection key is used
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Event Forwarder name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Password for authentication relevant for user-pass auth-type
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="privateKeyData")
    def private_key_data(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Base64 encoded PEM RSA Private Key, relevant for certificate auth-type
        """
        return pulumi.get(self, "private_key_data")

    @_builtins.property
    @pulumi.getter(name="runnerType")
    def runner_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Event Forwarder runner type [immediate/periodic]
        """
        return pulumi.get(self, "runner_type")

    @_builtins.property
    @pulumi.getter(name="serverCertificates")
    def server_certificates(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Base64 encoded PEM certificate of the Webhook
        """
        return pulumi.get(self, "server_certificates")

    @_builtins.property
    @pulumi.getter(name="targetsEventSourceLocations")
    def targets_event_source_locations(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Targets event sources to forward events about, for example: /abc/*
        """
        return pulumi.get(self, "targets_event_source_locations")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Webhook URL
        """
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Username for authentication relevant for user-pass auth-type
        """
        return pulumi.get(self, "username")

