# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProducerEksArgs', 'ProducerEks']

@pulumi.input_type
class ProducerEksArgs:
    def __init__(__self__, *,
                 eks_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_assume_role: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_ca_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_region: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 producer_encryption_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_allow_port_forwading: Optional[pulumi.Input[_builtins.bool]] = None,
                 secure_access_bastion_issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_enable: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_web: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_ttl: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ProducerEks resource.

        :param pulumi.Input[_builtins.str] eks_access_key_id: EKS Access Key ID
        :param pulumi.Input[_builtins.str] eks_assume_role: Role ARN. Role to assume when connecting to the EKS cluster
        :param pulumi.Input[_builtins.str] eks_cluster_ca_cert: EKS Cluster certificate. Base 64 encoded certificate.
        :param pulumi.Input[_builtins.str] eks_cluster_endpoint: EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        :param pulumi.Input[_builtins.str] eks_cluster_name: EKS cluster name. Must match the EKS cluster name you want to connect to.
        :param pulumi.Input[_builtins.str] eks_region: EKS Region
        :param pulumi.Input[_builtins.str] eks_secret_access_key: EKS Secret Access Key
        :param pulumi.Input[_builtins.str] name: Producer name
        :param pulumi.Input[_builtins.str] producer_encryption_key_name: Encrypt producer with following key
        :param pulumi.Input[_builtins.bool] secure_access_allow_port_forwading: Enable Port forwarding while using CLI access.
        :param pulumi.Input[_builtins.str] secure_access_bastion_issuer: Path to the SSH Certificate Issuer for your Akeyless Bastion
        :param pulumi.Input[_builtins.str] secure_access_cluster_endpoint: The K8s cluster endpoint URL
        :param pulumi.Input[_builtins.str] secure_access_enable: Enable/Disable secure remote access, [true/false]
        :param pulumi.Input[_builtins.bool] secure_access_web: Enable Web Secure Remote Access
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: Name of existing target to use in producer creation
        :param pulumi.Input[_builtins.str] user_ttl: User TTL
        """
        if eks_access_key_id is not None:
            pulumi.set(__self__, "eks_access_key_id", eks_access_key_id)
        if eks_assume_role is not None:
            pulumi.set(__self__, "eks_assume_role", eks_assume_role)
        if eks_cluster_ca_cert is not None:
            pulumi.set(__self__, "eks_cluster_ca_cert", eks_cluster_ca_cert)
        if eks_cluster_endpoint is not None:
            pulumi.set(__self__, "eks_cluster_endpoint", eks_cluster_endpoint)
        if eks_cluster_name is not None:
            pulumi.set(__self__, "eks_cluster_name", eks_cluster_name)
        if eks_region is not None:
            pulumi.set(__self__, "eks_region", eks_region)
        if eks_secret_access_key is not None:
            pulumi.set(__self__, "eks_secret_access_key", eks_secret_access_key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if producer_encryption_key_name is not None:
            pulumi.set(__self__, "producer_encryption_key_name", producer_encryption_key_name)
        if secure_access_allow_port_forwading is not None:
            pulumi.set(__self__, "secure_access_allow_port_forwading", secure_access_allow_port_forwading)
        if secure_access_bastion_issuer is not None:
            pulumi.set(__self__, "secure_access_bastion_issuer", secure_access_bastion_issuer)
        if secure_access_cluster_endpoint is not None:
            pulumi.set(__self__, "secure_access_cluster_endpoint", secure_access_cluster_endpoint)
        if secure_access_enable is not None:
            pulumi.set(__self__, "secure_access_enable", secure_access_enable)
        if secure_access_web is not None:
            pulumi.set(__self__, "secure_access_web", secure_access_web)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)
        if user_ttl is not None:
            pulumi.set(__self__, "user_ttl", user_ttl)

    @_builtins.property
    @pulumi.getter(name="eksAccessKeyId")
    def eks_access_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Access Key ID
        """
        return pulumi.get(self, "eks_access_key_id")

    @eks_access_key_id.setter
    def eks_access_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="eksAssumeRole")
    def eks_assume_role(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Role ARN. Role to assume when connecting to the EKS cluster
        """
        return pulumi.get(self, "eks_assume_role")

    @eks_assume_role.setter
    def eks_assume_role(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_assume_role", value)

    @_builtins.property
    @pulumi.getter(name="eksClusterCaCert")
    def eks_cluster_ca_cert(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Cluster certificate. Base 64 encoded certificate.
        """
        return pulumi.get(self, "eks_cluster_ca_cert")

    @eks_cluster_ca_cert.setter
    def eks_cluster_ca_cert(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_cluster_ca_cert", value)

    @_builtins.property
    @pulumi.getter(name="eksClusterEndpoint")
    def eks_cluster_endpoint(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        """
        return pulumi.get(self, "eks_cluster_endpoint")

    @eks_cluster_endpoint.setter
    def eks_cluster_endpoint(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_cluster_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="eksClusterName")
    def eks_cluster_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS cluster name. Must match the EKS cluster name you want to connect to.
        """
        return pulumi.get(self, "eks_cluster_name")

    @eks_cluster_name.setter
    def eks_cluster_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_cluster_name", value)

    @_builtins.property
    @pulumi.getter(name="eksRegion")
    def eks_region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Region
        """
        return pulumi.get(self, "eks_region")

    @eks_region.setter
    def eks_region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_region", value)

    @_builtins.property
    @pulumi.getter(name="eksSecretAccessKey")
    def eks_secret_access_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Secret Access Key
        """
        return pulumi.get(self, "eks_secret_access_key")

    @eks_secret_access_key.setter
    def eks_secret_access_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_secret_access_key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Producer name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="producerEncryptionKeyName")
    def producer_encryption_key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Encrypt producer with following key
        """
        return pulumi.get(self, "producer_encryption_key_name")

    @producer_encryption_key_name.setter
    def producer_encryption_key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "producer_encryption_key_name", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessAllowPortForwading")
    def secure_access_allow_port_forwading(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable Port forwarding while using CLI access.
        """
        return pulumi.get(self, "secure_access_allow_port_forwading")

    @secure_access_allow_port_forwading.setter
    def secure_access_allow_port_forwading(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "secure_access_allow_port_forwading", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessBastionIssuer")
    def secure_access_bastion_issuer(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to the SSH Certificate Issuer for your Akeyless Bastion
        """
        return pulumi.get(self, "secure_access_bastion_issuer")

    @secure_access_bastion_issuer.setter
    def secure_access_bastion_issuer(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secure_access_bastion_issuer", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessClusterEndpoint")
    def secure_access_cluster_endpoint(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The K8s cluster endpoint URL
        """
        return pulumi.get(self, "secure_access_cluster_endpoint")

    @secure_access_cluster_endpoint.setter
    def secure_access_cluster_endpoint(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secure_access_cluster_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessEnable")
    def secure_access_enable(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Enable/Disable secure remote access, [true/false]
        """
        return pulumi.get(self, "secure_access_enable")

    @secure_access_enable.setter
    def secure_access_enable(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secure_access_enable", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessWeb")
    def secure_access_web(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable Web Secure Remote Access
        """
        return pulumi.get(self, "secure_access_web")

    @secure_access_web.setter
    def secure_access_web(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "secure_access_web", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of existing target to use in producer creation
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "target_name", value)

    @_builtins.property
    @pulumi.getter(name="userTtl")
    def user_ttl(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User TTL
        """
        return pulumi.get(self, "user_ttl")

    @user_ttl.setter
    def user_ttl(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_ttl", value)


@pulumi.input_type
class _ProducerEksState:
    def __init__(__self__, *,
                 eks_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_assume_role: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_ca_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_region: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 producer_encryption_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_allow_port_forwading: Optional[pulumi.Input[_builtins.bool]] = None,
                 secure_access_bastion_issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_enable: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_web: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_ttl: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ProducerEks resources.

        :param pulumi.Input[_builtins.str] eks_access_key_id: EKS Access Key ID
        :param pulumi.Input[_builtins.str] eks_assume_role: Role ARN. Role to assume when connecting to the EKS cluster
        :param pulumi.Input[_builtins.str] eks_cluster_ca_cert: EKS Cluster certificate. Base 64 encoded certificate.
        :param pulumi.Input[_builtins.str] eks_cluster_endpoint: EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        :param pulumi.Input[_builtins.str] eks_cluster_name: EKS cluster name. Must match the EKS cluster name you want to connect to.
        :param pulumi.Input[_builtins.str] eks_region: EKS Region
        :param pulumi.Input[_builtins.str] eks_secret_access_key: EKS Secret Access Key
        :param pulumi.Input[_builtins.str] name: Producer name
        :param pulumi.Input[_builtins.str] producer_encryption_key_name: Encrypt producer with following key
        :param pulumi.Input[_builtins.bool] secure_access_allow_port_forwading: Enable Port forwarding while using CLI access.
        :param pulumi.Input[_builtins.str] secure_access_bastion_issuer: Path to the SSH Certificate Issuer for your Akeyless Bastion
        :param pulumi.Input[_builtins.str] secure_access_cluster_endpoint: The K8s cluster endpoint URL
        :param pulumi.Input[_builtins.str] secure_access_enable: Enable/Disable secure remote access, [true/false]
        :param pulumi.Input[_builtins.bool] secure_access_web: Enable Web Secure Remote Access
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: Name of existing target to use in producer creation
        :param pulumi.Input[_builtins.str] user_ttl: User TTL
        """
        if eks_access_key_id is not None:
            pulumi.set(__self__, "eks_access_key_id", eks_access_key_id)
        if eks_assume_role is not None:
            pulumi.set(__self__, "eks_assume_role", eks_assume_role)
        if eks_cluster_ca_cert is not None:
            pulumi.set(__self__, "eks_cluster_ca_cert", eks_cluster_ca_cert)
        if eks_cluster_endpoint is not None:
            pulumi.set(__self__, "eks_cluster_endpoint", eks_cluster_endpoint)
        if eks_cluster_name is not None:
            pulumi.set(__self__, "eks_cluster_name", eks_cluster_name)
        if eks_region is not None:
            pulumi.set(__self__, "eks_region", eks_region)
        if eks_secret_access_key is not None:
            pulumi.set(__self__, "eks_secret_access_key", eks_secret_access_key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if producer_encryption_key_name is not None:
            pulumi.set(__self__, "producer_encryption_key_name", producer_encryption_key_name)
        if secure_access_allow_port_forwading is not None:
            pulumi.set(__self__, "secure_access_allow_port_forwading", secure_access_allow_port_forwading)
        if secure_access_bastion_issuer is not None:
            pulumi.set(__self__, "secure_access_bastion_issuer", secure_access_bastion_issuer)
        if secure_access_cluster_endpoint is not None:
            pulumi.set(__self__, "secure_access_cluster_endpoint", secure_access_cluster_endpoint)
        if secure_access_enable is not None:
            pulumi.set(__self__, "secure_access_enable", secure_access_enable)
        if secure_access_web is not None:
            pulumi.set(__self__, "secure_access_web", secure_access_web)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)
        if user_ttl is not None:
            pulumi.set(__self__, "user_ttl", user_ttl)

    @_builtins.property
    @pulumi.getter(name="eksAccessKeyId")
    def eks_access_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Access Key ID
        """
        return pulumi.get(self, "eks_access_key_id")

    @eks_access_key_id.setter
    def eks_access_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="eksAssumeRole")
    def eks_assume_role(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Role ARN. Role to assume when connecting to the EKS cluster
        """
        return pulumi.get(self, "eks_assume_role")

    @eks_assume_role.setter
    def eks_assume_role(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_assume_role", value)

    @_builtins.property
    @pulumi.getter(name="eksClusterCaCert")
    def eks_cluster_ca_cert(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Cluster certificate. Base 64 encoded certificate.
        """
        return pulumi.get(self, "eks_cluster_ca_cert")

    @eks_cluster_ca_cert.setter
    def eks_cluster_ca_cert(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_cluster_ca_cert", value)

    @_builtins.property
    @pulumi.getter(name="eksClusterEndpoint")
    def eks_cluster_endpoint(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        """
        return pulumi.get(self, "eks_cluster_endpoint")

    @eks_cluster_endpoint.setter
    def eks_cluster_endpoint(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_cluster_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="eksClusterName")
    def eks_cluster_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS cluster name. Must match the EKS cluster name you want to connect to.
        """
        return pulumi.get(self, "eks_cluster_name")

    @eks_cluster_name.setter
    def eks_cluster_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_cluster_name", value)

    @_builtins.property
    @pulumi.getter(name="eksRegion")
    def eks_region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Region
        """
        return pulumi.get(self, "eks_region")

    @eks_region.setter
    def eks_region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_region", value)

    @_builtins.property
    @pulumi.getter(name="eksSecretAccessKey")
    def eks_secret_access_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        EKS Secret Access Key
        """
        return pulumi.get(self, "eks_secret_access_key")

    @eks_secret_access_key.setter
    def eks_secret_access_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "eks_secret_access_key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Producer name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="producerEncryptionKeyName")
    def producer_encryption_key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Encrypt producer with following key
        """
        return pulumi.get(self, "producer_encryption_key_name")

    @producer_encryption_key_name.setter
    def producer_encryption_key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "producer_encryption_key_name", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessAllowPortForwading")
    def secure_access_allow_port_forwading(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable Port forwarding while using CLI access.
        """
        return pulumi.get(self, "secure_access_allow_port_forwading")

    @secure_access_allow_port_forwading.setter
    def secure_access_allow_port_forwading(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "secure_access_allow_port_forwading", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessBastionIssuer")
    def secure_access_bastion_issuer(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Path to the SSH Certificate Issuer for your Akeyless Bastion
        """
        return pulumi.get(self, "secure_access_bastion_issuer")

    @secure_access_bastion_issuer.setter
    def secure_access_bastion_issuer(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secure_access_bastion_issuer", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessClusterEndpoint")
    def secure_access_cluster_endpoint(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The K8s cluster endpoint URL
        """
        return pulumi.get(self, "secure_access_cluster_endpoint")

    @secure_access_cluster_endpoint.setter
    def secure_access_cluster_endpoint(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secure_access_cluster_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessEnable")
    def secure_access_enable(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Enable/Disable secure remote access, [true/false]
        """
        return pulumi.get(self, "secure_access_enable")

    @secure_access_enable.setter
    def secure_access_enable(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secure_access_enable", value)

    @_builtins.property
    @pulumi.getter(name="secureAccessWeb")
    def secure_access_web(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable Web Secure Remote Access
        """
        return pulumi.get(self, "secure_access_web")

    @secure_access_web.setter
    def secure_access_web(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "secure_access_web", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of existing target to use in producer creation
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "target_name", value)

    @_builtins.property
    @pulumi.getter(name="userTtl")
    def user_ttl(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User TTL
        """
        return pulumi.get(self, "user_ttl")

    @user_ttl.setter
    def user_ttl(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_ttl", value)


@pulumi.type_token("akeyless:index/producerEks:ProducerEks")
class ProducerEks(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 eks_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_assume_role: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_ca_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_region: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 producer_encryption_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_allow_port_forwading: Optional[pulumi.Input[_builtins.bool]] = None,
                 secure_access_bastion_issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_enable: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_web: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_ttl: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ProducerEks resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] eks_access_key_id: EKS Access Key ID
        :param pulumi.Input[_builtins.str] eks_assume_role: Role ARN. Role to assume when connecting to the EKS cluster
        :param pulumi.Input[_builtins.str] eks_cluster_ca_cert: EKS Cluster certificate. Base 64 encoded certificate.
        :param pulumi.Input[_builtins.str] eks_cluster_endpoint: EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        :param pulumi.Input[_builtins.str] eks_cluster_name: EKS cluster name. Must match the EKS cluster name you want to connect to.
        :param pulumi.Input[_builtins.str] eks_region: EKS Region
        :param pulumi.Input[_builtins.str] eks_secret_access_key: EKS Secret Access Key
        :param pulumi.Input[_builtins.str] name: Producer name
        :param pulumi.Input[_builtins.str] producer_encryption_key_name: Encrypt producer with following key
        :param pulumi.Input[_builtins.bool] secure_access_allow_port_forwading: Enable Port forwarding while using CLI access.
        :param pulumi.Input[_builtins.str] secure_access_bastion_issuer: Path to the SSH Certificate Issuer for your Akeyless Bastion
        :param pulumi.Input[_builtins.str] secure_access_cluster_endpoint: The K8s cluster endpoint URL
        :param pulumi.Input[_builtins.str] secure_access_enable: Enable/Disable secure remote access, [true/false]
        :param pulumi.Input[_builtins.bool] secure_access_web: Enable Web Secure Remote Access
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: Name of existing target to use in producer creation
        :param pulumi.Input[_builtins.str] user_ttl: User TTL
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProducerEksArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ProducerEks resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProducerEksArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProducerEksArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 eks_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_assume_role: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_ca_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_region: Optional[pulumi.Input[_builtins.str]] = None,
                 eks_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 producer_encryption_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_allow_port_forwading: Optional[pulumi.Input[_builtins.bool]] = None,
                 secure_access_bastion_issuer: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_enable: Optional[pulumi.Input[_builtins.str]] = None,
                 secure_access_web: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_ttl: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProducerEksArgs.__new__(ProducerEksArgs)

            __props__.__dict__["eks_access_key_id"] = eks_access_key_id
            __props__.__dict__["eks_assume_role"] = eks_assume_role
            __props__.__dict__["eks_cluster_ca_cert"] = None if eks_cluster_ca_cert is None else pulumi.Output.secret(eks_cluster_ca_cert)
            __props__.__dict__["eks_cluster_endpoint"] = eks_cluster_endpoint
            __props__.__dict__["eks_cluster_name"] = eks_cluster_name
            __props__.__dict__["eks_region"] = eks_region
            __props__.__dict__["eks_secret_access_key"] = None if eks_secret_access_key is None else pulumi.Output.secret(eks_secret_access_key)
            __props__.__dict__["name"] = name
            __props__.__dict__["producer_encryption_key_name"] = producer_encryption_key_name
            __props__.__dict__["secure_access_allow_port_forwading"] = secure_access_allow_port_forwading
            __props__.__dict__["secure_access_bastion_issuer"] = secure_access_bastion_issuer
            __props__.__dict__["secure_access_cluster_endpoint"] = secure_access_cluster_endpoint
            __props__.__dict__["secure_access_enable"] = secure_access_enable
            __props__.__dict__["secure_access_web"] = secure_access_web
            __props__.__dict__["tags"] = tags
            __props__.__dict__["target_name"] = target_name
            __props__.__dict__["user_ttl"] = user_ttl
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["eksClusterCaCert", "eksSecretAccessKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ProducerEks, __self__).__init__(
            'akeyless:index/producerEks:ProducerEks',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            eks_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
            eks_assume_role: Optional[pulumi.Input[_builtins.str]] = None,
            eks_cluster_ca_cert: Optional[pulumi.Input[_builtins.str]] = None,
            eks_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
            eks_cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
            eks_region: Optional[pulumi.Input[_builtins.str]] = None,
            eks_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            producer_encryption_key_name: Optional[pulumi.Input[_builtins.str]] = None,
            secure_access_allow_port_forwading: Optional[pulumi.Input[_builtins.bool]] = None,
            secure_access_bastion_issuer: Optional[pulumi.Input[_builtins.str]] = None,
            secure_access_cluster_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
            secure_access_enable: Optional[pulumi.Input[_builtins.str]] = None,
            secure_access_web: Optional[pulumi.Input[_builtins.bool]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            target_name: Optional[pulumi.Input[_builtins.str]] = None,
            user_ttl: Optional[pulumi.Input[_builtins.str]] = None) -> 'ProducerEks':
        """
        Get an existing ProducerEks resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] eks_access_key_id: EKS Access Key ID
        :param pulumi.Input[_builtins.str] eks_assume_role: Role ARN. Role to assume when connecting to the EKS cluster
        :param pulumi.Input[_builtins.str] eks_cluster_ca_cert: EKS Cluster certificate. Base 64 encoded certificate.
        :param pulumi.Input[_builtins.str] eks_cluster_endpoint: EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        :param pulumi.Input[_builtins.str] eks_cluster_name: EKS cluster name. Must match the EKS cluster name you want to connect to.
        :param pulumi.Input[_builtins.str] eks_region: EKS Region
        :param pulumi.Input[_builtins.str] eks_secret_access_key: EKS Secret Access Key
        :param pulumi.Input[_builtins.str] name: Producer name
        :param pulumi.Input[_builtins.str] producer_encryption_key_name: Encrypt producer with following key
        :param pulumi.Input[_builtins.bool] secure_access_allow_port_forwading: Enable Port forwarding while using CLI access.
        :param pulumi.Input[_builtins.str] secure_access_bastion_issuer: Path to the SSH Certificate Issuer for your Akeyless Bastion
        :param pulumi.Input[_builtins.str] secure_access_cluster_endpoint: The K8s cluster endpoint URL
        :param pulumi.Input[_builtins.str] secure_access_enable: Enable/Disable secure remote access, [true/false]
        :param pulumi.Input[_builtins.bool] secure_access_web: Enable Web Secure Remote Access
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: Name of existing target to use in producer creation
        :param pulumi.Input[_builtins.str] user_ttl: User TTL
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProducerEksState.__new__(_ProducerEksState)

        __props__.__dict__["eks_access_key_id"] = eks_access_key_id
        __props__.__dict__["eks_assume_role"] = eks_assume_role
        __props__.__dict__["eks_cluster_ca_cert"] = eks_cluster_ca_cert
        __props__.__dict__["eks_cluster_endpoint"] = eks_cluster_endpoint
        __props__.__dict__["eks_cluster_name"] = eks_cluster_name
        __props__.__dict__["eks_region"] = eks_region
        __props__.__dict__["eks_secret_access_key"] = eks_secret_access_key
        __props__.__dict__["name"] = name
        __props__.__dict__["producer_encryption_key_name"] = producer_encryption_key_name
        __props__.__dict__["secure_access_allow_port_forwading"] = secure_access_allow_port_forwading
        __props__.__dict__["secure_access_bastion_issuer"] = secure_access_bastion_issuer
        __props__.__dict__["secure_access_cluster_endpoint"] = secure_access_cluster_endpoint
        __props__.__dict__["secure_access_enable"] = secure_access_enable
        __props__.__dict__["secure_access_web"] = secure_access_web
        __props__.__dict__["tags"] = tags
        __props__.__dict__["target_name"] = target_name
        __props__.__dict__["user_ttl"] = user_ttl
        return ProducerEks(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="eksAccessKeyId")
    def eks_access_key_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        EKS Access Key ID
        """
        return pulumi.get(self, "eks_access_key_id")

    @_builtins.property
    @pulumi.getter(name="eksAssumeRole")
    def eks_assume_role(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Role ARN. Role to assume when connecting to the EKS cluster
        """
        return pulumi.get(self, "eks_assume_role")

    @_builtins.property
    @pulumi.getter(name="eksClusterCaCert")
    def eks_cluster_ca_cert(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        EKS Cluster certificate. Base 64 encoded certificate.
        """
        return pulumi.get(self, "eks_cluster_ca_cert")

    @_builtins.property
    @pulumi.getter(name="eksClusterEndpoint")
    def eks_cluster_endpoint(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        EKS Cluster endpoint. https:// , <DNS / IP> of the cluster.
        """
        return pulumi.get(self, "eks_cluster_endpoint")

    @_builtins.property
    @pulumi.getter(name="eksClusterName")
    def eks_cluster_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        EKS cluster name. Must match the EKS cluster name you want to connect to.
        """
        return pulumi.get(self, "eks_cluster_name")

    @_builtins.property
    @pulumi.getter(name="eksRegion")
    def eks_region(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        EKS Region
        """
        return pulumi.get(self, "eks_region")

    @_builtins.property
    @pulumi.getter(name="eksSecretAccessKey")
    def eks_secret_access_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        EKS Secret Access Key
        """
        return pulumi.get(self, "eks_secret_access_key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Producer name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="producerEncryptionKeyName")
    def producer_encryption_key_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Encrypt producer with following key
        """
        return pulumi.get(self, "producer_encryption_key_name")

    @_builtins.property
    @pulumi.getter(name="secureAccessAllowPortForwading")
    def secure_access_allow_port_forwading(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable Port forwarding while using CLI access.
        """
        return pulumi.get(self, "secure_access_allow_port_forwading")

    @_builtins.property
    @pulumi.getter(name="secureAccessBastionIssuer")
    def secure_access_bastion_issuer(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Path to the SSH Certificate Issuer for your Akeyless Bastion
        """
        return pulumi.get(self, "secure_access_bastion_issuer")

    @_builtins.property
    @pulumi.getter(name="secureAccessClusterEndpoint")
    def secure_access_cluster_endpoint(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The K8s cluster endpoint URL
        """
        return pulumi.get(self, "secure_access_cluster_endpoint")

    @_builtins.property
    @pulumi.getter(name="secureAccessEnable")
    def secure_access_enable(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Enable/Disable secure remote access, [true/false]
        """
        return pulumi.get(self, "secure_access_enable")

    @_builtins.property
    @pulumi.getter(name="secureAccessWeb")
    def secure_access_web(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable Web Secure Remote Access
        """
        return pulumi.get(self, "secure_access_web")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of existing target to use in producer creation
        """
        return pulumi.get(self, "target_name")

    @_builtins.property
    @pulumi.getter(name="userTtl")
    def user_ttl(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        User TTL
        """
        return pulumi.get(self, "user_ttl")

