# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RotatedSecretAzureArgs', 'RotatedSecretAzure']

@pulumi.input_type
class RotatedSecretAzureArgs:
    def __init__(__self__, *,
                 rotator_type: pulumi.Input[_builtins.str],
                 target_name: pulumi.Input[_builtins.str],
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password_length: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_account_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a RotatedSecretAzure resource.

        :param pulumi.Input[_builtins.str] rotator_type: The rotator type [target/password/api-key/azure-storage-account]
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] app_id: Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with [use-self-creds/use-target-creds]
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] password_length: The length of the password to be generated
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] storage_account_key_name: The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] username: The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        pulumi.set(__self__, "rotator_type", rotator_type)
        pulumi.set(__self__, "target_name", target_name)
        if api_id is not None:
            pulumi.set(__self__, "api_id", api_id)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if app_id is not None:
            pulumi.set(__self__, "app_id", app_id)
        if authentication_credentials is not None:
            pulumi.set(__self__, "authentication_credentials", authentication_credentials)
        if auto_rotate is not None:
            pulumi.set(__self__, "auto_rotate", auto_rotate)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password_length is not None:
            pulumi.set(__self__, "password_length", password_length)
        if rotation_hour is not None:
            pulumi.set(__self__, "rotation_hour", rotation_hour)
        if rotation_interval is not None:
            pulumi.set(__self__, "rotation_interval", rotation_interval)
        if storage_account_key_name is not None:
            pulumi.set(__self__, "storage_account_key_name", storage_account_key_name)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter(name="rotatorType")
    def rotator_type(self) -> pulumi.Input[_builtins.str]:
        """
        The rotator type [target/password/api-key/azure-storage-account]
        """
        return pulumi.get(self, "rotator_type")

    @rotator_type.setter
    def rotator_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rotator_type", value)

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Input[_builtins.str]:
        """
        The target name to associate
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "target_name", value)

    @_builtins.property
    @pulumi.getter(name="apiId")
    def api_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API ID to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_id")

    @api_id.setter
    def api_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_id", value)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API key to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        """
        return pulumi.get(self, "app_id")

    @app_id.setter
    def app_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "app_id", value)

    @_builtins.property
    @pulumi.getter(name="authenticationCredentials")
    def authentication_credentials(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The credentials to connect with [use-self-creds/use-target-creds]
        """
        return pulumi.get(self, "authentication_credentials")

    @authentication_credentials.setter
    def authentication_credentials(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "authentication_credentials", value)

    @_builtins.property
    @pulumi.getter(name="autoRotate")
    def auto_rotate(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        """
        return pulumi.get(self, "auto_rotate")

    @auto_rotate.setter
    def auto_rotate(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auto_rotate", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secret name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="passwordLength")
    def password_length(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The length of the password to be generated
        """
        return pulumi.get(self, "password_length")

    @password_length.setter
    def password_length(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_length", value)

    @_builtins.property
    @pulumi.getter(name="rotationHour")
    def rotation_hour(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The Hour of the rotation in UTC
        """
        return pulumi.get(self, "rotation_hour")

    @rotation_hour.setter
    def rotation_hour(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rotation_hour", value)

    @_builtins.property
    @pulumi.getter(name="rotationInterval")
    def rotation_interval(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        """
        return pulumi.get(self, "rotation_interval")

    @rotation_interval.setter
    def rotation_interval(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotation_interval", value)

    @_builtins.property
    @pulumi.getter(name="storageAccountKeyName")
    def storage_account_key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        """
        return pulumi.get(self, "storage_account_key_name")

    @storage_account_key_name.setter
    def storage_account_key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "storage_account_key_name", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.input_type
class _RotatedSecretAzureState:
    def __init__(__self__, *,
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password_length: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_account_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering RotatedSecretAzure resources.

        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] app_id: Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with [use-self-creds/use-target-creds]
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] password_length: The length of the password to be generated
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_type: The rotator type [target/password/api-key/azure-storage-account]
        :param pulumi.Input[_builtins.str] storage_account_key_name: The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] username: The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        if api_id is not None:
            pulumi.set(__self__, "api_id", api_id)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if app_id is not None:
            pulumi.set(__self__, "app_id", app_id)
        if authentication_credentials is not None:
            pulumi.set(__self__, "authentication_credentials", authentication_credentials)
        if auto_rotate is not None:
            pulumi.set(__self__, "auto_rotate", auto_rotate)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password_length is not None:
            pulumi.set(__self__, "password_length", password_length)
        if rotation_hour is not None:
            pulumi.set(__self__, "rotation_hour", rotation_hour)
        if rotation_interval is not None:
            pulumi.set(__self__, "rotation_interval", rotation_interval)
        if rotator_type is not None:
            pulumi.set(__self__, "rotator_type", rotator_type)
        if storage_account_key_name is not None:
            pulumi.set(__self__, "storage_account_key_name", storage_account_key_name)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter(name="apiId")
    def api_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API ID to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_id")

    @api_id.setter
    def api_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_id", value)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API key to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        """
        return pulumi.get(self, "app_id")

    @app_id.setter
    def app_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "app_id", value)

    @_builtins.property
    @pulumi.getter(name="authenticationCredentials")
    def authentication_credentials(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The credentials to connect with [use-self-creds/use-target-creds]
        """
        return pulumi.get(self, "authentication_credentials")

    @authentication_credentials.setter
    def authentication_credentials(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "authentication_credentials", value)

    @_builtins.property
    @pulumi.getter(name="autoRotate")
    def auto_rotate(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        """
        return pulumi.get(self, "auto_rotate")

    @auto_rotate.setter
    def auto_rotate(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auto_rotate", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secret name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="passwordLength")
    def password_length(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The length of the password to be generated
        """
        return pulumi.get(self, "password_length")

    @password_length.setter
    def password_length(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_length", value)

    @_builtins.property
    @pulumi.getter(name="rotationHour")
    def rotation_hour(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The Hour of the rotation in UTC
        """
        return pulumi.get(self, "rotation_hour")

    @rotation_hour.setter
    def rotation_hour(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rotation_hour", value)

    @_builtins.property
    @pulumi.getter(name="rotationInterval")
    def rotation_interval(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        """
        return pulumi.get(self, "rotation_interval")

    @rotation_interval.setter
    def rotation_interval(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotation_interval", value)

    @_builtins.property
    @pulumi.getter(name="rotatorType")
    def rotator_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The rotator type [target/password/api-key/azure-storage-account]
        """
        return pulumi.get(self, "rotator_type")

    @rotator_type.setter
    def rotator_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotator_type", value)

    @_builtins.property
    @pulumi.getter(name="storageAccountKeyName")
    def storage_account_key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        """
        return pulumi.get(self, "storage_account_key_name")

    @storage_account_key_name.setter
    def storage_account_key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "storage_account_key_name", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The target name to associate
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "target_name", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.type_token("akeyless:index/rotatedSecretAzure:RotatedSecretAzure")
class RotatedSecretAzure(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password_length: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_account_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a RotatedSecretAzure resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] app_id: Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with [use-self-creds/use-target-creds]
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] password_length: The length of the password to be generated
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_type: The rotator type [target/password/api-key/azure-storage-account]
        :param pulumi.Input[_builtins.str] storage_account_key_name: The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] username: The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RotatedSecretAzureArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RotatedSecretAzure resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param RotatedSecretAzureArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RotatedSecretAzureArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 password_length: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
                 storage_account_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RotatedSecretAzureArgs.__new__(RotatedSecretAzureArgs)

            __props__.__dict__["api_id"] = api_id
            __props__.__dict__["api_key"] = api_key
            __props__.__dict__["app_id"] = app_id
            __props__.__dict__["authentication_credentials"] = authentication_credentials
            __props__.__dict__["auto_rotate"] = auto_rotate
            __props__.__dict__["description"] = description
            __props__.__dict__["key"] = key
            __props__.__dict__["name"] = name
            __props__.__dict__["password_length"] = password_length
            __props__.__dict__["rotation_hour"] = rotation_hour
            __props__.__dict__["rotation_interval"] = rotation_interval
            if rotator_type is None and not opts.urn:
                raise TypeError("Missing required property 'rotator_type'")
            __props__.__dict__["rotator_type"] = rotator_type
            __props__.__dict__["storage_account_key_name"] = storage_account_key_name
            __props__.__dict__["tags"] = tags
            if target_name is None and not opts.urn:
                raise TypeError("Missing required property 'target_name'")
            __props__.__dict__["target_name"] = target_name
            __props__.__dict__["username"] = username
        super(RotatedSecretAzure, __self__).__init__(
            'akeyless:index/rotatedSecretAzure:RotatedSecretAzure',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            api_id: Optional[pulumi.Input[_builtins.str]] = None,
            api_key: Optional[pulumi.Input[_builtins.str]] = None,
            app_id: Optional[pulumi.Input[_builtins.str]] = None,
            authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
            auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            password_length: Optional[pulumi.Input[_builtins.str]] = None,
            rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
            rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
            rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
            storage_account_key_name: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            target_name: Optional[pulumi.Input[_builtins.str]] = None,
            username: Optional[pulumi.Input[_builtins.str]] = None) -> 'RotatedSecretAzure':
        """
        Get an existing RotatedSecretAzure resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] app_id: Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with [use-self-creds/use-target-creds]
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] password_length: The length of the password to be generated
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_type: The rotator type [target/password/api-key/azure-storage-account]
        :param pulumi.Input[_builtins.str] storage_account_key_name: The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] username: The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RotatedSecretAzureState.__new__(_RotatedSecretAzureState)

        __props__.__dict__["api_id"] = api_id
        __props__.__dict__["api_key"] = api_key
        __props__.__dict__["app_id"] = app_id
        __props__.__dict__["authentication_credentials"] = authentication_credentials
        __props__.__dict__["auto_rotate"] = auto_rotate
        __props__.__dict__["description"] = description
        __props__.__dict__["key"] = key
        __props__.__dict__["name"] = name
        __props__.__dict__["password_length"] = password_length
        __props__.__dict__["rotation_hour"] = rotation_hour
        __props__.__dict__["rotation_interval"] = rotation_interval
        __props__.__dict__["rotator_type"] = rotator_type
        __props__.__dict__["storage_account_key_name"] = storage_account_key_name
        __props__.__dict__["tags"] = tags
        __props__.__dict__["target_name"] = target_name
        __props__.__dict__["username"] = username
        return RotatedSecretAzure(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiId")
    def api_id(self) -> pulumi.Output[_builtins.str]:
        """
        API ID to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_id")

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[_builtins.str]:
        """
        API key to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Id of the azure app that hold the serect to be rotated (relevant only for rotator-type=api-key & authentication-credentials=use-target-creds)
        """
        return pulumi.get(self, "app_id")

    @_builtins.property
    @pulumi.getter(name="authenticationCredentials")
    def authentication_credentials(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The credentials to connect with [use-self-creds/use-target-creds]
        """
        return pulumi.get(self, "authentication_credentials")

    @_builtins.property
    @pulumi.getter(name="autoRotate")
    def auto_rotate(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        """
        return pulumi.get(self, "auto_rotate")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Secret name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="passwordLength")
    def password_length(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The length of the password to be generated
        """
        return pulumi.get(self, "password_length")

    @_builtins.property
    @pulumi.getter(name="rotationHour")
    def rotation_hour(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The Hour of the rotation in UTC
        """
        return pulumi.get(self, "rotation_hour")

    @_builtins.property
    @pulumi.getter(name="rotationInterval")
    def rotation_interval(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        """
        return pulumi.get(self, "rotation_interval")

    @_builtins.property
    @pulumi.getter(name="rotatorType")
    def rotator_type(self) -> pulumi.Output[_builtins.str]:
        """
        The rotator type [target/password/api-key/azure-storage-account]
        """
        return pulumi.get(self, "rotator_type")

    @_builtins.property
    @pulumi.getter(name="storageAccountKeyName")
    def storage_account_key_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The name of the storage account key to rotate [key1/key2/kerb1/kerb2] (relevat to azure-storage-account)
        """
        return pulumi.get(self, "storage_account_key_name")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Output[_builtins.str]:
        """
        The target name to associate
        """
        return pulumi.get(self, "target_name")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The user principal name to rotate his password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "username")

