# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RotatedSecretArgs', 'RotatedSecret']

@pulumi.input_type
class RotatedSecretArgs:
    def __init__(__self__, *,
                 rotator_type: pulumi.Input[_builtins.str],
                 target_name: pulumi.Input[_builtins.str],
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_payload: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 ignore_cache: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_password: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_username: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_custom_cmd: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 user_attribute: Optional[pulumi.Input[_builtins.str]] = None,
                 user_dn: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a RotatedSecret resource.

        :param pulumi.Input[_builtins.str] rotator_type: The rotator type password/target/api-key/ldap/custom
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with use-user-creds/use-target-creds
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] custom_payload: Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] ignore_cache: Retrieve the Secret value without checking the Gateway's cache [true/false]
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] rotated_password: rotated-username password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.str] rotated_username: username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_custom_cmd: Custom rotation command (relevant only for ssh target)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] user_attribute: LDAP User Attribute
        :param pulumi.Input[_builtins.str] user_dn: Base DN to Perform User Search
        """
        pulumi.set(__self__, "rotator_type", rotator_type)
        pulumi.set(__self__, "target_name", target_name)
        if api_id is not None:
            pulumi.set(__self__, "api_id", api_id)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if authentication_credentials is not None:
            pulumi.set(__self__, "authentication_credentials", authentication_credentials)
        if auto_rotate is not None:
            pulumi.set(__self__, "auto_rotate", auto_rotate)
        if custom_payload is not None:
            pulumi.set(__self__, "custom_payload", custom_payload)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if ignore_cache is not None:
            pulumi.set(__self__, "ignore_cache", ignore_cache)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rotated_password is not None:
            pulumi.set(__self__, "rotated_password", rotated_password)
        if rotated_username is not None:
            pulumi.set(__self__, "rotated_username", rotated_username)
        if rotation_hour is not None:
            pulumi.set(__self__, "rotation_hour", rotation_hour)
        if rotation_interval is not None:
            pulumi.set(__self__, "rotation_interval", rotation_interval)
        if rotator_custom_cmd is not None:
            pulumi.set(__self__, "rotator_custom_cmd", rotator_custom_cmd)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if user_attribute is not None:
            pulumi.set(__self__, "user_attribute", user_attribute)
        if user_dn is not None:
            pulumi.set(__self__, "user_dn", user_dn)

    @_builtins.property
    @pulumi.getter(name="rotatorType")
    def rotator_type(self) -> pulumi.Input[_builtins.str]:
        """
        The rotator type password/target/api-key/ldap/custom
        """
        return pulumi.get(self, "rotator_type")

    @rotator_type.setter
    def rotator_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rotator_type", value)

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Input[_builtins.str]:
        """
        The target name to associate
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "target_name", value)

    @_builtins.property
    @pulumi.getter(name="apiId")
    def api_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API ID to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_id")

    @api_id.setter
    def api_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_id", value)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API key to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="authenticationCredentials")
    def authentication_credentials(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The credentials to connect with use-user-creds/use-target-creds
        """
        return pulumi.get(self, "authentication_credentials")

    @authentication_credentials.setter
    def authentication_credentials(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "authentication_credentials", value)

    @_builtins.property
    @pulumi.getter(name="autoRotate")
    def auto_rotate(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        """
        return pulumi.get(self, "auto_rotate")

    @auto_rotate.setter
    def auto_rotate(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auto_rotate", value)

    @_builtins.property
    @pulumi.getter(name="customPayload")
    def custom_payload(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        """
        return pulumi.get(self, "custom_payload")

    @custom_payload.setter
    def custom_payload(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "custom_payload", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="ignoreCache")
    def ignore_cache(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Retrieve the Secret value without checking the Gateway's cache [true/false]
        """
        return pulumi.get(self, "ignore_cache")

    @ignore_cache.setter
    def ignore_cache(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ignore_cache", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secret name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rotatedPassword")
    def rotated_password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        rotated-username password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "rotated_password")

    @rotated_password.setter
    def rotated_password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotated_password", value)

    @_builtins.property
    @pulumi.getter(name="rotatedUsername")
    def rotated_username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "rotated_username")

    @rotated_username.setter
    def rotated_username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotated_username", value)

    @_builtins.property
    @pulumi.getter(name="rotationHour")
    def rotation_hour(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The Hour of the rotation in UTC
        """
        return pulumi.get(self, "rotation_hour")

    @rotation_hour.setter
    def rotation_hour(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rotation_hour", value)

    @_builtins.property
    @pulumi.getter(name="rotationInterval")
    def rotation_interval(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        """
        return pulumi.get(self, "rotation_interval")

    @rotation_interval.setter
    def rotation_interval(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotation_interval", value)

    @_builtins.property
    @pulumi.getter(name="rotatorCustomCmd")
    def rotator_custom_cmd(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom rotation command (relevant only for ssh target)
        """
        return pulumi.get(self, "rotator_custom_cmd")

    @rotator_custom_cmd.setter
    def rotator_custom_cmd(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotator_custom_cmd", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="userAttribute")
    def user_attribute(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        LDAP User Attribute
        """
        return pulumi.get(self, "user_attribute")

    @user_attribute.setter
    def user_attribute(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_attribute", value)

    @_builtins.property
    @pulumi.getter(name="userDn")
    def user_dn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base DN to Perform User Search
        """
        return pulumi.get(self, "user_dn")

    @user_dn.setter
    def user_dn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_dn", value)


@pulumi.input_type
class _RotatedSecretState:
    def __init__(__self__, *,
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_payload: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 ignore_cache: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_password: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_username: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_custom_cmd: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_attribute: Optional[pulumi.Input[_builtins.str]] = None,
                 user_dn: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering RotatedSecret resources.

        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with use-user-creds/use-target-creds
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] custom_payload: Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] ignore_cache: Retrieve the Secret value without checking the Gateway's cache [true/false]
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] rotated_password: rotated-username password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.str] rotated_username: username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_custom_cmd: Custom rotation command (relevant only for ssh target)
        :param pulumi.Input[_builtins.str] rotator_type: The rotator type password/target/api-key/ldap/custom
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] user_attribute: LDAP User Attribute
        :param pulumi.Input[_builtins.str] user_dn: Base DN to Perform User Search
        """
        if api_id is not None:
            pulumi.set(__self__, "api_id", api_id)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if authentication_credentials is not None:
            pulumi.set(__self__, "authentication_credentials", authentication_credentials)
        if auto_rotate is not None:
            pulumi.set(__self__, "auto_rotate", auto_rotate)
        if custom_payload is not None:
            pulumi.set(__self__, "custom_payload", custom_payload)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if ignore_cache is not None:
            pulumi.set(__self__, "ignore_cache", ignore_cache)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rotated_password is not None:
            pulumi.set(__self__, "rotated_password", rotated_password)
        if rotated_username is not None:
            pulumi.set(__self__, "rotated_username", rotated_username)
        if rotation_hour is not None:
            pulumi.set(__self__, "rotation_hour", rotation_hour)
        if rotation_interval is not None:
            pulumi.set(__self__, "rotation_interval", rotation_interval)
        if rotator_custom_cmd is not None:
            pulumi.set(__self__, "rotator_custom_cmd", rotator_custom_cmd)
        if rotator_type is not None:
            pulumi.set(__self__, "rotator_type", rotator_type)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)
        if user_attribute is not None:
            pulumi.set(__self__, "user_attribute", user_attribute)
        if user_dn is not None:
            pulumi.set(__self__, "user_dn", user_dn)

    @_builtins.property
    @pulumi.getter(name="apiId")
    def api_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API ID to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_id")

    @api_id.setter
    def api_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_id", value)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API key to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="authenticationCredentials")
    def authentication_credentials(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The credentials to connect with use-user-creds/use-target-creds
        """
        return pulumi.get(self, "authentication_credentials")

    @authentication_credentials.setter
    def authentication_credentials(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "authentication_credentials", value)

    @_builtins.property
    @pulumi.getter(name="autoRotate")
    def auto_rotate(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        """
        return pulumi.get(self, "auto_rotate")

    @auto_rotate.setter
    def auto_rotate(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auto_rotate", value)

    @_builtins.property
    @pulumi.getter(name="customPayload")
    def custom_payload(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        """
        return pulumi.get(self, "custom_payload")

    @custom_payload.setter
    def custom_payload(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "custom_payload", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="ignoreCache")
    def ignore_cache(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Retrieve the Secret value without checking the Gateway's cache [true/false]
        """
        return pulumi.get(self, "ignore_cache")

    @ignore_cache.setter
    def ignore_cache(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ignore_cache", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secret name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rotatedPassword")
    def rotated_password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        rotated-username password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "rotated_password")

    @rotated_password.setter
    def rotated_password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotated_password", value)

    @_builtins.property
    @pulumi.getter(name="rotatedUsername")
    def rotated_username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "rotated_username")

    @rotated_username.setter
    def rotated_username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotated_username", value)

    @_builtins.property
    @pulumi.getter(name="rotationHour")
    def rotation_hour(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The Hour of the rotation in UTC
        """
        return pulumi.get(self, "rotation_hour")

    @rotation_hour.setter
    def rotation_hour(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rotation_hour", value)

    @_builtins.property
    @pulumi.getter(name="rotationInterval")
    def rotation_interval(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        """
        return pulumi.get(self, "rotation_interval")

    @rotation_interval.setter
    def rotation_interval(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotation_interval", value)

    @_builtins.property
    @pulumi.getter(name="rotatorCustomCmd")
    def rotator_custom_cmd(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom rotation command (relevant only for ssh target)
        """
        return pulumi.get(self, "rotator_custom_cmd")

    @rotator_custom_cmd.setter
    def rotator_custom_cmd(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotator_custom_cmd", value)

    @_builtins.property
    @pulumi.getter(name="rotatorType")
    def rotator_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The rotator type password/target/api-key/ldap/custom
        """
        return pulumi.get(self, "rotator_type")

    @rotator_type.setter
    def rotator_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rotator_type", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The target name to associate
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "target_name", value)

    @_builtins.property
    @pulumi.getter(name="userAttribute")
    def user_attribute(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        LDAP User Attribute
        """
        return pulumi.get(self, "user_attribute")

    @user_attribute.setter
    def user_attribute(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_attribute", value)

    @_builtins.property
    @pulumi.getter(name="userDn")
    def user_dn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base DN to Perform User Search
        """
        return pulumi.get(self, "user_dn")

    @user_dn.setter
    def user_dn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_dn", value)


@pulumi.type_token("akeyless:index/rotatedSecret:RotatedSecret")
class RotatedSecret(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_payload: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 ignore_cache: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_password: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_username: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_custom_cmd: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_attribute: Optional[pulumi.Input[_builtins.str]] = None,
                 user_dn: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a RotatedSecret resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with use-user-creds/use-target-creds
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] custom_payload: Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] ignore_cache: Retrieve the Secret value without checking the Gateway's cache [true/false]
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] rotated_password: rotated-username password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.str] rotated_username: username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_custom_cmd: Custom rotation command (relevant only for ssh target)
        :param pulumi.Input[_builtins.str] rotator_type: The rotator type password/target/api-key/ldap/custom
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] user_attribute: LDAP User Attribute
        :param pulumi.Input[_builtins.str] user_dn: Base DN to Perform User Search
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RotatedSecretArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RotatedSecret resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param RotatedSecretArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RotatedSecretArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_payload: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 ignore_cache: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_password: Optional[pulumi.Input[_builtins.str]] = None,
                 rotated_username: Optional[pulumi.Input[_builtins.str]] = None,
                 rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_custom_cmd: Optional[pulumi.Input[_builtins.str]] = None,
                 rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 target_name: Optional[pulumi.Input[_builtins.str]] = None,
                 user_attribute: Optional[pulumi.Input[_builtins.str]] = None,
                 user_dn: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RotatedSecretArgs.__new__(RotatedSecretArgs)

            __props__.__dict__["api_id"] = api_id
            __props__.__dict__["api_key"] = api_key
            __props__.__dict__["authentication_credentials"] = authentication_credentials
            __props__.__dict__["auto_rotate"] = auto_rotate
            __props__.__dict__["custom_payload"] = custom_payload
            __props__.__dict__["description"] = description
            __props__.__dict__["ignore_cache"] = ignore_cache
            __props__.__dict__["key"] = key
            __props__.__dict__["name"] = name
            __props__.__dict__["rotated_password"] = rotated_password
            __props__.__dict__["rotated_username"] = rotated_username
            __props__.__dict__["rotation_hour"] = rotation_hour
            __props__.__dict__["rotation_interval"] = rotation_interval
            __props__.__dict__["rotator_custom_cmd"] = rotator_custom_cmd
            if rotator_type is None and not opts.urn:
                raise TypeError("Missing required property 'rotator_type'")
            __props__.__dict__["rotator_type"] = rotator_type
            __props__.__dict__["tags"] = tags
            if target_name is None and not opts.urn:
                raise TypeError("Missing required property 'target_name'")
            __props__.__dict__["target_name"] = target_name
            __props__.__dict__["user_attribute"] = user_attribute
            __props__.__dict__["user_dn"] = user_dn
        super(RotatedSecret, __self__).__init__(
            'akeyless:index/rotatedSecret:RotatedSecret',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            api_id: Optional[pulumi.Input[_builtins.str]] = None,
            api_key: Optional[pulumi.Input[_builtins.str]] = None,
            authentication_credentials: Optional[pulumi.Input[_builtins.str]] = None,
            auto_rotate: Optional[pulumi.Input[_builtins.str]] = None,
            custom_payload: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            ignore_cache: Optional[pulumi.Input[_builtins.str]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            rotated_password: Optional[pulumi.Input[_builtins.str]] = None,
            rotated_username: Optional[pulumi.Input[_builtins.str]] = None,
            rotation_hour: Optional[pulumi.Input[_builtins.int]] = None,
            rotation_interval: Optional[pulumi.Input[_builtins.str]] = None,
            rotator_custom_cmd: Optional[pulumi.Input[_builtins.str]] = None,
            rotator_type: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            target_name: Optional[pulumi.Input[_builtins.str]] = None,
            user_attribute: Optional[pulumi.Input[_builtins.str]] = None,
            user_dn: Optional[pulumi.Input[_builtins.str]] = None) -> 'RotatedSecret':
        """
        Get an existing RotatedSecret resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_id: API ID to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] api_key: API key to rotate (relevant only for rotator-type=api-key)
        :param pulumi.Input[_builtins.str] authentication_credentials: The credentials to connect with use-user-creds/use-target-creds
        :param pulumi.Input[_builtins.str] auto_rotate: Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        :param pulumi.Input[_builtins.str] custom_payload: Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        :param pulumi.Input[_builtins.str] description: Description of the object
        :param pulumi.Input[_builtins.str] ignore_cache: Retrieve the Secret value without checking the Gateway's cache [true/false]
        :param pulumi.Input[_builtins.str] key: The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        :param pulumi.Input[_builtins.str] name: Secret name
        :param pulumi.Input[_builtins.str] rotated_password: rotated-username password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.str] rotated_username: username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        :param pulumi.Input[_builtins.int] rotation_hour: The Hour of the rotation in UTC
        :param pulumi.Input[_builtins.str] rotation_interval: The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        :param pulumi.Input[_builtins.str] rotator_custom_cmd: Custom rotation command (relevant only for ssh target)
        :param pulumi.Input[_builtins.str] rotator_type: The rotator type password/target/api-key/ldap/custom
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        :param pulumi.Input[_builtins.str] target_name: The target name to associate
        :param pulumi.Input[_builtins.str] user_attribute: LDAP User Attribute
        :param pulumi.Input[_builtins.str] user_dn: Base DN to Perform User Search
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RotatedSecretState.__new__(_RotatedSecretState)

        __props__.__dict__["api_id"] = api_id
        __props__.__dict__["api_key"] = api_key
        __props__.__dict__["authentication_credentials"] = authentication_credentials
        __props__.__dict__["auto_rotate"] = auto_rotate
        __props__.__dict__["custom_payload"] = custom_payload
        __props__.__dict__["description"] = description
        __props__.__dict__["ignore_cache"] = ignore_cache
        __props__.__dict__["key"] = key
        __props__.__dict__["name"] = name
        __props__.__dict__["rotated_password"] = rotated_password
        __props__.__dict__["rotated_username"] = rotated_username
        __props__.__dict__["rotation_hour"] = rotation_hour
        __props__.__dict__["rotation_interval"] = rotation_interval
        __props__.__dict__["rotator_custom_cmd"] = rotator_custom_cmd
        __props__.__dict__["rotator_type"] = rotator_type
        __props__.__dict__["tags"] = tags
        __props__.__dict__["target_name"] = target_name
        __props__.__dict__["user_attribute"] = user_attribute
        __props__.__dict__["user_dn"] = user_dn
        return RotatedSecret(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiId")
    def api_id(self) -> pulumi.Output[_builtins.str]:
        """
        API ID to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_id")

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[_builtins.str]:
        """
        API key to rotate (relevant only for rotator-type=api-key)
        """
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter(name="authenticationCredentials")
    def authentication_credentials(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The credentials to connect with use-user-creds/use-target-creds
        """
        return pulumi.get(self, "authentication_credentials")

    @_builtins.property
    @pulumi.getter(name="autoRotate")
    def auto_rotate(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
        """
        return pulumi.get(self, "auto_rotate")

    @_builtins.property
    @pulumi.getter(name="customPayload")
    def custom_payload(self) -> pulumi.Output[_builtins.str]:
        """
        Secret payload to be sent with rotation request (relevant only for rotator-type=custom)
        """
        return pulumi.get(self, "custom_payload")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the object
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="ignoreCache")
    def ignore_cache(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Retrieve the Secret value without checking the Gateway's cache [true/false]
        """
        return pulumi.get(self, "ignore_cache")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Secret name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="rotatedPassword")
    def rotated_password(self) -> pulumi.Output[_builtins.str]:
        """
        rotated-username password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "rotated_password")

    @_builtins.property
    @pulumi.getter(name="rotatedUsername")
    def rotated_username(self) -> pulumi.Output[_builtins.str]:
        """
        username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
        """
        return pulumi.get(self, "rotated_username")

    @_builtins.property
    @pulumi.getter(name="rotationHour")
    def rotation_hour(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The Hour of the rotation in UTC
        """
        return pulumi.get(self, "rotation_hour")

    @_builtins.property
    @pulumi.getter(name="rotationInterval")
    def rotation_interval(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
        """
        return pulumi.get(self, "rotation_interval")

    @_builtins.property
    @pulumi.getter(name="rotatorCustomCmd")
    def rotator_custom_cmd(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Custom rotation command (relevant only for ssh target)
        """
        return pulumi.get(self, "rotator_custom_cmd")

    @_builtins.property
    @pulumi.getter(name="rotatorType")
    def rotator_type(self) -> pulumi.Output[_builtins.str]:
        """
        The rotator type password/target/api-key/ldap/custom
        """
        return pulumi.get(self, "rotator_type")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Output[_builtins.str]:
        """
        The target name to associate
        """
        return pulumi.get(self, "target_name")

    @_builtins.property
    @pulumi.getter(name="userAttribute")
    def user_attribute(self) -> pulumi.Output[_builtins.str]:
        """
        LDAP User Attribute
        """
        return pulumi.get(self, "user_attribute")

    @_builtins.property
    @pulumi.getter(name="userDn")
    def user_dn(self) -> pulumi.Output[_builtins.str]:
        """
        Base DN to Perform User Search
        """
        return pulumi.get(self, "user_dn")

