// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless.Outputs
{

    [OutputType]
    public sealed class AuthMethodGcp
    {
        /// <summary>
        /// The audience to verify in the JWT received by the client
        /// </summary>
        public readonly string? Audience;
        /// <summary>
        /// IAM GCE Auth Method
        /// </summary>
        public readonly ImmutableArray<Outputs.AuthMethodGcpGce> Gces;
        /// <summary>
        /// IAM GCP Auth Method
        /// </summary>
        public readonly ImmutableArray<Outputs.AuthMethodGcpIam> Iams;
        /// <summary>
        /// Service Account creds data, base64 encoded
        /// </summary>
        public readonly string ServiceAccountCredsData;

        [OutputConstructor]
        private AuthMethodGcp(
            string? audience,

            ImmutableArray<Outputs.AuthMethodGcpGce> gces,

            ImmutableArray<Outputs.AuthMethodGcpIam> iams,

            string serviceAccountCredsData)
        {
            Audience = audience;
            Gces = gces;
            Iams = iams;
            ServiceAccountCredsData = serviceAccountCredsData;
        }
    }
}
