// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless.Outputs
{

    [OutputType]
    public sealed class GetAuthUidLoginResult
    {
        public readonly string? AccessId;
        public readonly string UidToken;

        [OutputConstructor]
        private GetAuthUidLoginResult(
            string? accessId,

            string uidToken)
        {
            AccessId = accessId;
            UidToken = uidToken;
        }
    }
}
