// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Akeyless.Inputs
{

    public sealed class RoleRuleGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("capabilities", required: true)]
        private InputList<string>? _capabilities;

        /// <summary>
        /// List of the approved/denied capabilities in the path options: [read, create, update, delete, list, deny] for sra-rule type: [allow_access, request_access, justify_access_only, approval_authority, upload_files, DownloadFiles]
        /// </summary>
        public InputList<string> Capabilities
        {
            get => _capabilities ?? (_capabilities = new InputList<string>());
            set => _capabilities = value;
        }

        /// <summary>
        /// The path the rule refers to
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// item-rule, target-rule, role-rule, auth-method-rule, sra-rule
        /// </summary>
        [Input("ruleType")]
        public Input<string>? RuleType { get; set; }

        public RoleRuleGetArgs()
        {
        }
        public static new RoleRuleGetArgs Empty => new RoleRuleGetArgs();
    }
}
