// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DynamicSecretGcp extends pulumi.CustomResource {
    /**
     * Get an existing DynamicSecretGcp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DynamicSecretGcpState, opts?: pulumi.CustomResourceOptions): DynamicSecretGcp {
        return new DynamicSecretGcp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'akeyless:index/dynamicSecretGcp:DynamicSecretGcp';

    /**
     * Returns true if the given object is an instance of DynamicSecretGcp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DynamicSecretGcp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DynamicSecretGcp.__pulumiType;
    }

    /**
     * The type of the GCP dynamic secret, options are [sa, external]
     */
    declare public readonly accessType: pulumi.Output<string | undefined>;
    /**
     * Customize how temporary usernames are generated using go template
     */
    declare public readonly customUsernameTemplate: pulumi.Output<string | undefined>;
    /**
     * Protection from accidental deletion of this item, [true/false]
     */
    declare public readonly deleteProtection: pulumi.Output<string | undefined>;
    /**
     * Encrypt dynamic secret details with following key
     */
    declare public readonly encryptionKeyName: pulumi.Output<string | undefined>;
    /**
     * For externally provided users, denotes the key-name of IdP claim to extract the username from
     */
    declare public readonly fixedUserClaimKeyname: pulumi.Output<string | undefined>;
    /**
     * Credentials type, options are [token, key]
     */
    declare public readonly gcpCredType: pulumi.Output<string | undefined>;
    /**
     * Base64-encoded service account private key text
     */
    declare public readonly gcpKey: pulumi.Output<string | undefined>;
    /**
     * Service account key algorithm, e.g. KEY_ALG_RSA_1024
     */
    declare public readonly gcpKeyAlgo: pulumi.Output<string | undefined>;
    /**
     * GCP service account email
     */
    declare public readonly gcpSaEmail: pulumi.Output<string | undefined>;
    /**
     * Access token scopes list, e.g. scope1,scope2
     */
    declare public readonly gcpTokenScopes: pulumi.Output<string | undefined>;
    /**
     * Dynamic secret name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * GCP Project ID override for dynamic secret operations
     */
    declare public readonly projectId: pulumi.Output<string | undefined>;
    /**
     * Role binding definitions in json format
     */
    declare public readonly roleBinding: pulumi.Output<string | undefined>;
    /**
     * Comma-separated list of GCP roles to assign to the user
     */
    declare public readonly roleNames: pulumi.Output<string | undefined>;
    /**
     * The type of the gcp dynamic secret. Options[fixed, dynamic]
     */
    declare public readonly serviceAccountType: pulumi.Output<string | undefined>;
    /**
     * List of the tags attached to this secret. To specify multiple tags use argument multiple times: --tag Tag1 --tag Tag2
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * Name of existing target to use in dynamic secret creation
     */
    declare public readonly targetName: pulumi.Output<string | undefined>;
    /**
     * User TTL (<=60m for access token)
     */
    declare public readonly userTtl: pulumi.Output<string | undefined>;

    /**
     * Create a DynamicSecretGcp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DynamicSecretGcpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DynamicSecretGcpArgs | DynamicSecretGcpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DynamicSecretGcpState | undefined;
            resourceInputs["accessType"] = state?.accessType;
            resourceInputs["customUsernameTemplate"] = state?.customUsernameTemplate;
            resourceInputs["deleteProtection"] = state?.deleteProtection;
            resourceInputs["encryptionKeyName"] = state?.encryptionKeyName;
            resourceInputs["fixedUserClaimKeyname"] = state?.fixedUserClaimKeyname;
            resourceInputs["gcpCredType"] = state?.gcpCredType;
            resourceInputs["gcpKey"] = state?.gcpKey;
            resourceInputs["gcpKeyAlgo"] = state?.gcpKeyAlgo;
            resourceInputs["gcpSaEmail"] = state?.gcpSaEmail;
            resourceInputs["gcpTokenScopes"] = state?.gcpTokenScopes;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["roleBinding"] = state?.roleBinding;
            resourceInputs["roleNames"] = state?.roleNames;
            resourceInputs["serviceAccountType"] = state?.serviceAccountType;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["targetName"] = state?.targetName;
            resourceInputs["userTtl"] = state?.userTtl;
        } else {
            const args = argsOrState as DynamicSecretGcpArgs | undefined;
            resourceInputs["accessType"] = args?.accessType;
            resourceInputs["customUsernameTemplate"] = args?.customUsernameTemplate;
            resourceInputs["deleteProtection"] = args?.deleteProtection;
            resourceInputs["encryptionKeyName"] = args?.encryptionKeyName;
            resourceInputs["fixedUserClaimKeyname"] = args?.fixedUserClaimKeyname;
            resourceInputs["gcpCredType"] = args?.gcpCredType;
            resourceInputs["gcpKey"] = args?.gcpKey;
            resourceInputs["gcpKeyAlgo"] = args?.gcpKeyAlgo;
            resourceInputs["gcpSaEmail"] = args?.gcpSaEmail;
            resourceInputs["gcpTokenScopes"] = args?.gcpTokenScopes;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["roleBinding"] = args?.roleBinding;
            resourceInputs["roleNames"] = args?.roleNames;
            resourceInputs["serviceAccountType"] = args?.serviceAccountType;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["targetName"] = args?.targetName;
            resourceInputs["userTtl"] = args?.userTtl;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DynamicSecretGcp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DynamicSecretGcp resources.
 */
export interface DynamicSecretGcpState {
    /**
     * The type of the GCP dynamic secret, options are [sa, external]
     */
    accessType?: pulumi.Input<string>;
    /**
     * Customize how temporary usernames are generated using go template
     */
    customUsernameTemplate?: pulumi.Input<string>;
    /**
     * Protection from accidental deletion of this item, [true/false]
     */
    deleteProtection?: pulumi.Input<string>;
    /**
     * Encrypt dynamic secret details with following key
     */
    encryptionKeyName?: pulumi.Input<string>;
    /**
     * For externally provided users, denotes the key-name of IdP claim to extract the username from
     */
    fixedUserClaimKeyname?: pulumi.Input<string>;
    /**
     * Credentials type, options are [token, key]
     */
    gcpCredType?: pulumi.Input<string>;
    /**
     * Base64-encoded service account private key text
     */
    gcpKey?: pulumi.Input<string>;
    /**
     * Service account key algorithm, e.g. KEY_ALG_RSA_1024
     */
    gcpKeyAlgo?: pulumi.Input<string>;
    /**
     * GCP service account email
     */
    gcpSaEmail?: pulumi.Input<string>;
    /**
     * Access token scopes list, e.g. scope1,scope2
     */
    gcpTokenScopes?: pulumi.Input<string>;
    /**
     * Dynamic secret name
     */
    name?: pulumi.Input<string>;
    /**
     * GCP Project ID override for dynamic secret operations
     */
    projectId?: pulumi.Input<string>;
    /**
     * Role binding definitions in json format
     */
    roleBinding?: pulumi.Input<string>;
    /**
     * Comma-separated list of GCP roles to assign to the user
     */
    roleNames?: pulumi.Input<string>;
    /**
     * The type of the gcp dynamic secret. Options[fixed, dynamic]
     */
    serviceAccountType?: pulumi.Input<string>;
    /**
     * List of the tags attached to this secret. To specify multiple tags use argument multiple times: --tag Tag1 --tag Tag2
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Name of existing target to use in dynamic secret creation
     */
    targetName?: pulumi.Input<string>;
    /**
     * User TTL (<=60m for access token)
     */
    userTtl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DynamicSecretGcp resource.
 */
export interface DynamicSecretGcpArgs {
    /**
     * The type of the GCP dynamic secret, options are [sa, external]
     */
    accessType?: pulumi.Input<string>;
    /**
     * Customize how temporary usernames are generated using go template
     */
    customUsernameTemplate?: pulumi.Input<string>;
    /**
     * Protection from accidental deletion of this item, [true/false]
     */
    deleteProtection?: pulumi.Input<string>;
    /**
     * Encrypt dynamic secret details with following key
     */
    encryptionKeyName?: pulumi.Input<string>;
    /**
     * For externally provided users, denotes the key-name of IdP claim to extract the username from
     */
    fixedUserClaimKeyname?: pulumi.Input<string>;
    /**
     * Credentials type, options are [token, key]
     */
    gcpCredType?: pulumi.Input<string>;
    /**
     * Base64-encoded service account private key text
     */
    gcpKey?: pulumi.Input<string>;
    /**
     * Service account key algorithm, e.g. KEY_ALG_RSA_1024
     */
    gcpKeyAlgo?: pulumi.Input<string>;
    /**
     * GCP service account email
     */
    gcpSaEmail?: pulumi.Input<string>;
    /**
     * Access token scopes list, e.g. scope1,scope2
     */
    gcpTokenScopes?: pulumi.Input<string>;
    /**
     * Dynamic secret name
     */
    name?: pulumi.Input<string>;
    /**
     * GCP Project ID override for dynamic secret operations
     */
    projectId?: pulumi.Input<string>;
    /**
     * Role binding definitions in json format
     */
    roleBinding?: pulumi.Input<string>;
    /**
     * Comma-separated list of GCP roles to assign to the user
     */
    roleNames?: pulumi.Input<string>;
    /**
     * The type of the gcp dynamic secret. Options[fixed, dynamic]
     */
    serviceAccountType?: pulumi.Input<string>;
    /**
     * List of the tags attached to this secret. To specify multiple tags use argument multiple times: --tag Tag1 --tag Tag2
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Name of existing target to use in dynamic secret creation
     */
    targetName?: pulumi.Input<string>;
    /**
     * User TTL (<=60m for access token)
     */
    userTtl?: pulumi.Input<string>;
}
