// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class GatewayLogForwardingSumologic extends pulumi.CustomResource {
    /**
     * Get an existing GatewayLogForwardingSumologic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayLogForwardingSumologicState, opts?: pulumi.CustomResourceOptions): GatewayLogForwardingSumologic {
        return new GatewayLogForwardingSumologic(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'akeyless:index/gatewayLogForwardingSumologic:GatewayLogForwardingSumologic';

    /**
     * Returns true if the given object is an instance of GatewayLogForwardingSumologic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayLogForwardingSumologic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayLogForwardingSumologic.__pulumiType;
    }

    /**
     * Enable Log Forwarding [true/false]
     */
    declare public readonly enable: pulumi.Output<string | undefined>;
    /**
     * Sumologic endpoint URL
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * Sumologic host
     */
    declare public readonly host: pulumi.Output<string | undefined>;
    /**
     * Logs format [text/json]
     */
    declare public readonly outputFormat: pulumi.Output<string | undefined>;
    /**
     * Pull interval in seconds
     */
    declare public readonly pullInterval: pulumi.Output<string | undefined>;
    /**
     * A comma-separated list of Sumologic tags
     */
    declare public readonly sumologicTags: pulumi.Output<string | undefined>;

    /**
     * Create a GatewayLogForwardingSumologic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GatewayLogForwardingSumologicArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayLogForwardingSumologicArgs | GatewayLogForwardingSumologicState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayLogForwardingSumologicState | undefined;
            resourceInputs["enable"] = state?.enable;
            resourceInputs["endpoint"] = state?.endpoint;
            resourceInputs["host"] = state?.host;
            resourceInputs["outputFormat"] = state?.outputFormat;
            resourceInputs["pullInterval"] = state?.pullInterval;
            resourceInputs["sumologicTags"] = state?.sumologicTags;
        } else {
            const args = argsOrState as GatewayLogForwardingSumologicArgs | undefined;
            resourceInputs["enable"] = args?.enable;
            resourceInputs["endpoint"] = args?.endpoint ? pulumi.secret(args.endpoint) : undefined;
            resourceInputs["host"] = args?.host;
            resourceInputs["outputFormat"] = args?.outputFormat;
            resourceInputs["pullInterval"] = args?.pullInterval;
            resourceInputs["sumologicTags"] = args?.sumologicTags;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["endpoint"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GatewayLogForwardingSumologic.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayLogForwardingSumologic resources.
 */
export interface GatewayLogForwardingSumologicState {
    /**
     * Enable Log Forwarding [true/false]
     */
    enable?: pulumi.Input<string>;
    /**
     * Sumologic endpoint URL
     */
    endpoint?: pulumi.Input<string>;
    /**
     * Sumologic host
     */
    host?: pulumi.Input<string>;
    /**
     * Logs format [text/json]
     */
    outputFormat?: pulumi.Input<string>;
    /**
     * Pull interval in seconds
     */
    pullInterval?: pulumi.Input<string>;
    /**
     * A comma-separated list of Sumologic tags
     */
    sumologicTags?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GatewayLogForwardingSumologic resource.
 */
export interface GatewayLogForwardingSumologicArgs {
    /**
     * Enable Log Forwarding [true/false]
     */
    enable?: pulumi.Input<string>;
    /**
     * Sumologic endpoint URL
     */
    endpoint?: pulumi.Input<string>;
    /**
     * Sumologic host
     */
    host?: pulumi.Input<string>;
    /**
     * Logs format [text/json]
     */
    outputFormat?: pulumi.Input<string>;
    /**
     * Pull interval in seconds
     */
    pullInterval?: pulumi.Input<string>;
    /**
     * A comma-separated list of Sumologic tags
     */
    sumologicTags?: pulumi.Input<string>;
}
