// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDetokenize(args: GetDetokenizeArgs, opts?: pulumi.InvokeOptions): Promise<GetDetokenizeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("akeyless:index/getDetokenize:getDetokenize", {
        "ciphertext": args.ciphertext,
        "tokenizerName": args.tokenizerName,
        "tweak": args.tweak,
    }, opts);
}

/**
 * A collection of arguments for invoking getDetokenize.
 */
export interface GetDetokenizeArgs {
    ciphertext: string;
    tokenizerName: string;
    tweak?: string;
}

/**
 * A collection of values returned by getDetokenize.
 */
export interface GetDetokenizeResult {
    readonly ciphertext: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly result: string;
    readonly tokenizerName: string;
    readonly tweak: string;
}
export function getDetokenizeOutput(args: GetDetokenizeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDetokenizeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("akeyless:index/getDetokenize:getDetokenize", {
        "ciphertext": args.ciphertext,
        "tokenizerName": args.tokenizerName,
        "tweak": args.tweak,
    }, opts);
}

/**
 * A collection of arguments for invoking getDetokenize.
 */
export interface GetDetokenizeOutputArgs {
    ciphertext: pulumi.Input<string>;
    tokenizerName: pulumi.Input<string>;
    tweak?: pulumi.Input<string>;
}
