// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPkiCertificate(args: GetPkiCertificateArgs, opts?: pulumi.InvokeOptions): Promise<GetPkiCertificateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("akeyless:index/getPkiCertificate:getPkiCertificate", {
        "altNames": args.altNames,
        "certIssuerName": args.certIssuerName,
        "commonName": args.commonName,
        "csrDataBase64": args.csrDataBase64,
        "extendedKeyUsage": args.extendedKeyUsage,
        "keyDataBase64": args.keyDataBase64,
        "ttl": args.ttl,
        "uriSans": args.uriSans,
    }, opts);
}

/**
 * A collection of arguments for invoking getPkiCertificate.
 */
export interface GetPkiCertificateArgs {
    altNames?: string;
    certIssuerName: string;
    commonName?: string;
    csrDataBase64?: string;
    extendedKeyUsage?: string;
    keyDataBase64?: string;
    ttl?: number;
    uriSans?: string;
}

/**
 * A collection of values returned by getPkiCertificate.
 */
export interface GetPkiCertificateResult {
    readonly altNames?: string;
    readonly certDisplayId: string;
    readonly certIssuerName: string;
    readonly commonName?: string;
    readonly csrDataBase64?: string;
    readonly data: string;
    readonly extendedKeyUsage?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keyDataBase64?: string;
    readonly parentCert: string;
    readonly readingToken: string;
    readonly ttl?: number;
    readonly uriSans?: string;
}
export function getPkiCertificateOutput(args: GetPkiCertificateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPkiCertificateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("akeyless:index/getPkiCertificate:getPkiCertificate", {
        "altNames": args.altNames,
        "certIssuerName": args.certIssuerName,
        "commonName": args.commonName,
        "csrDataBase64": args.csrDataBase64,
        "extendedKeyUsage": args.extendedKeyUsage,
        "keyDataBase64": args.keyDataBase64,
        "ttl": args.ttl,
        "uriSans": args.uriSans,
    }, opts);
}

/**
 * A collection of arguments for invoking getPkiCertificate.
 */
export interface GetPkiCertificateOutputArgs {
    altNames?: pulumi.Input<string>;
    certIssuerName: pulumi.Input<string>;
    commonName?: pulumi.Input<string>;
    csrDataBase64?: pulumi.Input<string>;
    extendedKeyUsage?: pulumi.Input<string>;
    keyDataBase64?: pulumi.Input<string>;
    ttl?: pulumi.Input<number>;
    uriSans?: pulumi.Input<string>;
}
