// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RotatedSecretCustom extends pulumi.CustomResource {
    /**
     * Get an existing RotatedSecretCustom resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RotatedSecretCustomState, opts?: pulumi.CustomResourceOptions): RotatedSecretCustom {
        return new RotatedSecretCustom(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'akeyless:index/rotatedSecretCustom:RotatedSecretCustom';

    /**
     * Returns true if the given object is an instance of RotatedSecretCustom.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RotatedSecretCustom {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RotatedSecretCustom.__pulumiType;
    }

    /**
     * Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
     */
    declare public readonly autoRotate: pulumi.Output<string | undefined>;
    /**
     * Secret payload to be sent with rotation request
     */
    declare public readonly customPayload: pulumi.Output<string>;
    /**
     * Description of the object
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * Secret name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The length of the password to be generated
     */
    declare public readonly passwordLength: pulumi.Output<string | undefined>;
    /**
     * The Hour of the rotation in UTC
     */
    declare public readonly rotationHour: pulumi.Output<number | undefined>;
    /**
     * The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
     */
    declare public readonly rotationInterval: pulumi.Output<string | undefined>;
    /**
     * List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * The target name to associate
     */
    declare public readonly targetName: pulumi.Output<string>;

    /**
     * Create a RotatedSecretCustom resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RotatedSecretCustomArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RotatedSecretCustomArgs | RotatedSecretCustomState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RotatedSecretCustomState | undefined;
            resourceInputs["autoRotate"] = state?.autoRotate;
            resourceInputs["customPayload"] = state?.customPayload;
            resourceInputs["description"] = state?.description;
            resourceInputs["key"] = state?.key;
            resourceInputs["name"] = state?.name;
            resourceInputs["passwordLength"] = state?.passwordLength;
            resourceInputs["rotationHour"] = state?.rotationHour;
            resourceInputs["rotationInterval"] = state?.rotationInterval;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["targetName"] = state?.targetName;
        } else {
            const args = argsOrState as RotatedSecretCustomArgs | undefined;
            if (args?.targetName === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetName'");
            }
            resourceInputs["autoRotate"] = args?.autoRotate;
            resourceInputs["customPayload"] = args?.customPayload;
            resourceInputs["description"] = args?.description;
            resourceInputs["key"] = args?.key;
            resourceInputs["name"] = args?.name;
            resourceInputs["passwordLength"] = args?.passwordLength;
            resourceInputs["rotationHour"] = args?.rotationHour;
            resourceInputs["rotationInterval"] = args?.rotationInterval;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["targetName"] = args?.targetName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RotatedSecretCustom.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RotatedSecretCustom resources.
 */
export interface RotatedSecretCustomState {
    /**
     * Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
     */
    autoRotate?: pulumi.Input<string>;
    /**
     * Secret payload to be sent with rotation request
     */
    customPayload?: pulumi.Input<string>;
    /**
     * Description of the object
     */
    description?: pulumi.Input<string>;
    /**
     * The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     */
    key?: pulumi.Input<string>;
    /**
     * Secret name
     */
    name?: pulumi.Input<string>;
    /**
     * The length of the password to be generated
     */
    passwordLength?: pulumi.Input<string>;
    /**
     * The Hour of the rotation in UTC
     */
    rotationHour?: pulumi.Input<number>;
    /**
     * The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
     */
    rotationInterval?: pulumi.Input<string>;
    /**
     * List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The target name to associate
     */
    targetName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RotatedSecretCustom resource.
 */
export interface RotatedSecretCustomArgs {
    /**
     * Whether to automatically rotate every --rotation-interval days, or disable existing automatic rotation
     */
    autoRotate?: pulumi.Input<string>;
    /**
     * Secret payload to be sent with rotation request
     */
    customPayload?: pulumi.Input<string>;
    /**
     * Description of the object
     */
    description?: pulumi.Input<string>;
    /**
     * The name of a key that is used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     */
    key?: pulumi.Input<string>;
    /**
     * Secret name
     */
    name?: pulumi.Input<string>;
    /**
     * The length of the password to be generated
     */
    passwordLength?: pulumi.Input<string>;
    /**
     * The Hour of the rotation in UTC
     */
    rotationHour?: pulumi.Input<number>;
    /**
     * The number of days to wait between every automatic rotation (1-365),custom rotator interval will be set in minutes
     */
    rotationInterval?: pulumi.Input<string>;
    /**
     * List of the tags attached to this secret. To specify multiple tags use argument multiple times: -t Tag1 -t Tag2
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The target name to associate
     */
    targetName: pulumi.Input<string>;
}
