// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TargetGcp extends pulumi.CustomResource {
    /**
     * Get an existing TargetGcp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TargetGcpState, opts?: pulumi.CustomResourceOptions): TargetGcp {
        return new TargetGcp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'akeyless:index/targetGcp:TargetGcp';

    /**
     * Returns true if the given object is an instance of TargetGcp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TargetGcp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TargetGcp.__pulumiType;
    }

    /**
     * Description of the object
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Base64-encoded service account private key text
     */
    declare public readonly gcpKey: pulumi.Output<string | undefined>;
    /**
     * GCP service account email
     */
    declare public readonly gcpSaEmail: pulumi.Output<string | undefined>;
    /**
     * Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
     */
    declare public readonly key: pulumi.Output<string | undefined>;
    /**
     * Target name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Use the GW's Cloud IAM
     */
    declare public readonly useGwCloudIdentity: pulumi.Output<boolean | undefined>;

    /**
     * Create a TargetGcp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TargetGcpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TargetGcpArgs | TargetGcpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TargetGcpState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["gcpKey"] = state?.gcpKey;
            resourceInputs["gcpSaEmail"] = state?.gcpSaEmail;
            resourceInputs["key"] = state?.key;
            resourceInputs["name"] = state?.name;
            resourceInputs["useGwCloudIdentity"] = state?.useGwCloudIdentity;
        } else {
            const args = argsOrState as TargetGcpArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["gcpKey"] = args?.gcpKey ? pulumi.secret(args.gcpKey) : undefined;
            resourceInputs["gcpSaEmail"] = args?.gcpSaEmail;
            resourceInputs["key"] = args?.key;
            resourceInputs["name"] = args?.name;
            resourceInputs["useGwCloudIdentity"] = args?.useGwCloudIdentity;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["gcpKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(TargetGcp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TargetGcp resources.
 */
export interface TargetGcpState {
    /**
     * Description of the object
     */
    description?: pulumi.Input<string>;
    /**
     * Base64-encoded service account private key text
     */
    gcpKey?: pulumi.Input<string>;
    /**
     * GCP service account email
     */
    gcpSaEmail?: pulumi.Input<string>;
    /**
     * Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
     */
    key?: pulumi.Input<string>;
    /**
     * Target name
     */
    name?: pulumi.Input<string>;
    /**
     * Use the GW's Cloud IAM
     */
    useGwCloudIdentity?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a TargetGcp resource.
 */
export interface TargetGcpArgs {
    /**
     * Description of the object
     */
    description?: pulumi.Input<string>;
    /**
     * Base64-encoded service account private key text
     */
    gcpKey?: pulumi.Input<string>;
    /**
     * GCP service account email
     */
    gcpSaEmail?: pulumi.Input<string>;
    /**
     * Key name. The key will be used to encrypt the target secret value. If key name is not specified, the account default protection key is used
     */
    key?: pulumi.Input<string>;
    /**
     * Target name
     */
    name?: pulumi.Input<string>;
    /**
     * Use the GW's Cloud IAM
     */
    useGwCloudIdentity?: pulumi.Input<boolean>;
}
